<x-layouts.app title="Hjelp · DekkPilot" heading="Hjelp">
@php
    $roleLabels=['owner'=>'Eier','admin'=>'Administrator','manager'=>'Avdelingsleder','customer_service'=>'Kundebehandler','technician'=>'Verkstedmedarbeider','warehouse'=>'Lagermedarbeider','accounting'=>'Regnskap'];
    $role=auth()->user()->is_super_admin?'Superadmin':($roleLabels[auth()->user()->role]??ucfirst(auth()->user()->role));
@endphp
<section class="panel help-hero"><div class="help-hero-copy"><span class="help-hero-mark">?</span><div><p class="eyebrow">DEKKPILOT HJELPESENTER</p><h2>Hva kan vi hjelpe deg med?</h2><p>Praktiske forklaringer fra første kunde til ferdig jobb – skrevet for mennesker som skal få arbeidet gjort.</p></div></div><div class="help-user"><span class="help-user-label">DIN VISNING</span><div><span class="help-user-avatar">{{ mb_strtoupper(mb_substr(auth()->user()->name,0,1)) }}</span><span><strong>{{ auth()->user()->name }}</strong><small>{{ $role }} · {{ session('ui_mode')==='technician'?'Teknikermodus':'Full portal' }}</small></span></div><small>{{ auth()->user()->organization?->name }}</small></div></section>

<nav class="help-start" aria-label="Hopp til hjelp"><a href="#kom-i-gang"><span>01</span><b>Kom i gang</b><small>De viktigste stegene først.</small><i>→</i></a><a href="#daglig-drift"><span>02</span><b>Daglig drift</b><small>Booking, hjul og jobber.</small><i>→</i></a><a href="#tekniker"><span>03</span><b>Teknikermodus</b><small>Dagens arbeid på mobil.</small><i>→</i></a><a href="#ofte-spurt"><span>04</span><b>Ofte spurt</b><small>Raske svar når du står fast.</small><i>→</i></a></nav>

<section class="panel help-section" id="kom-i-gang"><div class="panel-head"><div><p class="eyebrow">FØRSTE GANG</p><h2>Kom i gang på fem steg</h2></div></div><ol class="help-steps"><li><strong>Kontroller virksomheten</strong><p>Eier eller administrator åpner Admin og setter tjenester, priser, åpningstider, ansatte, arbeidsbukker og lagerplasser.</p></li><li><strong>Sett opp kommunikasjon</strong><p>Under Admin → E-post og backup legger virksomheten inn avsender og svaradresse. Twilio settes opp separat dersom SMS skal brukes.</p></li><li><strong>Registrer første kunde</strong><p>Trykk «Ny kunde», fyll inn kontaktinformasjon og gå videre til kjøretøy. Registreringsnummer kan bare registreres én gang.</p></li><li><strong>Opprett booking</strong><p>Søk etter navn eller registreringsnummer, velg én eller flere tjenester og bruk forslagene til ledige tider.</p></li><li><strong>Registrer hjulsettet</strong><p>Mål alle fire dekk, registrer vask og tilstand, velg lagerplass og skriv ut etikett.</p></li></ol></section>

<section class="grid two help-section" id="daglig-drift"><article class="panel"><p class="eyebrow">KUNDER OG BOOKING</p><h2>Fra telefon til avtale</h2><ol class="help-steps"><li><strong>Finn kunden</strong><p>Søk på navn eller registreringsnummer. Starter du fra kundekortet, følger kunden og bilen automatisk med til bookingen.</p></li><li><strong>Velg arbeidet</strong><p>Velg alle tjenestene som skal utføres. Tidsbehovet beregnes samlet.</p></li><li><strong>Finn tid</strong><p>Velg første ledige eller se de neste ledige tidene. Rød markering betyr overbooket kapasitet, men tiden kan fortsatt velges.</p></li><li><strong>Følg bekreftelsen</strong><p>Bekreftet og ventende vises tydelig. Ubekreftede timer følges opp automatisk.</p></li></ol></article><article class="panel"><p class="eyebrow">HJULHOTELL</p><h2>Fra mottak til utlevering</h2><ol class="help-steps"><li><strong>Mottak</strong><p>Finn kunde/bil, registrer settet og bruk bilfiguren til fire enkle mønsterdybdemålinger.</p></li><li><strong>Kontroll</strong><p>Marker skade, vaskebehov og bilder. Manglende opplysninger vises under «Krever handling».</p></li><li><strong>Lagring</strong><p>Velg reol og hylle fra lagerkartet. Etiketten representerer hele hjulsettet.</p></li><li><strong>Klargjøring</strong><p>«Min arbeidsdag» viser hvilke sett som skal finnes frem til morgendagens avtaler.</p></li><li><strong>Utlevering</strong><p>Skann settet, oppdater status og fullfør jobben. Feil fullføring kan åpnes igjen.</p></li></ol></article></section>

<section class="grid two help-section"><article class="panel"><p class="eyebrow">TILBUD OG MERSALG</p><h2>Når dekk bør skiftes</h2><p class="muted">Lav mønsterdybde oppretter en salgsmulighet. Systemet matcher dimensjon og sesong mot lageret.</p><ol class="help-steps"><li><strong>Åpne forslaget</strong><p>Kontroller bilen, målingen og tilgjengelige produkter.</p></li><li><strong>Velg alternativer</strong><p>Presenter opptil tre gode valg: «Godt valg», «Bra valg» og «Det beste».</p></li><li><strong>Forhåndsvis</strong><p>Se nøyaktig hvordan e-posten blir før den sendes.</p></li><li><strong>Kundens svar</strong><p>Kunden åpner sikker lenke, velger alternativ og godtar kjøpsvilkår.</p></li></ol></article><article class="panel"><p class="eyebrow">FULLFØRING OG REGNSKAP</p><h2>Avslutt jobben riktig</h2><ol class="help-steps"><li><strong>Kontroller oppgavene</strong><p>Fyll ut nødvendige kontrollpunkter og avvik før fullføring.</p></li><li><strong>Marker ferdig</strong><p>Jobb og booking fullføres. Trykk igjen for å åpne den dersom noe var feil.</p></li><li><strong>Fakturagrunnlag</strong><p>Grunnlaget opprettes automatisk og sendes direkte eller legges i manuell kø.</p></li><li><strong>Følg feil</strong><p>Admin → Regnskap viser om eksport til Fiken eller Tripletex er sendt eller feilet.</p></li></ol></article></section>

<section class="panel help-section" id="tekniker"><div class="panel-head"><div><p class="eyebrow">MOBIL OG NETTBRETT</p><h2>Teknikermodus</h2></div></div><p class="muted">Teknikermodus viser bare det verkstedmedarbeideren trenger akkurat nå. På mobil bruker du menyen nederst.</p><div class="help-role"><span>I dag – dagens bookinger</span><span>Kart – finn lagerplass</span><span>Hjul – søk og skann</span><span>Avvik – manglende kontroll</span><span>Bytt – gå til full portal</span></div><ol class="help-steps"><li><strong>Åpne dagens jobb</strong><p>Se kunde, bil, tjenester og hvor hjulene ligger.</p></li><li><strong>Skann én gang</strong><p>Én QR-kode identifiserer hele settet; du trenger ikke skanne fire dekk.</p></li><li><strong>Mål og dokumenter</strong><p>Bruk store felter og kamera til mønsterdybde, tilstand, vask og bilde.</p></li><li><strong>Flytt status</strong><p>Oppdater settet videre i flyten slik at resten av teamet alltid ser riktig status.</p></li></ol></section>

<section class="grid two help-section"><article class="panel"><p class="eyebrow">HVEM KAN GJØRE HVA?</p><h2>Roller</h2><div class="help-role"><span>Eier: alt i egen virksomhet</span><span>Admin: oppsett og drift</span><span>Avdelingsleder: kapasitet og jobber</span><span>Kundebehandler: kunder og booking</span><span>Tekniker: dagens arbeid</span><span>Lager: hjul og plassering</span><span>Regnskap: fakturakø</span><span>Superadmin: hele plattformen</span></div><p class="muted">Ser du ikke en funksjon, skyldes det vanligvis rollen din eller at du er i teknikermodus. Velg «Bytt visning» for full portal.</p></article><article class="panel"><p class="eyebrow">TRYGG BRUK</p><h2>Viktig å huske</h2><ul class="check"><li>Del aldri passord, API-nøkler eller kundelenker.</li><li>Bruk tofaktor når du har administrativ tilgang.</li><li>Kontroller mottaker og forhåndsvisning før masseutsending.</li><li>Ikke bruk ekte persondata i demo.</li><li>Logg ut på delte enheter.</li><li>Kontakt administrator dersom data ser ut til å tilhøre feil virksomhet.</li></ul></article></section>

<section class="panel help-faq help-section" id="ofte-spurt"><p class="eyebrow">RASKE SVAR</p><h2>Ofte stilte spørsmål</h2><details open><summary>Hvorfor får jeg ikke sendt e-post?</summary><p>Administrator må sette virksomhetens avsender og sende en test. Superadmin må ha konfigurert servertransporten. Se også meldingskøen for konkret feilmelding. Demo sender aldri.</p></details><details><summary>Hvorfor ser jeg ingen ledige timer?</summary><p>Kontroller åpningstid, aktive tjenester, varighet, ansatte og eventuelle arbeidsbukker under Admin. Prøv deretter en annen dato.</p></details><details><summary>Hvorfor er en booking rød?</summary><p>Det er flere samtidige bookinger enn registrert kapasitet. Bookingen tillates, men bør vurderes av driftsleder.</p></details><details><summary>Kan en bil flyttes til en ny eier?</summary><p>Ja. Åpne kunden og bilen, velg flytting og søk etter den nye kunden. Historikken følger bilen.</p></details><details><summary>Hvor finner jeg hjulene til i morgen?</summary><p>Åpne «Min arbeidsdag» og se «Finn frem til i morgen». Lagerplass vises på hver rad.</p></details><details><summary>Jeg fullførte feil jobb – hva gjør jeg?</summary><p>Åpne jobben/bookingen og velg å åpne den igjen. Status går tilbake til ventende arbeid.</p></details><details><summary>Hvordan bytter jeg mellom mobil- og fullvisning?</summary><p>Bruk «Visning» ved brukeropplysningene, eller «Bytt» i bunnmenyen i teknikermodus.</p></details></section>

<section class="panel help-callout"><div><p class="eyebrow">FORTSATT FAST?</p><h2>Ta med det som gjør feilsøkingen enkel</h2><p>Noter hvilken side du var på, tidspunktet, hva du trykket på og den nøyaktige feilmeldingen. Ikke send passord eller API-nøkler.</p></div><a class="button" href="mailto:hei@dekkpilot.no?subject=Hjelp%20med%20DekkPilot">Kontakt support</a></section>
</x-layouts.app>
