<x-layouts.app title="Hjelp · DekkPilot" heading="Hjelp">
@php
    $roleLabels=['owner'=>'Eier','admin'=>'Administrator','manager'=>'Avdelingsleder','customer_service'=>'Kundebehandler','technician'=>'Verkstedmedarbeider','warehouse'=>'Lagermedarbeider','accounting'=>'Regnskap'];
    $role=auth()->user()->is_super_admin?'Leverandør':($roleLabels[auth()->user()->role]??ucfirst(auth()->user()->role));
@endphp
<section class="panel help-hero"><div class="help-hero-copy"><span class="help-hero-mark">?</span><div><p class="eyebrow">DEKKPILOT HJELPESENTER</p><h2>Hva kan vi hjelpe deg med?</h2><p>Praktiske forklaringer fra første kunde til ferdig jobb – skrevet for mennesker som skal få arbeidet gjort.</p></div></div><div class="help-user"><span class="help-user-label">DIN VISNING</span><div><span class="help-user-avatar">{{ mb_strtoupper(mb_substr(auth()->user()->name,0,1)) }}</span><span><strong>{{ auth()->user()->name }}</strong><small>{{ $role }} · {{ session('ui_mode')==='technician'?'Teknikermodus':'Full portal' }}</small></span></div><small>{{ auth()->user()->organization?->name }}</small></div></section>

<nav class="help-start" aria-label="Hopp til hjelp"><a href="#kom-i-gang"><span>01</span><b>Kom i gang</b><small>De viktigste stegene først.</small><i>→</i></a><a href="#daglig-drift"><span>02</span><b>Daglig drift</b><small>Booking, hjul og jobber.</small><i>→</i></a><a href="#integrasjoner"><span>03</span><b>Integrasjoner</b><small>Nøkler, tilkobling og test.</small><i>→</i></a><a href="#tekniker"><span>04</span><b>Teknikermodus</b><small>Dagens arbeid på mobil.</small><i>→</i></a></nav>

<section class="panel help-section" id="kom-i-gang"><div class="panel-head"><div><p class="eyebrow">FØRSTE GANG</p><h2>Kom i gang på fem steg</h2></div></div><ol class="help-steps"><li><strong>Kontroller virksomheten</strong><p>Eier eller administrator åpner Admin og setter tjenester, priser, åpningstider, ansatte, arbeidsbukker og lagerplasser.</p></li><li><strong>Sett opp kommunikasjon</strong><p>Under Admin → E-post og backup legger virksomheten inn avsender og svaradresse. Twilio settes opp separat dersom SMS skal brukes.</p></li><li><strong>Registrer første kunde</strong><p>Trykk «Ny kunde», fyll inn kontaktinformasjon og gå videre til kjøretøy. Registreringsnummer kan bare registreres én gang.</p></li><li><strong>Opprett booking</strong><p>Søk etter navn eller registreringsnummer, velg én eller flere tjenester og bruk forslagene til ledige tider.</p></li><li><strong>Registrer hjulsettet</strong><p>Mål alle fire dekk, registrer vask og tilstand, velg lagerplass og skriv ut etikett.</p></li></ol></section>

<section class="grid two help-section" id="daglig-drift"><article class="panel"><p class="eyebrow">KUNDER OG BOOKING</p><h2>Fra telefon til avtale</h2><ol class="help-steps"><li><strong>Finn kunden</strong><p>Søk på navn eller registreringsnummer. Starter du fra kundekortet, følger kunden og bilen automatisk med til bookingen.</p></li><li><strong>Velg arbeidet</strong><p>Velg alle tjenestene som skal utføres. Tidsbehovet beregnes samlet.</p></li><li><strong>Finn tid</strong><p>Velg første ledige eller se de neste ledige tidene. Rød markering betyr overbooket kapasitet, men tiden kan fortsatt velges.</p></li><li><strong>Følg bekreftelsen</strong><p>Bekreftet og ventende vises tydelig. Ubekreftede timer følges opp automatisk.</p></li></ol></article><article class="panel"><p class="eyebrow">HJULHOTELL</p><h2>Fra mottak til utlevering</h2><ol class="help-steps"><li><strong>Mottak</strong><p>Finn kunde/bil, registrer settet og bruk bilfiguren til fire enkle mønsterdybdemålinger.</p></li><li><strong>Kontroll</strong><p>Marker skade, vaskebehov og bilder. Manglende opplysninger vises under «Krever handling».</p></li><li><strong>Lagring</strong><p>Velg reol og hylle fra lagerkartet. Etiketten representerer hele hjulsettet.</p></li><li><strong>Klargjøring</strong><p>«Min arbeidsdag» viser hvilke sett som skal finnes frem til morgendagens avtaler.</p></li><li><strong>Utlevering</strong><p>Skann settet, oppdater status og fullfør jobben. Feil fullføring kan åpnes igjen.</p></li></ol></article></section>

<section class="grid two help-section"><article class="panel"><p class="eyebrow">TILBUD OG MERSALG</p><h2>Når dekk bør skiftes</h2><p class="muted">Lav mønsterdybde oppretter en salgsmulighet. Systemet matcher dimensjon og sesong mot lageret.</p><ol class="help-steps"><li><strong>Åpne forslaget</strong><p>Kontroller bilen, målingen og tilgjengelige produkter.</p></li><li><strong>Velg alternativer</strong><p>Presenter opptil tre gode valg: «Godt valg», «Bra valg» og «Det beste».</p></li><li><strong>Forhåndsvis</strong><p>Se nøyaktig hvordan e-posten blir før den sendes.</p></li><li><strong>Kundens svar</strong><p>Kunden åpner sikker lenke, velger alternativ og godtar kjøpsvilkår.</p></li></ol></article><article class="panel"><p class="eyebrow">FULLFØRING OG REGNSKAP</p><h2>Avslutt jobben riktig</h2><ol class="help-steps"><li><strong>Kontroller oppgavene</strong><p>Fyll ut nødvendige kontrollpunkter og avvik før fullføring.</p></li><li><strong>Marker ferdig</strong><p>Jobb og booking fullføres. Trykk igjen for å åpne den dersom noe var feil.</p></li><li><strong>Fakturagrunnlag</strong><p>Grunnlaget opprettes automatisk og sendes direkte eller legges i manuell kø.</p></li><li><strong>Følg feil</strong><p>Admin → Regnskap viser om eksport til Fiken eller Tripletex er sendt eller feilet.</p></li></ol></article></section>

<section class="panel help-section" id="integrasjoner"><div class="panel-head"><div><p class="eyebrow">EKSTERNE TJENESTER</p><h2>Koble DekkPilot trygt til andre systemer</h2><p>Åpne Administrasjon for virksomhetens tilkoblinger. Plattformnøkler, servertransport, cron og Git håndteres bare av leverandør.</p></div></div><div class="help-integration-grid">
<article><span class="help-provider">SVV</span><div><h3>Statens vegvesen</h3><p>Bruk API-et for <em>tekniske kjøretøyopplysninger</em>. Det gir oppslag på registreringsnummer uten at eierdata hentes.</p><ol><li>Åpne Vegvesenets side for API-er og velg tekniske kjøretøyopplysninger.</li><li>Registrer virksomheten/abonnementet i Dataporten og opprett API-nøkkel.</li><li>I DekkPilot: Administrasjon → Statens vegvesen → lim inn nøkkelen → lagre.</li><li>Test med et registreringsnummer i kunde- eller kjøretøyskjemaet.</li></ol><a href="https://www.vegvesen.no/kjoretoy/kjop-og-salg/kjoretoyopplysninger/api-er-for-tekniske-kjoretoyopplysninger/" target="_blank" rel="noopener">Offisiell veiledning hos Statens vegvesen ↗</a></div></article>
<article><span class="help-provider">1881</span><div><h3>1881 Opplysningen</h3><p>1881-oppslag kan fylle navn og adresse fra telefonnummer. Dette er en valgfri plattformfunksjon som leverandør slår av eller på.</p><ol><li>Bestill API-tilgang direkte fra 1881/API1881.</li><li>Leverandør legger inn endepunktet med <code>{phone}</code> og API-nøkkelen.</li><li>Når funksjonen er aktiv, vises «Hent navn og adresse fra 1881» ved ny kunde.</li><li>Kontroller alltid treffet før kunden lagres.</li></ol><p class="help-note">Tilgang og bruk må følge avtalen med 1881. Ikke bruk oppslag til markedsføring uten gyldig behandlingsgrunnlag.</p></div></article>
<article><span class="help-provider">SMS</span><div><h3>SMS med Twilio</h3><p>Hver virksomhet bruker og betaler sin egen Twilio-konto. SMS faktureres av Twilio etter bruk.</p><ol><li>Opprett konto, aktiver fakturering og skaff et SMS-nummer eller en Messaging Service.</li><li>I Twilio Console: Account management → API keys &amp; tokens → opprett en begrenset eller Standard API key.</li><li>I DekkPilot: Administrasjon → Kommunikasjon → fyll inn Account SID, API Key SID, Secret og avsender.</li><li>Lagre og send én test-SMS til ditt eget nummer.</li></ol><a href="https://www.twilio.com/docs/iam/api-keys/keys-in-console" target="_blank" rel="noopener">Slik oppretter Twilio API-nøkler ↗</a></div></article>
<article><span class="help-provider">E-post</span><div><h3>E-post og avsender</h3><p>Virksomheten velger bare synlig avsenderadresse og svaradresse. SMTP, lokal <code>mail()</code>, Domeneshop-oppsett og systemavsender styres av leverandør.</p><ol><li>Leverandør velger servertransport og sender en systemtest.</li><li>Virksomheten åpner Administrasjon → Kommunikasjon og legger inn egen avsender.</li><li>Send en test og kontroller meldingskøen.</li><li>Demo- og testmiljø sender aldri ekte e-post.</li></ol></div></article>
</div></section>

<section class="panel help-section" id="regnskap-oppsett"><div class="panel-head"><div><p class="eyebrow">REGNSKAP</p><h2>Velg én aktiv regnskapskobling</h2><p>Gå til Administrasjon → Regnskap og fakturakø. Test tilkoblingen før automatisk eksport aktiveres.</p></div></div><div class="help-provider-list">
<details open><summary><strong>Fiken</strong><span>OAuth – kunden logger inn og godkjenner</span></summary><div><ol><li>Leverandør registrerer DekkPilot som Fiken-app og lagrer Client ID og Client Secret.</li><li>Redirect URL-en som vises i DekkPilot må registreres helt identisk hos Fiken.</li><li>Virksomheten trykker «Logg inn hos Fiken», velger firma og godkjenner tilgangen.</li><li>Velg betalingsfrist, inntektskonto og manuell eller automatisk eksport. Send deretter test.</li></ol><p>Fiken krever OAuth for tredjepartssystemer. App opprettes under Brukerinnstillinger → API etter at utviklermodus er aktivert.</p><a href="https://api.fiken.no/api/v2/docs/" target="_blank" rel="noopener">Fiken API v2 og OAuth ↗</a></div></details>
<details><summary><strong>Tripletex</strong><span>Virksomheten limer inn sin token</span></summary><div><ol><li>Leverandør må først ha DekkPilots Consumer Token for produksjon.</li><li>Virksomheten oppretter/aktiverer integrasjonen i Tripletex og kopierer tokenen som vises.</li><li>Lim tokenen inn under Tripletex i DekkPilot, velg inntektskonto og betalingsfrist.</li><li>Lagre, test og aktiver eksport.</li></ol><p>Test- og produksjonstokener kan ikke blandes. Tokenens rettigheter kan ikke være større enn brukerens rettigheter.</p><a href="https://developer.tripletex.no/docs/documentation/authentication-and-tokens/" target="_blank" rel="noopener">Tripletex: autentisering og tokens ↗</a></div></details>
<details><summary><strong>PowerOffice Go</strong><span>Client Key per virksomhet</span></summary><div><ol><li>Leverandør registrerer applikasjonen og legger inn Application Key og Subscription Key.</li><li>Virksomheten aktiverer integrasjonen i PowerOffice Go og kopierer Client Key; den vises normalt bare ved opprettelse.</li><li>Lim Client Key inn i DekkPilot og velg riktig miljø.</li><li>Test koblingen. Fakturaeksport krever at nødvendige API-produkter/rettigheter, blant annet salgsordre, er godkjent.</li></ol><p>Demo og produksjon bruker separate nøkler og adresser.</p><a href="https://developer.poweroffice.net/documentation/credentials" target="_blank" rel="noopener">PowerOffice: nøkler og klienttilgang ↗</a></div></details>
<details><summary><strong>Uni Micro</strong><span>Company Key og tilgangstoken</span></summary><div><ol><li>Opprett/aktiver integrasjonen hos Uni Micro og velg firma.</li><li>Kopier tilgangstoken og Company Key for firmaet.</li><li>Lim begge inn under Uni Micro i DekkPilot.</li><li>Test tilkoblingen før automatisk eksport slås på.</li></ol><p>Company Key bestemmer hvilket firma API-kallene gjelder. Test- og produksjonsmiljø må holdes adskilt.</p><a href="https://developer.unimicro.no/guide/authentication/auth-code" target="_blank" rel="noopener">Uni Micro: innlogging og Company Key ↗</a></div></details>
</div></section>

<section class="grid two help-section"><article class="panel"><p class="eyebrow">BETALING</p><h2>Vipps, Zettle og bankterminal</h2><ul class="help-plain"><li><strong>Vipps:</strong> Logg inn i bedriftsportalen → For developers → velg Test eller Production → Show keys. Kopier MSN, Client ID, Client Secret og Subscription Key til betalingsoppsettet.</li><li><strong>Zettle:</strong> Tilgjengeligheten kan variere. Kontakt leverandøren dersom valget ikke vises.</li><li><strong>Bankterminal:</strong> Manuell kassaflyt kan brukes. Automatisk terminalstatus krever valgt og sertifisert terminalpartner.</li><li><strong>Kontant/faktura:</strong> Registreres av ansatte. Ubetalt arbeid kan sendes videre som faktura ved dagsavslutning.</li></ul><a href="https://developer.vippsmobilepay.com/docs/knowledge-base/api-keys/" target="_blank" rel="noopener">Vipps MobilePay: finn API-nøkler ↗</a></article><article class="panel"><p class="eyebrow">TEKNISK DRIFT</p><h2>Trygg bruk av integrasjoner</h2><ul class="help-plain"><li>Legg API-nøkler bare inn i feltene som er beregnet for dem.</li><li>Ikke del passord, nøkler eller kundelenker i e-post, chat eller skjermbilder.</li><li>Bruk testknappen etter at en integrasjon er konfigurert.</li><li>Les feilmeldingen i den aktuelle køen før du forsøker på nytt.</li><li>Kontakt leverandøren dersom problemet gjelder plattformens tekniske oppsett.</li></ul></article></section>

<section class="panel help-section" id="tekniker"><div class="panel-head"><div><p class="eyebrow">MOBIL OG NETTBRETT</p><h2>Teknikermodus</h2></div></div><p class="muted">Teknikermodus viser bare det verkstedmedarbeideren trenger akkurat nå. På mobil bruker du menyen nederst.</p><div class="help-role"><span>I dag – dagens bookinger</span><span>Kart – finn lagerplass</span><span>Hjul – søk og skann</span><span>Avvik – manglende kontroll</span><span>Bytt – gå til full portal</span></div><ol class="help-steps"><li><strong>Åpne dagens jobb</strong><p>Se kunde, bil, tjenester og hvor hjulene ligger.</p></li><li><strong>Skann én gang</strong><p>Én QR-kode identifiserer hele settet; du trenger ikke skanne fire dekk.</p></li><li><strong>Mål og dokumenter</strong><p>Bruk store felter og kamera til mønsterdybde, tilstand, vask og bilde.</p></li><li><strong>Flytt status</strong><p>Oppdater settet videre i flyten slik at resten av teamet alltid ser riktig status.</p></li></ol></section>

<section class="grid two help-section"><article class="panel"><p class="eyebrow">HVEM KAN GJØRE HVA?</p><h2>Roller i virksomheten</h2><div class="help-role"><span>Eier: alt i egen virksomhet</span><span>Admin: oppsett og drift</span><span>Avdelingsleder: kapasitet og jobber</span><span>Kundebehandler: kunder og booking</span><span>Tekniker: dagens arbeid</span><span>Lager: hjul og plassering</span><span>Regnskap: fakturakø</span></div><p class="muted">Ser du ikke en funksjon, skyldes det vanligvis rollen din eller at du er i teknikermodus. Velg «Bytt visning» for full portal.</p></article><article class="panel"><p class="eyebrow">TRYGG BRUK</p><h2>Viktig å huske</h2><ul class="check"><li>Del aldri passord, API-nøkler eller kundelenker.</li><li>Bruk tofaktor når du har administrativ tilgang.</li><li>Kontroller mottaker og forhåndsvisning før masseutsending.</li><li>Ikke bruk ekte persondata i demo.</li><li>Logg ut på delte enheter.</li><li>Kontakt administrator dersom data ser ut til å tilhøre feil virksomhet.</li></ul></article></section>

<section class="panel help-faq help-section" id="ofte-spurt"><p class="eyebrow">RASKE SVAR</p><h2>Ofte stilte spørsmål</h2><details open><summary>Hvorfor får jeg ikke sendt e-post?</summary><p>Administrator må sette virksomhetens avsender og sende en test. Leverandør må ha konfigurert servertransporten. Se også meldingskøen for konkret feilmelding. Demo sender aldri.</p></details><details><summary>Hvorfor virker ikke kjøretøyoppslaget?</summary><p>Kontroller at Statens vegvesen-integrasjonen er aktiv og at nøkkelen er lagret i riktig miljø. Test et norsk registreringsnummer uten mellomrom. Ved 401/403 må nøkkelen eller abonnementet kontrolleres; ved 429 må oppslagene vente og prøves igjen senere.</p></details><details><summary>Hvorfor sendes ikke fakturaen?</summary><p>Åpne Administrasjon → Regnskap og fakturakø. Kontroller aktiv leverandør, test tilkoblingen og les feilen på den konkrete køposten. Ikke trykk mange ganger; legg posten tilbake i kø én gang etter at årsaken er rettet.</p></details><details><summary>Hva betyr 429?</summary><p>Leverandøren eller serveren har mottatt for mange forespørsler på kort tid. Vent før nytt forsøk. Fiken tillater blant annet bare ett samtidig API-kall, så køen skal behandle eksportene sekvensielt.</p></details><details><summary>Hvorfor ser jeg ingen ledige timer?</summary><p>Kontroller åpningstid, aktive tjenester, varighet, ansatte og eventuelle arbeidsbukker under Admin. Prøv deretter en annen dato.</p></details><details><summary>Hvorfor er en booking rød?</summary><p>Det er flere samtidige bookinger enn registrert kapasitet. Bookingen tillates, men bør vurderes av driftsleder.</p></details><details><summary>Kan en bil flyttes til en ny eier?</summary><p>Ja. Åpne kunden og bilen, velg flytting og søk etter den nye kunden. Historikken følger bilen.</p></details><details><summary>Hvor finner jeg hjulene til i morgen?</summary><p>Åpne «Min arbeidsdag» og se «Finn frem til i morgen». Lagerplass vises på hver rad.</p></details><details><summary>Jeg fullførte feil jobb – hva gjør jeg?</summary><p>Åpne jobben/bookingen og velg å åpne den igjen. Status går tilbake til ventende arbeid.</p></details><details><summary>Hvordan bytter jeg mellom mobil- og fullvisning?</summary><p>Bruk «Visning» ved brukeropplysningene, eller «Bytt» i bunnmenyen i teknikermodus.</p></details></section>

<section class="panel help-callout"><div><p class="eyebrow">FORTSATT FAST?</p><h2>Ta med det som gjør feilsøkingen enkel</h2><p>Noter hvilken side du var på, tidspunktet, hva du trykket på og den nøyaktige feilmeldingen. Ikke send passord eller API-nøkler.</p></div><a class="button" href="mailto:hei@dekkpilot.no?subject=Hjelp%20med%20DekkPilot">Kontakt support</a></section>
</x-layouts.app>
