<!doctype html>
<html lang="nb"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Min kundeportal · DekkPilot</title><link rel="stylesheet" href="{{ asset('app.css') }}"><link rel="stylesheet" href="{{ asset('portal.css') }}?v=20260810-2"></head>
<body class="portal-page {{ $adminPreview ? 'portal-preview' : '' }}">
<header class="portal-header"><span class="brandmark">D</span><div><strong>{{ $customer->organization?->name ?? 'DekkPilot' }}</strong><small>Sikker kundeportal</small></div></header>
<main class="portal-main">
@if($adminPreview)<div class="portal-preview-banner"><div><strong>Forhåndsvisning som {{ $customer->name }}</strong><span>Denne visningen er skrivebeskyttet. Ingen bestillinger, tilbud eller timer kan endres.</span></div><a href="{{ route('admin.portals') }}">← Tilbake til portaler</a></div>@endif
@if(session('success'))<div class="flash">✓ {{ session('success') }}</div>@endif
@if($errors->any())<div class="flash error">{{ $errors->first() }}</div>@endif
<div class="portal-welcome"><p class="eyebrow">MIN SIDE</p><h1>Hei, {{ explode(' ', $customer->name)[0] }}</h1><p>Her har du biler, hjul, timer, tilbud og utført arbeid samlet på ett sted.</p></div>

<nav class="portal-jump" aria-label="Innhold"><a href="#bestill">Bestill time</a><a href="#biler">Biler og hjul</a><a href="#timer">Timer</a><a href="#tilbud">Tilbud</a><a href="#historikk">Historikk</a></nav>

<section id="bestill" class="panel portal-section"><div class="portal-section-head"><div><p class="eyebrow">SELVBETJENING</p><h2>Bestill ny time</h2></div><span>Viser bare ledig kapasitet</span></div>
@if($customer->vehicles->isEmpty() || $services->isEmpty())<p class="empty">Verkstedet må registrere bil og aktive tjenester før du kan bestille.</p>@else
<form method="post" action="{{ route('portal.booking.create',$token) }}" id="portal-booking-form" data-availability-url="{{ route('portal.availability',$token) }}">@csrf
<div class="portal-booking-fields"><label>Bil<select name="vehicle_id" required>@foreach($customer->vehicles as $vehicle)<option value="{{ $vehicle->id }}">{{ $vehicle->registration_number }} · {{ trim($vehicle->make.' '.$vehicle->model) }}</option>@endforeach</select></label>
<fieldset><legend>Hva vil du bestille?</legend><div class="portal-service-options">@foreach($services as $service)<label><input type="checkbox" name="service_product_ids[]" value="{{ $service->id }}" @checked($loop->first)><span><b>{{ $service->name }}</b><small>{{ $service->duration_minutes }} min · {{ number_format($service->fixed_price_cents/100,0,',',' ') }} kr</small></span></label>@endforeach</div></fieldset></div>
<div class="portal-slot-head"><strong>Velg en ledig tid</strong><label>Fra dato <input type="date" id="portal-slot-date" min="{{ today()->toDateString() }}"></label></div>
<div class="portal-slots" id="portal-slots">@foreach($slots as $slot)<label><input type="radio" name="starts_at" value="{{ $slot['starts_at'] }}" @checked($loop->first)><span><b>{{ $slot['date'] }}</b>{{ $slot['time'] }}–{{ $slot['end_time'] }}</span></label>@endforeach</div>
<p class="empty" id="portal-slot-empty" @if($slots->isNotEmpty()) hidden @endif>Ingen ledige tider med disse valgene. Prøv en senere dato.</p><button class="button" id="portal-booking-submit" @disabled($slots->isEmpty())>Bestill og bekreft timen</button>
</form>@endif</section>

<section id="biler"><div class="portal-section-head"><div><p class="eyebrow">BILER OG HJUL</p><h2>Dine kjøretøy</h2></div><span>{{ $customer->vehicles->count() }} registrert</span></div><div class="portal-grid">
@forelse($customer->vehicles as $vehicle)<article class="panel"><div class="panel-head"><div><p class="eyebrow">KJØRETØY</p><h2>{{ $vehicle->registration_number }}</h2></div><span class="tag">{{ trim($vehicle->make.' '.$vehicle->model) }}</span></div>
@forelse($vehicle->tireSets as $set)@php($last=$set->inspections->sortByDesc('inspected_at')->first())<div class="portal-tires"><strong>{{ ['winter'=>'Vinterhjul','summer'=>'Sommerhjul','all_season'=>'Helårsdekk'][$set->season] ?? 'Hjulsett' }} · {{ $set->size ?: 'Dimensjon mangler' }}</strong><span class="status {{ $last?->overall_status==='replace'?'cancelled':($last?->overall_status==='attention'?'in_progress':'completed') }}">{{ $last ? (['good'=>'God tilstand','attention'=>'Bør følges opp','replace'=>'Bør skiftes'][$last->overall_status] ?? 'Kontrollert') : 'Ikke kontrollert' }}</span>@if($last)<div class="depth-row">@foreach($last->measurements as $wheel)<span>{{ ['front_left'=>'FV','front_right'=>'FH','rear_left'=>'BV','rear_right'=>'BH'][$wheel->position] ?? $wheel->position }} <b>{{ $wheel->tread_depth_mm ?? '—' }} mm</b></span>@endforeach</div>@endif</div>@empty<p class="empty">Ingen hjulsett registrert.</p>@endforelse
</article>@empty<article class="panel empty">Ingen kjøretøy er registrert.</article>@endforelse
</div></section>

<section id="timer" class="panel portal-section"><div class="portal-section-head"><div><p class="eyebrow">KOMMENDE</p><h2>Dine timer</h2></div><span>{{ $customer->bookings->count() }} avtaler</span></div>
@forelse($customer->bookings as $booking)<div class="portal-booking"><div><strong>{{ $booking->starts_at->translatedFormat('l d. F · H:i') }}</strong><span>{{ $booking->service_name }}{{ $booking->vehicle ? ' · '.$booking->vehicle->registration_number : '' }}</span></div><span class="portal-state {{ $booking->confirmation_status==='confirmed'?'confirmed':'waiting' }}">{{ $booking->confirmation_status==='confirmed'?'Bekreftet':'Venter på bekreftelse' }}</span><div class="portal-booking-actions"><details><summary>Endre time</summary><div class="portal-action-menu"><form method="post" action="{{ route('portal.booking',[$token,$booking]) }}">@csrf<input type="hidden" name="action" value="reschedule"><label>Ønsket tidspunkt<input type="datetime-local" name="requested_at" required></label><button class="button">Send ønske</button></form><form method="post" action="{{ route('portal.booking',[$token,$booking]) }}">@csrf<input type="hidden" name="action" value="cancel"><button class="button ghost">Avbestill timen</button></form></div></details></div></div>
@empty<p class="empty">Du har ingen kommende avtaler.</p>@endforelse</section>

<section id="tilbud" class="panel portal-section"><div class="portal-section-head"><div><p class="eyebrow">TILBUD</p><h2>Dine tilbud</h2></div><span>{{ $customer->quotes->count() }} totalt</span></div>
@forelse($customer->quotes as $quote)<article class="portal-quote"><div class="portal-quote-head"><div><strong>{{ $quote->reference }}</strong><span>{{ $quote->vehicle?->registration_number }} · {{ $quote->created_at->format('d.m.Y') }}</span></div><span class="status {{ $quote->status==='accepted'?'completed':($quote->status==='declined'||$quote->status==='expired'?'cancelled':'in_progress') }}">{{ ['draft'=>'Utkast','sent'=>'Nytt','viewed'=>'Åpnet','accepted'=>'Godkjent','declined'=>'Avslått','expired'=>'Utløpt'][$quote->status] ?? $quote->status }}</span></div>
@if(in_array($quote->status,['sent','viewed'],true) && $quote->expires_at->isFuture())<form method="post" action="{{ route('portal.quote',[$token,$quote]) }}">@csrf<div class="portal-options">@foreach($quote->items->sortBy('position') as $option)<label><input type="radio" name="quote_item_id" value="{{ $option->id }}" @checked($loop->first)><span><b>{{ $option->recommendation_label ?: 'Godt valg' }}</b><strong>{{ $option->description }}</strong><small>{{ $option->quantity }} stk.</small></span><strong>{{ number_format($option->line_total_cents/100,0,',',' ') }} kr</strong></label>@endforeach</div><label class="portal-terms"><input type="checkbox" name="terms_accepted" value="1"><span>Jeg godtar <a href="{{ route('legal.terms') }}" target="_blank" rel="noopener">kjøpsvilkårene</a>.</span></label><div class="quote-actions"><button class="button ghost" name="decision" value="declined" formnovalidate>Nei takk</button><button class="button" name="decision" value="accepted">Godta valgt tilbud</button></div></form>
@else<div class="portal-quote-summary"><span>{{ $quote->items->firstWhere('id',$quote->selected_quote_item_id)?->description ?? $quote->items->first()?->description ?? 'Dekketøy' }}</span><strong>{{ number_format($quote->total_cents/100,0,',',' ') }} kr</strong></div>@endif</article>
@empty<p class="empty">Ingen tilbud er registrert.</p>@endforelse</section>

<section id="historikk" class="panel portal-section"><div class="portal-section-head"><div><p class="eyebrow">HISTORIKK</p><h2>Utført arbeid</h2></div><span>{{ $customer->workOrders->count() }} jobber</span></div>
@forelse($customer->workOrders as $order)<div class="portal-history"><div><strong>{{ $order->reference }}</strong><span>{{ $order->vehicle?->registration_number }} · {{ ($order->completed_at ?? $order->created_at)->format('d.m.Y') }}</span></div><span class="status {{ $order->status==='completed'?'completed':'in_progress' }}">{{ ['draft'=>'Klargjøres','ready'=>'Klar','in_progress'=>'Pågår','quality_check'=>'Kvalitetskontroll','completed'=>'Fullført','cancelled'=>'Avbrutt'][$order->status] ?? $order->status }}</span><small>{{ $order->tasks->where('completed',true)->count() }} av {{ $order->tasks->count() }} oppgaver fullført</small></div>@empty<p class="empty">Ingen arbeidsordre er registrert ennå.</p>@endforelse</section>

<footer>{{ $adminPreview ? 'Administrativ, skrivebeskyttet forhåndsvisning.' : 'Den personlige lenken gir tilgang til kundeportalen. Ikke videresend den.' }}</footer></main>
@if($adminPreview)<style>.portal-preview-banner{position:sticky;top:12px;z-index:20;display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:18px;padding:14px 17px;border:1px solid #d7ab45;border-radius:13px;background:#fff4d6;box-shadow:0 8px 24px rgba(70,52,14,.12)}.portal-preview-banner div{display:grid;gap:2px}.portal-preview-banner span{color:#6c571d;font-size:13px}.portal-preview-banner a{white-space:nowrap;color:#5b4510;font-weight:800}.portal-preview form{opacity:.62}.portal-preview form button,.portal-preview form input,.portal-preview form select{cursor:not-allowed}@media(max-width:650px){.portal-preview-banner{position:static;display:grid}.portal-preview-banner a{white-space:normal}}</style><script>document.querySelectorAll('form').forEach(function(form){form.inert=true;form.setAttribute('aria-disabled','true')});</script>@else<script src="{{ asset('portal-booking.js') }}?v=20260810-1" defer></script>@endif</body></html>
