<!doctype html>
<html lang="nb"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Min kundeportal · DekkPilot</title><link rel="stylesheet" href="{{ asset('app.css') }}"><link rel="stylesheet" href="{{ asset('portal.css') }}?v=20260812-1">@if($adminPreview)<link rel="stylesheet" href="{{ asset('portal-preview.css') }}?v=20260812-1">@endif</head>
<body class="portal-page {{ $adminPreview ? 'portal-preview' : '' }}">
<header class="portal-header"><span class="brandmark">D</span><div><strong>{{ $customer->organization?->name ?? 'DekkPilot' }}</strong><small>Sikker kundeportal</small></div></header>
<main class="portal-main">
@if($adminPreview)<div class="portal-preview-banner"><div><strong>Forhåndsvisning som {{ $customer->name }}</strong><span>Denne visningen er skrivebeskyttet. Ingen bestillinger, tilbud eller timer kan endres.</span></div><a href="{{ route('admin.portals') }}">← Tilbake til portaler</a></div>@endif
@if(session('success'))<div class="flash">✓ {{ session('success') }}</div>@endif
@if($errors->any())<div class="flash error">{{ $errors->first() }}</div>@endif
<div class="portal-welcome"><div><p class="eyebrow">MIN SIDE</p><h1>Hei, {{ explode(' ', $customer->name)[0] }}</h1><p>Alt om bilene og hjulene dine – uten telefonkø og papirarbeid.</p></div><div class="portal-overview"><div><strong>{{ $customer->vehicles->count() }}</strong><span>{{ $customer->vehicles->count() === 1 ? 'bil' : 'biler' }}</span></div><div><strong>{{ $customer->bookings->count() }}</strong><span>kommende timer</span></div><div class="{{ $recommendations->isNotEmpty() ? 'needs-attention' : '' }}"><strong>{{ $recommendations->count() }}</strong><span>trenger oppfølging</span></div></div></div>

<nav class="portal-jump" aria-label="Innhold">@if($hotelCharges->isNotEmpty())<a href="#ubetalt" class="attention-link">Ubetalt <span>{{ $hotelCharges->count() }}</span></a>@endif @if($recommendations->isNotEmpty())<a href="#dekkvalg" class="attention-link">Dekkvalg <span>{{ $recommendations->count() }}</span></a>@endif<a href="#bestill">Bestill time</a><a href="#biler">Biler og hjul</a><a href="#timer">Timer</a><a href="#tilbud">Tilbud</a><a href="#historikk">Historikk</a></nav>

@if($hotelCharges->isNotEmpty())<section id="ubetalt" class="panel portal-section recommendation-section"><div class="recommendation-intro"><div class="recommendation-icon" aria-hidden="true">kr</div><div><p class="eyebrow">DEKKHOTELL</p><h2>Ubetalt halvårsperiode</h2><p>Du trenger ikke bestille time for å gjøre opp dekkhotellet. Betal sikkert her, eller kontakt verkstedet dersom du ønsker faktura.</p></div></div>@foreach($hotelCharges as $charge)<article class="portal-quote"><div class="portal-quote-head"><div><strong>{{ $charge->vehicle?->registration_number??'Dekkhotell' }}</strong><span>{{ $charge->period_starts_on->format('d.m.Y') }}–{{ $charge->period_ends_on->format('d.m.Y') }} · forfalt {{ $charge->due_on->format('d.m.Y') }}</span></div><strong>{{ number_format($charge->amount_cents/100,2,',',' ') }} kr</strong></div>@unless($adminPreview)<form method="post" action="{{ route('portal.hotel-charge.pay',[$token,$charge]) }}">@csrf<button class="button">Betal nå</button></form>@endunless</article>@endforeach</section>@endif

@if($recommendations->isNotEmpty())
<section id="dekkvalg" class="panel portal-section recommendation-section"><div class="recommendation-intro"><div class="recommendation-icon" aria-hidden="true">↗</div><div><p class="eyebrow">ANBEFALT Å GJØRE NÅ</p><h2>Dekk som passer bilen din</h2><p>Vi viser dekk som bør vurderes på grunn av mønsterdybde eller alder. Vi prioriterer samme merke når det finnes på lager.</p></div></div>
@foreach($recommendations as $recommendation)@php($set=$recommendation['set'])<article class="vehicle-recommendation"><div class="recommendation-vehicle"><div><span class="registration">{{ $set->vehicle->registration_number }}</span><strong>{{ ['winter'=>'Vinterdekk','summer'=>'Sommerdekk','all_season'=>'Helårsdekk'][$set->season] ?? 'Dekk' }} · {{ $set->size }}</strong></div><div class="tread-warning"><span>Målt mønsterdybde</span><strong>{{ number_format((float)$set->minimum_tread_depth,1,',',' ') }} mm</strong></div></div>
@if($recommendation['quote'])<div class="existing-offer"><div><strong>Du har allerede et tilbud på disse dekkene</strong><span>Se alternativene, prisene og svar på tilbudet nedenfor.</span></div><a class="button" href="#tilbud">Se tilbudet</a></div>
@else<form method="post" action="{{ route('portal.tires.order',[$token,$set]) }}">@csrf<div class="replacement-explanation"><strong>{{ $recommendation['quantity'] }} dekk anbefales byttet</strong><span>{{ $recommendation['quantity'] === 2 ? 'Dekk skiftes parvis på samme aksel for trygg og jevn kjørefølelse.' : 'Målingene tilsier at hele settet bør skiftes.' }}@if($set->manufacturer) Nåværende merke: {{ $set->manufacturer }}{{ $set->model ? ' '.$set->model : '' }}.@endif</span></div><div class="tire-choice-grid">@foreach($recommendation['products'] as $product)@php($sameBrand=$set->manufacturer && mb_strtolower(trim($product->brand))===mb_strtolower(trim($set->manufacturer)))<label class="tire-choice"><input type="radio" name="tire_product_id" value="{{ $product->id }}" @checked($loop->first)><span class="choice-content"><span class="choice-label">{{ ['Det beste','Bra valg','Godt valg'][$loop->index] ?? 'Godt valg' }}</span>@if($sameBrand)<span class="same-brand">Samme merke som i dag</span>@endif<strong>{{ $product->brand }} {{ $product->model }}</strong><small>{{ $product->size }} · {{ $product->studded ? 'Piggdekk' : (['winter'=>'Vinter','summer'=>'Sommer','all_season'=>'Helårs'][$product->season] ?? '') }}</small><span class="stock-ok">✓ {{ $recommendation['quantity'] }} tilgjengelig</span><b>{{ number_format(($product->price_cents*$recommendation['quantity'])/100,0,',',' ') }} kr <small>for {{ $recommendation['quantity'] }} stk.</small></b></span></label>@endforeach</div><div class="recommendation-order"><label class="portal-terms"><input type="checkbox" name="terms_accepted" value="1" required><span>Jeg godtar <a href="{{ route('legal.terms') }}" target="_blank" rel="noopener">kjøpsvilkårene</a>.</span></label><button class="button">Reserver valgte dekk</button></div><p class="order-help">Ingen betaling nå. Etter reservasjonen velger du monteringstid i neste steg.</p></form>@endif</article>@endforeach
</section>
@endif

<section id="bestill" class="panel portal-section"><div class="portal-section-head"><div><p class="eyebrow">SELVBETJENING</p><h2>Bestill ny time</h2></div><span>Viser bare ledig kapasitet</span></div>
@if($customer->vehicles->isEmpty() || $services->isEmpty())<p class="empty">Verkstedet må registrere bil og aktive tjenester før du kan bestille.</p>@else
<form method="post" action="{{ route('portal.booking.create',$token) }}" id="portal-booking-form" data-availability-url="{{ route('portal.availability',$token) }}">@csrf
<div class="portal-booking-fields"><label>Bil<select name="vehicle_id" required>@foreach($customer->vehicles as $vehicle)<option value="{{ $vehicle->id }}" @selected($preferredVehicleId === $vehicle->id)>{{ $vehicle->registration_number }} · {{ trim($vehicle->make.' '.$vehicle->model) }}</option>@endforeach</select></label>
<fieldset><legend>Hva vil du bestille?</legend><div class="portal-service-options">@foreach($services as $service)<label><input type="checkbox" name="service_product_ids[]" value="{{ $service->id }}" @checked($preferredVehicleId ? $service->id === $preferredServiceId : $loop->first)><span><b>{{ $service->name }}</b><small>{{ $service->duration_minutes }} min · {{ number_format($service->fixed_price_cents/100,0,',',' ') }} kr</small></span></label>@endforeach</div></fieldset></div>
<div class="portal-slot-head"><strong>Velg en ledig tid</strong><label>Fra dato <input type="date" id="portal-slot-date" min="{{ today()->toDateString() }}"></label></div>
<div class="portal-slots" id="portal-slots">@foreach($slots as $slot)<label><input type="radio" name="starts_at" value="{{ $slot['starts_at'] }}" @checked($loop->first)><span><b>{{ $slot['date'] }}</b>{{ $slot['time'] }}–{{ $slot['end_time'] }}</span></label>@endforeach</div>
<p class="empty" id="portal-slot-empty" @if($slots->isNotEmpty()) hidden @endif>Ingen ledige tider med disse valgene. Prøv en senere dato.</p><button class="button" id="portal-booking-submit" @disabled($slots->isEmpty())>Bestill og bekreft timen</button>
</form>@endif</section>

<section id="biler"><div class="portal-section-head"><div><p class="eyebrow">BILER OG HJUL</p><h2>Dine kjøretøy</h2></div><span>{{ $customer->vehicles->count() }} registrert</span></div><div class="portal-grid">
@forelse($customer->vehicles as $vehicle)<article class="panel"><div class="panel-head"><div><p class="eyebrow">KJØRETØY</p><h2>{{ $vehicle->registration_number }}</h2></div><span class="tag">{{ trim($vehicle->make.' '.$vehicle->model) }}</span></div>
@forelse($vehicle->tireSets as $set)@php($last=$set->inspections->sortByDesc('inspected_at')->first())@php($measured=$last||$set->minimum_tread_depth!==null)@php($measurementDue=!$last?->inspected_at||$last->inspected_at->lte(now()->subYear()))<div class="portal-tires"><strong>{{ ['winter'=>'Vinterhjul','summer'=>'Sommerhjul','all_season'=>'Helårsdekk'][$set->season] ?? 'Hjulsett' }} · {{ $set->size ?: 'Dimensjon mangler' }}</strong><span class="status {{ $measurementDue?'in_progress':($last?->overall_status==='replace'||(!$last&&$set->minimum_tread_depth!==null&&(float)$set->minimum_tread_depth<3)?'cancelled':($last?->overall_status==='attention'||(!$last&&$set->minimum_tread_depth!==null&&(float)$set->minimum_tread_depth<4)?'in_progress':'completed')) }}">{{ $measurementDue ? ($last?'Målingen bør oppdateres':'Aldri målt') : ($last ? (['good'=>'God tilstand','attention'=>'Bør følges opp','replace'=>'Bør skiftes'][$last->overall_status] ?? 'Kontrollert') : ($measured?'Målt · '.$set->minimum_tread_depth.' mm':'Ikke kontrollert')) }}</span>@if($last)<div class="depth-row">@foreach($last->measurements as $wheel)<span>{{ ['front_left'=>'FV','front_right'=>'FH','rear_left'=>'BV','rear_right'=>'BH'][$wheel->position] ?? $wheel->position }} <b>{{ $wheel->tread_depth_mm ?? '—' }} mm</b></span>@endforeach @if($measurementDue)<span>Sist målt <b>{{ $last->inspected_at->format('d.m.Y') }}</b> · tilstanden kan ha endret seg</span>@endif</div>@elseif($measured)<div class="depth-row"><span>Laveste målte verdi <b>{{ $set->minimum_tread_depth }} mm</b></span></div>@endif</div>@empty<p class="empty">Ingen hjulsett registrert.</p>@endforelse
</article>@empty<article class="panel empty">Ingen kjøretøy er registrert.</article>@endforelse
</div></section>

<section id="timer" class="panel portal-section"><div class="portal-section-head"><div><p class="eyebrow">KOMMENDE</p><h2>Dine timer</h2></div><span>{{ $customer->bookings->count() }} avtaler</span></div>
@forelse($customer->bookings as $booking)<div class="portal-booking"><div><strong>{{ $booking->starts_at->translatedFormat('l d. F · H:i') }}</strong><span>{{ $booking->service_name }}{{ $booking->vehicle ? ' · '.$booking->vehicle->registration_number : '' }}</span></div><span class="portal-state {{ $booking->confirmation_status==='confirmed'?'confirmed':'waiting' }}">{{ $booking->confirmation_status==='confirmed'?'Bekreftet':'Venter på bekreftelse' }}</span><div class="portal-booking-actions"><details><summary>Endre time</summary><div class="portal-action-menu"><form method="post" action="{{ route('portal.booking',[$token,$booking]) }}">@csrf<input type="hidden" name="action" value="reschedule"><label>Ønsket tidspunkt<input type="datetime-local" name="requested_at" required></label><button class="button">Send ønske</button></form><form method="post" action="{{ route('portal.booking',[$token,$booking]) }}">@csrf<input type="hidden" name="action" value="cancel"><button class="button ghost">Avbestill timen</button></form></div></details></div></div>
@empty<p class="empty">Du har ingen kommende avtaler.</p>@endforelse</section>

<section id="tilbud" class="panel portal-section"><div class="portal-section-head"><div><p class="eyebrow">TILBUD</p><h2>Dine tilbud</h2></div><span>{{ $customer->quotes->count() }} totalt</span></div>
@forelse($customer->quotes as $quote)<article class="portal-quote"><div class="portal-quote-head"><div><strong>{{ $quote->reference }}</strong><span>{{ $quote->vehicle?->registration_number }} · {{ $quote->created_at->format('d.m.Y') }}</span></div><span class="status {{ $quote->status==='accepted'?'completed':($quote->status==='declined'||$quote->status==='expired'?'cancelled':'in_progress') }}">{{ ['draft'=>'Utkast','sent'=>'Nytt','viewed'=>'Åpnet','accepted'=>'Godkjent','declined'=>'Avslått','expired'=>'Utløpt'][$quote->status] ?? $quote->status }}</span></div>
@if(in_array($quote->status,['sent','viewed'],true) && $quote->expires_at->isFuture())<form method="post" action="{{ route('portal.quote',[$token,$quote]) }}">@csrf<div class="portal-options">@foreach($quote->items->sortBy('position') as $option)<label><input type="radio" name="quote_item_id" value="{{ $option->id }}" @checked($loop->first)><span><b>{{ $option->recommendation_label ?: 'Godt valg' }}</b><strong>{{ $option->description }}</strong><small>{{ $option->quantity }} stk.</small></span><strong>{{ number_format($option->line_total_cents/100,0,',',' ') }} kr</strong></label>@endforeach</div><label class="portal-terms"><input type="checkbox" name="terms_accepted" value="1"><span>Jeg godtar <a href="{{ route('legal.terms') }}" target="_blank" rel="noopener">kjøpsvilkårene</a>.</span></label><div class="quote-actions"><button class="button ghost" name="decision" value="declined" formnovalidate>Nei takk</button><button class="button" name="decision" value="accepted">Godta valgt tilbud</button></div></form>
@else<div class="portal-quote-summary"><span>{{ $quote->items->firstWhere('id',$quote->selected_quote_item_id)?->description ?? $quote->items->first()?->description ?? 'Dekketøy' }}</span><strong>{{ number_format($quote->total_cents/100,0,',',' ') }} kr</strong></div>@endif</article>
@empty<p class="empty">Ingen tilbud er registrert.</p>@endforelse</section>

<section id="historikk" class="panel portal-section"><div class="portal-section-head"><div><p class="eyebrow">HISTORIKK</p><h2>Utført arbeid</h2></div><span>{{ $customer->workOrders->count() }} jobber</span></div>
@forelse($customer->workOrders as $order)<div class="portal-history"><div><strong>{{ $order->reference }}</strong><span>{{ $order->vehicle?->registration_number }} · {{ ($order->completed_at ?? $order->created_at)->format('d.m.Y') }}</span></div><span class="status {{ $order->status==='completed'?'completed':'in_progress' }}">{{ ['draft'=>'Klargjøres','ready'=>'Klar','in_progress'=>'Pågår','quality_check'=>'Kvalitetskontroll','completed'=>'Fullført','cancelled'=>'Avbrutt'][$order->status] ?? $order->status }}</span><small>{{ $order->tasks->where('completed',true)->count() }} av {{ $order->tasks->count() }} oppgaver fullført</small></div>@empty<p class="empty">Ingen arbeidsordre er registrert ennå.</p>@endforelse</section>

<footer>{{ $adminPreview ? 'Administrativ, skrivebeskyttet forhåndsvisning.' : 'Den personlige lenken gir tilgang til kundeportalen. Ikke videresend den.' }}</footer></main>
@if($adminPreview)<script src="{{ asset('portal-preview.js') }}?v=20260812-1" defer></script>@else<script src="{{ asset('portal-booking.js') }}?v=20260812-1" defer></script>@endif</body></html>
