<!doctype html>
<html lang="nb"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#0d2b20"><title>Betaling · {{ $organization->name }}</title><link rel="stylesheet" href="{{ asset('checkout.css') }}?v=20260812-4">@if(in_array($payment->status,['pending','processing'],true))<meta name="checkout-status-url" content="{{ route('checkout.status',[$payment,$plain]) }}">@endif<script src="{{ asset('checkout.js') }}?v=20260812-2" defer></script></head>
<body><main class="checkout-shell payment-shell">
 <section class="checkout-brand-panel"><header class="checkout-brand"><span class="checkout-mark">D</span><span><strong>{{ $organization->name }}</strong><small>Drevet av DekkPilot</small></span></header><div class="checkout-brand-copy"><p class="checkout-kicker">TRYGG UTSJEKKING</p><h1>Snart klar<br><em>for veien.</em></h1><p>Velg hvordan du vil betale. Kort og PIN håndteres alltid sikkert av bankterminalen.</p></div><ol class="checkout-steps"><li class="done"><b>✓</b><span><strong>Bilen er funnet</strong><small>{{ $vehicle->registration_number }}</small></span></li><li class="active"><b>2</b><span><strong>Kontroller og betal</strong><small>Velg bankterminal eller Vipps</small></span></li><li><b>3</b><span><strong>Kvittering</strong><small>E-post, SMS eller utskrift</small></span></li></ol><footer><span class="shield-icon">✓</span><span><strong>Sikker betaling</strong><small>DekkPilot lagrer aldri kortnummer eller PIN.</small></span></footer></section>
 <section class="checkout-action-panel"><div class="checkout-action-card payment-card"><div class="checkout-mobile-brand"><span class="checkout-mark">D</span><span><strong>{{ $organization->name }}</strong><small>Sikker betaling</small></span></div><p class="checkout-kicker">{{ $payment->status==='paid'?'BETALING FULLFØRT':'TRINN 2 AV 3' }}</p><div class="payment-heading"><div><small>REGISTRERINGSNUMMER</small><h2>{{ $vehicle->registration_number }}</h2></div><span class="payment-status {{ $payment->status }}">{{ $payment->status==='paid'?'Betalt':($payment->status==='expired'?'Utløpt':($payment->status==='processing'?'Betaler':'Ikke startet')) }}</span></div><div class="payment-summary"><span><small>UTFØRT TJENESTE</small><strong>{{ $booking->service_name }}</strong></span><span><small>Å BETALE</small><strong>{{ number_format($invoice->total_cents/100,2,',',' ') }} kr</strong></span></div>
 @if($errors->any())<div class="payment-result error"><span>!</span><div><strong>Betalingen kunne ikke startes</strong><p>{{ $errors->first() }}</p></div></div>@endif
 @if($payment->status==='paid')
  <div class="payment-result success"><span>✓</span><div><strong>Betalingen er godkjent</strong><p>{{ $payment->receipt_channel==='email'?'Kvittering sendes på e-post.':($payment->receipt_channel==='sms'?'Kvittering sendes på SMS.':'Bilen kan nå utleveres.') }}</p></div></div>
  <a class="checkout-new" href="{{ route('checkout.receipt',[$payment,$plain]) }}" target="_blank" rel="noopener">Åpne og skriv ut kvittering</a><a class="checkout-new" href="{{ route('checkout.show',$organization) }}">Sjekk ut en annen bil</a>
 @elseif($payment->status==='expired')
  <div class="payment-result error"><span>!</span><div><strong>Betalingsfristen er utløpt</strong><p>Faktura er sendt via verkstedets regnskapssystem.</p></div></div><a class="checkout-new" href="{{ route('checkout.show',$organization) }}">Tilbake til utsjekking</a>
 @elseif($payment->status==='processing')
  <div class="terminal-card"><div class="terminal-top"><span class="terminal-icon">{{ $payment->payment_method==='vipps'?'V':'▣' }}</span><span><small>{{ $payment->payment_method==='vipps'?'VIPPS':'BANKTERMINAL' }}</small><strong>{{ $payment->terminal_reference }}</strong></span></div><p>{{ $payment->payment_method==='vipps'?'Godkjenn betalingen i Vipps. Siden oppdateres automatisk når beløpet er trukket.':'Beløpet er sendt til kassen. Sett inn, tæpp eller dra kortet og følg terminalens beskjed. Tast PIN kun på bankterminalen.' }}</p><div class="waiting"><span class="spinner" aria-hidden="true"></span><strong>{{ $payment->provider_status==='WAITING_FOR_CARD'?'Venter på kort / PIN …':'Venter på betalingsbekreftelse …' }}</strong></div></div>
  @auth<form class="terminal-confirm" method="post" action="{{ route('checkout.complete',$payment) }}">@csrf<label>Terminalens transaksjonsreferanse<input name="provider_reference" required maxlength="255" placeholder="Referanse fra godkjent betaling"></label><button class="checkout-new" type="submit">Bekreft godkjent terminalbetaling</button></form>@endauth
  <p class="payment-deadline">Betalingen må bekreftes innen <strong>{{ $payment->expires_at->format('d.m.Y H:i') }}</strong>. Deretter sendes faktura automatisk.</p>
 @else
  <form class="payment-choice-form" method="post" action="{{ route('checkout.start',[$payment,$plain]) }}">@csrf
   <fieldset><legend>Hvordan vil du betale?</legend><div class="payment-methods">
    @if($terminalEnabled)<label class="payment-method"><input type="radio" name="payment_method" value="terminal" required><span><b>▣</b><strong>{{ $terminalName }}</strong><small>Sett inn, tæpp eller dra kortet</small></span></label>@endif
    @if($vippsEnabled)<label class="payment-method vipps"><input type="radio" name="payment_method" value="vipps" required><span><b>V</b><strong>Vipps</strong><small>Godkjenn trygt i Vipps-appen</small></span></label>@endif
   </div>@if(!$terminalEnabled&&!$vippsEnabled)<p class="notice">Verkstedet har ikke aktivert en betalingsmåte ennå.</p>@endif</fieldset>
   @if($terminalEnabled||$vippsEnabled)<fieldset><legend>Hvordan vil du ha kvitteringen?</legend><div class="receipt-options"><label><input type="radio" name="receipt_channel" value="email" required><span>E-post</span></label><label><input type="radio" name="receipt_channel" value="sms"><span>SMS</span></label><label><input type="radio" name="receipt_channel" value="print"><span>Skriv ut</span></label><label><input type="radio" name="receipt_channel" value="none"><span>Ingen</span></label></div><label class="receipt-recipient">E-post eller mobilnummer<input name="receipt_recipient" value="{{ old('receipt_recipient',$booking->customer?->email ?: $booking->customer?->phone) }}" placeholder="Fylles ut ved e-post eller SMS"><small>SMS belastes etter verkstedets SMS-avtale.</small></label></fieldset><button class="checkout-pay" type="submit"><span>Fortsett til betaling</span><b>→</b></button>@endif
  </form>
 @endif
 </div></section>
</main></body></html>
