<!doctype html>
<html lang="nb"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#0d2b20"><title>Betaling · {{ $organization->name }}</title><link rel="stylesheet" href="{{ asset('checkout.css') }}?v=20260812-5"><link rel="stylesheet" href="{{ asset('checkout-staff.css') }}?v=20260812-1">@if(in_array($payment->status,['pending','processing'],true))<meta name="checkout-status-url" content="{{ route('checkout.status',[$payment,$plain]) }}">@endif<script src="{{ asset('checkout.js') }}?v=20260812-2" defer></script></head>
<body><main class="checkout-shell payment-shell">
<section class="checkout-brand-panel"><header class="checkout-brand"><span class="checkout-mark">D</span><span><strong>{{ $organization->name }}</strong><small>Drevet av DekkPilot</small></span></header><div class="checkout-brand-copy"><p class="checkout-kicker">TRYGG UTSJEKKING</p><h1>Jobben er ferdig.<br><em>Velg betaling.</em></h1><p>Betal i kassen eller la kunden fullføre på denne skjermen. Kortnummer og PIN lagres aldri i DekkPilot.</p></div><ol class="checkout-steps"><li class="done"><b>✓</b><span><strong>Jobben er fullført</strong><small>{{ $vehicle->registration_number }}</small></span></li><li class="active"><b>2</b><span><strong>Velg betaling</strong><small>Vipps, terminal, kontant eller faktura</small></span></li><li><b>3</b><span><strong>Kvittering</strong><small>E-post, SMS eller utskrift</small></span></li></ol><footer><span class="shield-icon">✓</span><span><strong>Sikker betaling</strong><small>Kort og PIN behandles av betalingstilbyderen.</small></span></footer></section>
<section class="checkout-action-panel"><div class="checkout-action-card payment-card"><div class="checkout-mobile-brand"><span class="checkout-mark">D</span><span><strong>{{ $organization->name }}</strong><small>Sikker betaling</small></span></div><p class="checkout-kicker">{{ $payment->status==='paid'?'BETALING FULLFØRT':'KASSE OG SELVBETJENING' }}</p>
<div class="payment-heading"><div><small>REGISTRERINGSNUMMER</small><h2>{{ $vehicle->registration_number }}</h2></div><span class="payment-status {{ $payment->status }}">{{ $payment->status==='paid'?'Betalt':($payment->provider_status==='INVOICED'?'Fakturert':($payment->status==='expired'?'Utløpt':($payment->status==='processing'?'Betaler':'Klar til betaling'))) }}</span></div>
<div class="payment-summary"><span><small>UTFØRT TJENESTE</small><strong>{{ $booking->service_name }}</strong></span><span><small>Å BETALE</small><strong>{{ number_format($invoice->total_cents/100,2,',',' ') }} kr</strong></span></div>
@if(session('success'))<div class="payment-result success"><span>✓</span><div><strong>{{ session('success') }}</strong></div></div>@endif
@if($errors->any())<div class="payment-result error"><span>!</span><div><strong>Dette kunne ikke gjennomføres</strong><p>{{ $errors->first() }}</p></div></div>@endif
@if($payment->status==='paid')
<div class="payment-result success"><span>✓</span><div><strong>Betalingen er godkjent</strong><p>{{ $payment->receipt_channel==='email'?'Kvittering sendes på e-post.':($payment->receipt_channel==='sms'?'Kvittering sendes på SMS.':'Kvitteringen er klar.') }}</p></div></div><a class="checkout-new" href="{{ route('checkout.receipt',[$payment,$plain]) }}" target="_blank" rel="noopener">Åpne og skriv ut kvittering</a>@auth<a class="checkout-new" href="{{ route('bookings') }}">Tilbake til timeboken</a>@else<a class="checkout-new" href="{{ route('checkout.show',$organization) }}">Sjekk ut en annen bil</a>@endauth
@elseif($payment->status==='expired')
<div class="payment-result {{ $payment->provider_status==='INVOICED'?'success':'error' }}"><span>{{ $payment->provider_status==='INVOICED'?'✓':'!' }}</span><div><strong>{{ $payment->provider_status==='INVOICED'?'Fakturaen er sendt':'Betalingsfristen er utløpt' }}</strong><p>Faktura er sendt via verkstedets regnskapssystem.</p></div></div><a class="checkout-new" href="{{ auth()->check()?route('bookings'):route('checkout.show',$organization) }}">Tilbake</a>
@elseif($payment->status==='processing')
<div class="terminal-card"><div class="terminal-top"><span class="terminal-icon">{{ $payment->payment_method==='vipps'?'V':'▣' }}</span><span><small>{{ $payment->payment_method==='vipps'?'VIPPS':'BANKTERMINAL' }}</small><strong>{{ $payment->terminal_reference }}</strong></span></div><p>{{ $payment->payment_method==='vipps'?'Godkjenn betalingen i Vipps. Siden oppdateres automatisk.':'Sett inn, tæpp eller dra kortet og følg terminalens beskjed. Tast PIN kun på bankterminalen.' }}</p><div class="waiting"><span class="spinner" aria-hidden="true"></span><strong>Venter på betalingsbekreftelse …</strong></div></div>
@auth<form class="terminal-confirm" method="post" action="{{ route('checkout.complete',$payment) }}">@csrf<label>Terminalens transaksjonsreferanse<input name="provider_reference" required maxlength="255" placeholder="Referanse fra godkjent betaling"></label><button class="checkout-new" type="submit">Bekreft godkjent terminalbetaling</button></form>@endauth
@else
<form class="payment-choice-form" method="post" action="{{ route('checkout.start',[$payment,$plain]) }}">@csrf<fieldset><legend>Hvordan skal kunden betale?</legend><div class="payment-methods">
@if($terminalEnabled)<label class="payment-method"><input type="radio" name="payment_method" value="terminal" required><span><b>▣</b><strong>Bankterminal</strong><small>Kort og PIN i kassen</small></span></label>@endif
@if($vippsEnabled)<label class="payment-method vipps"><input type="radio" name="payment_method" value="vipps" required><span><b>V</b><strong>Vipps</strong><small>Kunden godkjenner i appen</small></span></label>@endif
@auth<label class="payment-method"><input type="radio" name="payment_method" value="cash" required><span><b>kr</b><strong>Kontant</strong><small>Registrer mottatt betaling</small></span></label><label class="payment-method"><input type="radio" name="payment_method" value="invoice" required><span><b>↗</b><strong>Faktura</strong><small>Send til regnskapssystemet</small></span></label>@endauth
</div>@if(!$terminalEnabled&&!$vippsEnabled&&!auth()->check())<p class="notice">Verkstedet har ikke aktivert en betalingsmåte ennå.</p>@endif</fieldset>
@if($terminalEnabled||$vippsEnabled||auth()->check())<fieldset><legend>Kvittering for Vipps, terminal eller kontant</legend><div class="receipt-options"><label><input type="radio" name="receipt_channel" value="email"><span>E-post</span></label><label><input type="radio" name="receipt_channel" value="sms"><span>SMS</span></label><label><input type="radio" name="receipt_channel" value="print"><span>Skriv ut</span></label></div><label class="receipt-recipient">E-post eller mobilnummer<input name="receipt_recipient" value="{{ old('receipt_recipient',$booking->customer?->email ?: $booking->customer?->phone) }}" placeholder="Brukes ved e-post eller SMS"><small>Alle direktebetalinger får kvittering. Faktura sendes via regnskapssystemet.</small></label></fieldset><button class="checkout-pay" type="submit"><span>Fortsett</span><b>→</b></button>@endif</form>
@auth<div class="customer-payment-handoff"><strong>La kunden betale selv?</strong><p>Åpne denne siden på kundeskjermen eller la kunden bruke Vipps her. Betalingsstatus oppdateres automatisk.</p><button type="button" class="checkout-new" data-copy-payment-link>Kopier sikker betalingslenke</button></div>@endauth
@endif
</div></section></main><script src="{{ asset('checkout-staff.js') }}?v=20260812-1" defer></script></body></html>
