<?php
namespace App\Http\Controllers;
use App\Models\Booking;use App\Models\CheckoutPayment;use App\Models\InvoiceExport;use App\Models\Organization;use App\Models\Vehicle;use Illuminate\Http\JsonResponse;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;use Illuminate\View\View;
class CheckoutPortalController extends Controller{
 public function show(Organization $organization):View{return view('checkout.show',compact('organization'));}
 public function lookup(Request $request,Organization $organization):View|RedirectResponse{$data=$request->validate(['registration_number'=>['required','string','max:20']]);$reg=strtoupper(preg_replace('/[^A-Z0-9]/i','',$data['registration_number']));$vehicle=Vehicle::where('organization_id',$organization->id)->where('registration_number',$reg)->first();if(!$vehicle)return back()->withErrors(['registration_number'=>'Vi fant ingen ferdig jobb på dette registreringsnummeret.'])->withInput();$booking=Booking::where('organization_id',$organization->id)->where('vehicle_id',$vehicle->id)->where('status','completed')->latest('updated_at')->first();$invoice=$booking?InvoiceExport::where('booking_id',$booking->id)->first():null;if(!$booking||!$invoice||$invoice->status==='exported')return back()->withErrors(['registration_number'=>'Vi fant ingen ubetalt, ferdig jobb på dette registreringsnummeret.'])->withInput();$plain=Str::random(64);$payment=CheckoutPayment::firstOrCreate(['booking_id'=>$booking->id,'invoice_export_id'=>$invoice->id],['public_id'=>(string)Str::uuid(),'organization_id'=>$organization->id,'amount_cents'=>$invoice->total_cents,'terminal_reference'=>'DP-'.Str::upper(Str::random(18)),'lookup_token_hash'=>hash('sha256',$plain),'expires_at'=>now()->addHours(24)]);if(!$payment->wasRecentlyCreated){$plain=Str::random(64);$payment->update(['lookup_token_hash'=>hash('sha256',$plain)]);}return view('checkout.payment',compact('organization','vehicle','booking','invoice','payment','plain'));}
 public function status(CheckoutPayment $payment,string $token):JsonResponse{abort_unless(hash_equals($payment->lookup_token_hash,hash('sha256',$token)),404);return response()->json(['status'=>$payment->status,'paid_at'=>$payment->paid_at?->toIso8601String()]);}
 public function complete(Request $request,CheckoutPayment $payment):RedirectResponse{$data=$request->validate(['provider_reference'=>['required','string','max:255']]);abort_unless($payment->organization_id===$request->user()->organization_id,404);DB::transaction(function()use($payment,$data){$locked=CheckoutPayment::lockForUpdate()->findOrFail($payment->id);if($locked->status==='paid')return;$locked->update(['status'=>'paid','provider_reference'=>$data['provider_reference'],'paid_at'=>now(),'last_error'=>null]);$locked->invoiceExport()->update(['status'=>'cancelled','last_error'=>'Betalt med Zettle: '.$data['provider_reference']]);});return back()->with('success','Zettle-betalingen er bekreftet. Faktura sendes ikke.');}
}
