<?php
namespace App\Http\Controllers;
use App\Models\DataImport;use App\Services\TabularImportReader;use App\Services\TenantDataImporter;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Storage;use Illuminate\Support\Str;use Illuminate\View\View;use Symfony\Component\HttpFoundation\StreamedResponse;
class DataImportController extends Controller{
 public function index(Request$request):View{$org=$request->user()->organization_id;$pending=null;if($id=$request->query('import'))$pending=DataImport::where('organization_id',$org)->where('public_id',$id)->firstOrFail();return view('admin.imports',['pending'=>$pending,'fields'=>TenantDataImporter::FIELDS,'history'=>DataImport::where('organization_id',$org)->latest()->limit(20)->get()]);}
 public function upload(Request$request,TabularImportReader$reader,TenantDataImporter$importer):RedirectResponse{@set_time_limit(300);$data=$request->validate(['file'=>['required','file','mimes:csv,txt,xlsx','max:51200']]);$extension=strtolower($data['file']->getClientOriginalExtension());if(!in_array($extension,['csv','xlsx'],true))return back()->withErrors(['file'=>'Bruk CSV eller moderne Excel-format (.xlsx).']);$path=$data['file']->store('imports');try{$parsed=$reader->read(Storage::path($path),$extension);if(count($parsed['rows'])>5000)throw new \RuntimeException('Filen kan inneholde maksimalt 5 000 datarader per import.');$record=DataImport::create(['public_id'=>(string)Str::uuid(),'organization_id'=>$request->user()->organization_id,'created_by'=>$request->user()->id,'original_filename'=>$data['file']->getClientOriginalName(),'stored_path'=>$path,'file_type'=>$extension,'headers'=>$parsed['headers'],'preview'=>array_slice($parsed['rows'],0,10),'mapping'=>$importer->detect($parsed['headers']),'total_rows'=>count($parsed['rows'])]);return redirect()->route('admin.imports',['import'=>$record->public_id])->with('success','Filen er lest. Kontroller kolonnene før du importerer.');}catch(\Throwable$e){Storage::delete($path);return back()->withErrors(['file'=>$e->getMessage()]);}}
 public function execute(Request$request,DataImport$import,TabularImportReader$reader,TenantDataImporter$importer):RedirectResponse{@set_time_limit(300);abort_unless($import->organization_id===$request->user()->organization_id,404);abort_unless($import->status==='uploaded',409);$rules=['mapping'=>['required','array']];foreach(TenantDataImporter::FIELDS as$field=>$label)$rules['mapping.'.$field]=[in_array($field,['customer_name','postal_code'],true)?'required':'nullable','string'];$data=$request->validate($rules);foreach(array_filter($data['mapping'])as$column)if(!in_array($column,$import->headers,true))return back()->withErrors(['mapping'=>'En valgt kolonne finnes ikke i filen.']);$import->update(['status'=>'processing','mapping'=>$data['mapping']]);try{$parsed=$reader->read(Storage::path($import->stored_path),$import->file_type);$result=$importer->run($parsed['rows'],$data['mapping'],$import->organization_id,$request->user()->branch_id);$import->update(['status'=>$result['failed']&&$result['imported']===0?'failed':'completed','imported_rows'=>$result['imported'],'failed_rows'=>$result['failed'],'errors'=>$result['errors'],'completed_at'=>now()]);Storage::delete($import->stored_path);DB::table('audit_logs')->insert(['organization_id'=>$import->organization_id,'user_id'=>$request->user()->id,'action'=>'data_import.completed','subject_type'=>DataImport::class,'subject_id'=>$import->id,'metadata'=>json_encode(['imported'=>$result['imported'],'failed'=>$result['failed']]),'created_at'=>now()]);return redirect()->route('admin.imports')->with('success',$result['imported'].' rader ble importert'.($result['failed']?' · '.$result['failed'].' rader feilet.':' uten feil.'));}catch(\Throwable$e){$import->update(['status'=>'failed','errors'=>[$e->getMessage()],'completed_at'=>now()]);return back()->withErrors(['import'=>$e->getMessage()]);}}
 public function template():StreamedResponse{$headers=array_values(TenantDataImporter::FIELDS);return response()->streamDownload(function()use($headers){$out=fopen('php://output','wb');fwrite($out,"\xEF\xBB\xBF");fputcsv($out,$headers,';','"','\\');fputcsv($out,['Ola Nordmann','ola@example.no','99999999','Privat','','Storgata 1','0182','AB12345','Volvo','XC60','2021','','Vinter','235/55 R19','Nokian','6,5','2024','A-01'],';','"','\\');fclose($out);},'dekkpilot-importmal.csv',['Content-Type'=>'text/csv; charset=UTF-8']);}
}
