<?php
namespace App\Http\Controllers;
use App\Services\GitDeploymentService;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\Artisan;use Illuminate\Support\Facades\DB;use Illuminate\View\View;use Throwable;
class SuperAdminGitUpdateController extends Controller{
 public function show(GitDeploymentService $git):View{return view('superadmin.git-update',['gitStatus'=>$git->inspect(false)]);}
 public function check(GitDeploymentService $git):RedirectResponse{$status=$git->inspect(true);return back()->with($status['available']?'git_status':'git_error',$status);}
 public function connect(Request $request,GitDeploymentService $git):RedirectResponse{$data=$request->validate(['repository_url'=>['required','string','max:500'],'branch'=>['required','string','max:100','regex:/^[A-Za-z0-9._\/-]+$/'],'confirmation'=>['required','in:KOBLE TIL GITHUB']]);try{$status=$git->initialize($data['repository_url'],$data['branch']);DB::table('audit_logs')->insert(['organization_id'=>$request->user()->organization_id,'user_id'=>$request->user()->id,'action'=>'superadmin.git.connected','ip_address'=>$request->ip(),'metadata'=>json_encode(['remote_url'=>$status['remote_url']??null,'branch'=>$status['branch']??null,'head'=>$status['head']??null]),'created_at'=>now()]);return redirect()->route('superadmin.git-update')->with('success',$status['dirty']?'GitHub er koblet til. Serverfilene avviker fra GitHub, så automatisk pull er sperret til avvikene er håndtert.':'GitHub er koblet til og serverfilene samsvarer.')->with('git_status',$status);}catch(Throwable$e){report($e);return back()->withErrors(['git'=>$e->getMessage()])->withInput();}}
 public function pull(Request $request,GitDeploymentService $git):RedirectResponse{$request->validate(['confirmation'=>['required','in:HENT OPPDATERING']]);$lock=fopen(storage_path('app/git-deployment.lock'),'c+');if($lock===false||!flock($lock,LOCK_EX|LOCK_NB)){if(is_resource($lock))fclose($lock);return back()->withErrors(['git'=>'En annen oppdatering kjører allerede.']);}try{$result=$git->deploy();if($result['updated']??false){Artisan::call('optimize:clear');if(function_exists('opcache_reset'))@opcache_reset();}DB::table('audit_logs')->insert(['organization_id'=>$request->user()->organization_id,'user_id'=>$request->user()->id,'action'=>'superadmin.git.'.(($result['updated']??false)?'pulled':'checked'),'ip_address'=>$request->ip(),'metadata'=>json_encode(['previous_head'=>$result['previous_head']??null,'head'=>$result['head']??null,'files'=>$result['updated_files']??[]]),'created_at'=>now()]);return redirect()->route('superadmin.git-update')->with('success',($result['updated']??false)?'Nye programfiler er hentet sikkert fra GitHub.':'Serveren var allerede oppdatert.')->with('git_result',$result);}catch(Throwable$e){report($e);return back()->withErrors(['git'=>$e->getMessage()]);}finally{flock($lock,LOCK_UN);fclose($lock);}}
 public function synchronize(Request $request,GitDeploymentService $git):RedirectResponse{$request->validate(['confirmation'=>['required','in:ERSTATT SERVERFILER']]);$lock=fopen(storage_path('app/git-deployment.lock'),'c+');if($lock===false||!flock($lock,LOCK_EX|LOCK_NB)){if(is_resource($lock))fclose($lock);return back()->withErrors(['git'=>'En annen oppdatering kjører allerede.']);}try{$result=$git->synchronize();try{Artisan::call('optimize:clear');}catch(Throwable $cacheError){report($cacheError);}if(function_exists('opcache_reset'))@opcache_reset();DB::table('audit_logs')->insert(['organization_id'=>$request->user()->organization_id,'user_id'=>$request->user()->id,'action'=>'superadmin.git.synchronized','ip_address'=>$request->ip(),'metadata'=>json_encode(['previous_head'=>$result['previous_head']??null,'head'=>$result['head']??null,'files'=>$result['updated_files']??[]]),'created_at'=>now()]);return redirect()->route('superadmin.git-update')->with('success','Serverens sporede programfiler er erstattet med GitHub-versjonen. Miljø, databasekobling, storage og opplastinger er urørt.')->with('git_result',$result);}catch(Throwable$e){report($e);return back()->withErrors(['git'=>$e->getMessage()]);}finally{flock($lock,LOCK_UN);fclose($lock);}}
}
