<?php
namespace App\Http\Controllers;
use App\Models\Organization;use App\Services\DatabaseUpdateStatus;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\View\View;
class SuperAdminController extends Controller
{
 public function index(Request $request,DatabaseUpdateStatus $updates):View{$query=Organization::query()->with(['users'=>fn($q)=>$q->orderByDesc('role')])->withCount(['users','customers','vehicles','bookings','tireSets']);if($search=trim((string)$request->query('q')))$query->where(fn($q)=>$q->where('name','like',"%{$search}%")->orWhere('organization_number','like',"%{$search}%")->orWhereHas('users',fn($u)=>$u->where('email','like',"%{$search}%")));if(in_array($request->query('status'),['active','trialing','past_due','incomplete','canceled','unpaid'],true))$query->where('subscription_status',$request->query('status'));return view('superadmin.index',['organizations'=>$query->latest()->paginate(30)->withQueryString(),'stats'=>['organizations'=>Organization::count(),'active'=>Organization::whereIn('subscription_status',['active','trialing'])->count(),'attention'=>Organization::whereIn('subscription_status',['past_due','unpaid','incomplete'])->count(),'users'=>\App\Models\User::count()],'updateStatus'=>$updates->inspect()]);}
 public function enter(Request $request,Organization $organization):RedirectResponse{if(!$organization->branches()->where('active',true)->exists())return back()->withErrors(['tenant'=>'Virksomheten har ingen aktiv avdeling.']);$request->session()->put('superadmin_tenant_id',$organization->id);DB::table('audit_logs')->insert(['organization_id'=>$organization->id,'user_id'=>$request->user()->id,'action'=>'superadmin.tenant.entered','subject_type'=>Organization::class,'subject_id'=>$organization->id,'ip_address'=>$request->ip(),'created_at'=>now()]);return redirect()->route('dashboard')->with('success','Du arbeider nå i '.$organization->name.'.');}
 public function leave(Request $request):RedirectResponse{$request->session()->forget('superadmin_tenant_id');return redirect()->route('superadmin')->with('success','Du er tilbake i plattformoversikten.');}
}
