<?php
namespace App\Http\Controllers;
use App\Services\GitDeploymentService;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\Artisan;use Illuminate\Support\Facades\DB;use Illuminate\View\View;use Throwable;
class SuperAdminGitUpdateController extends Controller{
 public function show(GitDeploymentService $git):View{return view('superadmin.git-update',['gitStatus'=>$git->inspect(false)]);}
 public function check(GitDeploymentService $git):RedirectResponse{$status=$git->inspect(true);return back()->with($status['available']?'git_status':'git_error',$status);}
 public function connect(Request $request,GitDeploymentService $git):RedirectResponse{
  $data=$request->validate(['repository_url'=>['required','string','max:500'],'branch'=>['required','string','max:100','regex:/^[A-Za-z0-9._\/-]+$/'],'confirmation'=>['accepted']],['repository_url.required'=>'GitHub-adressen må fylles ut.','branch.required'=>'Gren må fylles ut.','branch.regex'=>'Grenen inneholder ugyldige tegn.','confirmation.accepted'=>'Du må bekrefte at servermappen kan kobles til GitHub.']);
  try{$status=$git->initialize($data['repository_url'],$data['branch']);DB::table('audit_logs')->insert(['organization_id'=>$request->user()->organization_id,'user_id'=>$request->user()->id,'action'=>'superadmin.git.connected','ip_address'=>$request->ip(),'metadata'=>json_encode(['remote_url'=>$status['remote_url']??null,'branch'=>$status['branch']??null,'head'=>$status['head']??null]),'created_at'=>now()]);return redirect()->route('superadmin.git-update')->with('success',$status['dirty']?'GitHub er koblet til. Du kan nå erstatte avvikende programfiler med GitHub-versjonen.':'GitHub er koblet til og serverfilene samsvarer.')->with('git_status',$status);}catch(Throwable$e){report($e);return back()->withErrors(['git'=>$e->getMessage()])->withInput();}
 }
 public function pull(Request $request,GitDeploymentService $git):RedirectResponse{return $this->locked($request,$git,false);}
 public function synchronize(Request $request,GitDeploymentService $git):RedirectResponse{return $this->locked($request,$git,true);}
 private function locked(Request $request,GitDeploymentService $git,bool $replace):RedirectResponse{
  $data=$request->validate(['confirmation'=>['accepted'],'selected_files'=>['required','array','min:1','max:1000'],'selected_files.*'=>['required','string','max:500','regex:/^[^\\x00]+$/']],['confirmation.accepted'=>$replace?'Du må bekrefte at GitHub-versjonen skal erstatte valgte programfiler.':'Du må bekrefte at de valgte filene skal hentes fra GitHub.','selected_files.required'=>'Velg minst én fil som skal oppdateres.']);$lock=fopen(storage_path('app/git-deployment.lock'),'c+');if($lock===false||!flock($lock,LOCK_EX|LOCK_NB)){if(is_resource($lock))fclose($lock);return back()->withErrors(['git'=>'En annen oppdatering kjører allerede.']);}
  try{$result=$replace?$git->synchronize($data['selected_files']):$git->deploy($data['selected_files']);if($result['updated']??false){try{Artisan::call('optimize:clear');}catch(Throwable $cacheError){report($cacheError);}if(function_exists('opcache_reset'))@opcache_reset();}DB::table('audit_logs')->insert(['organization_id'=>$request->user()->organization_id,'user_id'=>$request->user()->id,'action'=>$replace?'superadmin.git.synchronized':'superadmin.git.'.(($result['updated']??false)?'pulled':'checked'),'ip_address'=>$request->ip(),'metadata'=>json_encode(['previous_head'=>$result['previous_head']??null,'head'=>$result['head']??null,'files'=>$result['updated_files']??[],'preserved'=>$result['ignored_files']??[]]),'created_at'=>now()]);$message=($result['updated']??false)?count($result['updated_files']??[]).' valgte programfiler er oppdatert. Fravalgte og beskyttede filer er beholdt.':'Serveren var allerede oppdatert.';return redirect()->route('superadmin.git-update')->with('success',$message)->with('git_result',$result);}catch(Throwable$e){report($e);return back()->withErrors(['git'=>$e->getMessage()]);}finally{flock($lock,LOCK_UN);fclose($lock);}
 }
}
