<?php
namespace App\Http\Controllers;
use App\Services\TestDataGuard;use App\Services\TotpService;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Hash;use Illuminate\Support\Str;use Illuminate\View\View;
class TwoFactorController extends Controller
{
 public function challenge(Request$request):View|RedirectResponse{if(!$request->user()->two_factor_confirmed_at)return redirect()->route('dashboard');return view('auth.two-factor-challenge');}
 public function verify(Request$request,TotpService$totp):RedirectResponse{$data=$request->validate(['code'=>['required','string','max:20']]);$user=$request->user();$input=strtoupper(preg_replace('/\s/','',$data['code']));$valid=$totp->verify((string)$user->two_factor_secret,$input);if(!$valid){$codes=$user->two_factor_recovery_codes??[];$index=collect($codes)->search(fn($hash)=>Hash::check($input,$hash));if($index!==false){unset($codes[$index]);$user->update(['two_factor_recovery_codes'=>array_values($codes)]);$valid=true;}}if(!$valid)return back()->withErrors(['code'=>'Koden er feil eller utløpt.'])->onlyInput('code');$request->session()->put('two_factor_confirmed',true);DB::table('audit_logs')->insert(['organization_id'=>$user->organization_id,'user_id'=>$user->id,'action'=>'security.two_factor.challenge_passed','ip_address'=>$request->ip(),'created_at'=>now()]);return redirect()->intended(route('dashboard'));}
 public function setup(Request$request,TotpService$totp,TestDataGuard$guard):View{$user=$request->user();$demo=$guard->organization((int)$user->organization_id);$setupSecret=$user->two_factor_secret?:$totp->secret();if(!$user->two_factor_secret&&!$demo)$user->update(['two_factor_secret'=>$setupSecret]);return view('admin.security',['tokens'=>DB::table('personal_access_tokens')->where('user_id',$user->id)->latest()->get(),'logs'=>DB::table('audit_logs')->where('organization_id',$user->organization_id)->latest('created_at')->limit(100)->get(),'otpUri'=>$totp->uri($setupSecret,$user->email),'setupSecret'=>$setupSecret,'demoReadOnly'=>$demo]);}
 public function enable(Request$request,TotpService$totp):RedirectResponse{$data=$request->validate(['code'=>['required','digits:6']]);$user=$request->user();if(!$user->two_factor_secret||!$totp->verify((string)$user->two_factor_secret,$data['code']))return back()->withErrors(['code'=>'Koden stemmer ikke. Kontroller tiden på telefonen og prøv igjen.']);$plain=collect(range(1,8))->map(fn()=>strtoupper(Str::random(5).'-'.Str::random(5)));$user->update(['two_factor_confirmed_at'=>now(),'two_factor_recovery_codes'=>$plain->map(fn($code)=>Hash::make($code))->all()]);$request->session()->put('two_factor_confirmed',true);DB::table('audit_logs')->insert(['organization_id'=>$user->organization_id,'user_id'=>$user->id,'action'=>'security.two_factor.enabled','ip_address'=>$request->ip(),'created_at'=>now()]);return back()->with('success','Tofaktor er aktivert. Lagre engangskodene trygt.')->with('recovery_codes',$plain->all());}
 public function disable(Request$request):RedirectResponse{$request->validate(['password'=>['required','current_password']]);$user=$request->user();$user->update(['two_factor_secret'=>null,'two_factor_recovery_codes'=>null,'two_factor_confirmed_at'=>null]);$request->session()->forget('two_factor_confirmed');DB::table('audit_logs')->insert(['organization_id'=>$user->organization_id,'user_id'=>$user->id,'action'=>'security.two_factor.disabled','ip_address'=>$request->ip(),'created_at'=>now()]);return back()->with('success','Tofaktor er deaktivert.');}
 public function revokeToken(Request$request,int$token):RedirectResponse{$user=$request->user();DB::table('personal_access_tokens')->where('user_id',$user->id)->where('id',$token)->update(['revoked_at'=>now(),'updated_at'=>now()]);DB::table('audit_logs')->insert(['organization_id'=>$user->organization_id,'user_id'=>$user->id,'action'=>'security.api_token.revoked','ip_address'=>$request->ip(),'metadata'=>json_encode(['token_id'=>$token]),'created_at'=>now()]);return back()->with('success','App-tilgangen er tilbakekalt.');}
}
