<x-layouts.app title="Krever handling · DekkPilot" heading="Krever handling">
<link rel="stylesheet" href="{{ in_array(request()->getHost(),['localhost','127.0.0.1','::1'],true) ? route('system.asset',['filename'=>'action-center.css']) : asset('action-center.css') }}?v=20260812-4">
<link rel="stylesheet" href="{{ in_array(request()->getHost(),['localhost','127.0.0.1','::1'],true) ? route('system.asset',['filename'=>'action-workflow.css']) : asset('action-workflow.css') }}?v=20260812-3">
<meta name="labels-enabled" content="{{ $labelsEnabled?'1':'0' }}">
@php
    $otherCount = $items->count()
        - (int) ($counts['Hjulsett'] ?? 0)
        - (int) ($counts['Booking'] ?? 0)
        - (int) ($counts['Tilbud'] ?? 0);
@endphp
<section class="stats"><a href="#action-list"><span class="stat-icon orange">{{ $items->count() }}</span><div><small>TOTALT</small><strong>{{ $items->count() }}</strong></div><b>↓</b></a>@foreach(['Hjulsett'=>(int)($counts['Hjulsett']??0),'Booking'=>(int)($counts['Booking']??0),'Tilbud'=>(int)($counts['Tilbud']??0),'Annet'=>$otherCount] as $type=>$count)<a href="#action-list"><span class="stat-icon {{ ['Hjulsett'=>'blue','Booking'=>'violet','Tilbud'=>'green','Annet'=>'orange'][$type] }}">{{ $count }}</span><div><small>{{ strtoupper($type) }}</small><strong>{{ $count }}</strong></div><b>↓</b></a>@endforeach</section>
@if(session('label_url'))<div class="flash action-success">✓ Hjulsettet er lagret. <button class="button" type="button" data-action-label-preview="{{ session('label_url') }}">Forhåndsvis og skriv etikett</button></div>@endif
<section class="panel action-toolbar"><div><p class="eyebrow">UTE VED REOLEN?</p><h2>Skann etiketten med kamera</h2><p>På mobil og nettbrett åpnes riktig hjulsett direkte.</p></div><div class="action-scan"><form method="get" action="{{ route('actions') }}"><input name="code" placeholder="HJ-XXXXXXXX" autocomplete="off" data-action-code><button class="button">Finn</button></form><button class="button ghost" type="button" data-action-camera-open>▣ Bruk kamera</button></div></section>
<section class="panel" id="action-list"><div class="panel-head"><div><p class="eyebrow">ÉN FELLES INNBOKS</p><h2>Dette bør håndteres nå</h2><p>De fem viktigste vises først. Resten er samlet nedenfor, så siden forblir oversiktlig.</p></div></div><div class="action-list">@forelse($items->take(5) as $item)@include('actions._item',['item'=>$item])@empty<div class="empty-state"><strong>✓ Ingen avvik krever handling</strong><span>Alle kontrollerte arbeidsflyter ser bra ut.</span></div>@endforelse @if($items->count()>5)<details class="action-more"><summary>Vis {{ $items->count()-5 }} øvrige oppgaver</summary><div class="action-list">@foreach($items->slice(5) as $item)@include('actions._item',['item'=>$item])@endforeach</div></details>@endif</div></section>

@foreach($items->whereNotNull('kind') as $item)@php $model=$item['model']; @endphp
<dialog class="action-quick-dialog" id="action-{{ $item['kind'] }}-{{ $model->id }}"><div class="action-quick-head"><div><p class="eyebrow">{{ strtoupper($item['type']) }}</p><h2>{{ $item['title'] }}</h2></div><button type="button" data-action-dialog-close aria-label="Lukk">×</button></div><div class="action-quick-body"><p>{{ $item['detail'] }}</p>
@if($item['kind']==='booking')<div class="action-fact"><span>Tidspunkt</span><strong>{{ $model->starts_at->translatedFormat('l d. F · H:i') }}</strong><span>Kunde</span><strong>{{ $model->customer->name }}</strong></div><form method="post" action="{{ route('actions.resolve',['kind'=>'booking','id'=>$model->id]) }}" class="action-quick-buttons">@csrf<button class="button ghost danger" name="decision" value="cancel">Avbestill</button><button class="button" name="decision" value="confirm">Bekreft timen</button></form>
@elseif($item['kind']==='inspection')<div class="action-fact"><span>Kunde</span><strong>{{ $model->vehicle?->customer?->name??'Ukjent kunde' }}</strong><span>Bil og hjulsett</span><strong>{{ $model->vehicle?->registration_number??'Uten registreringsnummer' }} · {{ ['winter'=>'Vinterhjul','summer'=>'Sommerhjul','all_season'=>'Helårshjul'][$model->season]??'Hjulsett' }}</strong><span>Siste måling</span><strong>{{ $item['last_measured_at']?->format('d.m.Y')??'Aldri målt' }}</strong></div><a class="button full" href="{{ route('tire-sets.inspection',$model) }}">Åpne firehjulskontroll →</a>
@elseif($item['kind']==='count')<div class="action-fact"><span>Hjulkode</span><strong>{{ $model->code }}</strong><span>Plass</span><strong>{{ $model->storageLocation?->code??'Uten lagerplass' }}</strong></div><form method="post" action="{{ route('actions.resolve',['kind'=>'count','id'=>$model->id]) }}">@csrf<input type="hidden" name="decision" value="count"><button class="button full">Ja, hjulsettet er kontrollert</button></form>
@elseif($item['kind']==='agreement')<div class="action-fact"><span>Nåværende fornyelse</span><strong>{{ $model->renews_on->format('d.m.Y') }}</strong><span>Pris per halvår</span><strong>{{ number_format($model->price_cents/100,0,',',' ') }} kr</strong></div><form method="post" action="{{ route('actions.resolve',['kind'=>'agreement','id'=>$model->id]) }}">@csrf<input type="hidden" name="decision" value="renew"><button class="button full">Forny avtalen seks måneder</button></form>
@elseif($item['kind']==='message')<div class="action-error-box">{{ $model->last_error }}</div><div class="action-fact"><span>Kanal</span><strong>{{ strtoupper($model->channel) }}</strong><span>Mottaker</span><strong>{{ $model->recipient }}</strong></div><form method="post" action="{{ route('actions.resolve',['kind'=>'message','id'=>$model->id]) }}">@csrf<input type="hidden" name="decision" value="retry"><button class="button full">Prøv å sende på nytt</button></form>
@elseif($item['kind']==='invoice')<div class="action-error-box">{{ $model->last_error }}</div><div class="action-fact"><span>Referanse</span><strong>{{ $model->reference }}</strong><span>Beløp</span><strong>{{ number_format($model->total_cents/100,0,',',' ') }} kr</strong></div><form method="post" action="{{ route('admin.accounting.queue',$model) }}">@csrf<button class="button full">Send til regnskapssystemet på nytt</button></form>
@elseif($item['kind']==='offer')<div class="action-fact"><span>Kunde</span><strong>{{ $model->vehicle->customer->name }}</strong><span>Bil og dimensjon</span><strong>{{ $model->vehicle->registration_number }} · {{ $model->size }}</strong></div><form method="post" action="{{ route('quotes.suggestion.send',$model) }}">@csrf<input type="hidden" name="_action_center" value="1"><div class="action-offer-options">@foreach($model->portalOptions as $product)<label><input type="checkbox" name="product_ids[]" value="{{ $product->id }}" checked><span><strong>{{ ['Det beste','Bra valg','Godt valg'][$loop->index] }}</strong>{{ $product->brand }} {{ $product->model }}<small>{{ number_format(($product->price_cents*4)/100,0,',',' ') }} kr · 4 stk.</small></span></label>@endforeach</div><label>Melding til kunden<textarea name="message" rows="3" maxlength="2000" placeholder="Valgfri personlig melding"></textarea></label><button class="button full">Send tilbud med disse valgene</button></form>
@endif</div></dialog>@endforeach

@php
$tirePayload=$tireSets->map(function($set){$last=$set->inspections->first();$measurements=$last?->measurements?->pluck('tread_depth_mm','position')??collect();$needs=collect();if(!$set->storage_location_id)$needs->push('location');if($set->minimum_tread_depth===null)$needs->push('measure');if(in_array($set->wash_status??'not_assessed',['not_assessed','needed'],true))$needs->push('wash');if(!$set->label_printed_at)$needs->push('label');return ['id'=>$set->id,'action'=>route('actions.tire-set.update',$set),'code'=>$set->code,'registration'=>$set->vehicle?->registration_number,'customer'=>$set->vehicle?->customer?->name,'customer_url'=>$set->vehicle?->customer?route('customers.show',$set->vehicle->customer):null,'tire_url'=>route('tire-sets.show',$set),'label_url'=>route('tire-sets.labels',['ids'=>$set->id]),'location_id'=>$set->storage_location_id,'storage_shelf_number'=>$set->storage_shelf_number,'storage_position_number'=>$set->storage_position_number,'wash_status'=>$set->wash_status??'not_assessed','minimum'=>$set->minimum_tread_depth,'measurements'=>$measurements,'needs'=>$needs->values()];})->values();
@endphp
<dialog class="action-tire-dialog" data-action-tire-dialog data-tires='@json($tirePayload)' data-open-id="{{ $openTireSetId }}"><div class="action-dialog-head"><div><p class="eyebrow"><span data-action-step-progress>STEG 1 AV 1</span> · <span data-action-tire-code>HJULSETT</span></p><h2 data-action-tire-title>Fullfør avvik</h2><p><a data-action-customer-link href="#"><span data-action-tire-customer></span> → åpne kundekort</a></p></div><button type="button" data-action-tire-close aria-label="Lukk">×</button></div><form method="post" class="action-tire-form" data-action-tire-form>@csrf @method('PUT')<section class="action-dialog-section" data-work-step="location"><p class="step-label"><b data-step-number>1</b><span><strong>Hvor skal hjulsettet stå?</strong><small>Velg rad/reol, og angi lengde og høyde eller bruk automatisk plassering.</small></span></p><div class="location-choice-grid">@foreach($locations as $location)<label><input type="radio" name="storage_location_id" value="{{ $location->id }}" required @disabled($location->tire_sets_count >= $location->capacity)><span><strong>{{ $location->code }}</strong><small>{{ $location->label?:$location->zone }} · {{ $location->tire_sets_count }}/{{ $location->capacity }}</small></span></label>@endforeach</div><x-storage-coordinates/></section>
<section class="action-dialog-section"><p class="step-label"><b>2</b><span><strong>Mål mønsterdybden</strong><small>Fyll inn alle fire når måling mangler. Store felt er tilpasset nettbrett.</small></span></p><fieldset class="action-car-measurements"><legend class="screen-reader-only">Mønsterdybde på fire hjul</legend><svg class="action-car" viewBox="0 0 180 360" aria-label="Bil sett ovenfra"><path class="car-shadow" d="M40 52Q45 18 90 12q45 6 50 40l14 58v180l-14 50H40l-14-50V110z"/><path class="car-body" d="M48 55Q52 28 90 22q38 6 42 33l12 60-8 165 8 45H36l8-45-8-165z"/><path class="car-glass" d="m57 72 12-30h42l12 30 7 48H50zM50 239h80l-9 66H59z"/><path class="car-line" d="M48 132h84M48 226h84M90 132v94"/></svg>@foreach(['front_left'=>'Venstre foran','front_right'=>'Høyre foran','rear_left'=>'Venstre bak','rear_right'=>'Høyre bak'] as $position=>$label)<label class="action-wheel action-wheel-{{ str_replace('_','-',$position) }}"><span>{{ $label }}</span><span><input name="wheels[{{ $loop->index }}][tread_depth_mm]" type="number" inputmode="decimal" step="0.1" min="0" max="20" data-action-depth="{{ $position }}"><b>mm</b></span><input type="hidden" name="wheels[{{ $loop->index }}][position]" value="{{ $position }}"></label>@endforeach</fieldset><div class="action-depth-result" data-action-depth-result>Fyll inn målingene</div></section>
<section class="action-dialog-section"><p class="step-label"><b>3</b><span><strong>Vaskestatus</strong><small>Ett trykk er nok.</small></span></p><div class="wash-choice-grid"><label><input type="radio" name="wash_status" value="needed" required><span>💧<strong>Trenger vask</strong></span></label><label><input type="radio" name="wash_status" value="washed"><span>✓<strong>Vasket</strong></span></label><label><input type="radio" name="wash_status" value="not_needed"><span>–<strong>Trenger ikke vask</strong></span></label></div></section><section class="action-dialog-section action-label-step"><p class="step-label"><b>4</b><span><strong>Gjør etiketten klar</strong><small>Etiketten åpnes automatisk etter at opplysningene er lagret.</small></span></p><div class="action-selected-tire"><span>▤</span><div><strong data-action-label-registration></strong><small data-action-label-code></small></div></div></section><div class="action-dialog-footer"><button type="button" class="button ghost" data-action-step-back>← Forrige</button><button type="button" class="button" data-action-step-next>Neste →</button><button class="button" data-action-step-save>Lagre og fullfør</button></div></form></dialog>

<dialog class="camera-modal" data-action-camera-modal><div class="camera-head"><div><p class="eyebrow">SKANN HJULETIKETT</p><h2>Hold koden foran kameraet</h2></div><button type="button" data-action-camera-close>×</button></div><video playsinline data-action-camera-video></video><p data-action-camera-status>Kameraet starter når du trykker.</p><button class="button full" type="button" data-action-camera-start>Start kamera</button></dialog>
<dialog class="label-modal" data-action-label-modal><div class="label-modal-head"><div><p class="eyebrow">UTSKRIFTSKLAR</p><h2>Forhåndsvis etikett</h2></div><button type="button" data-action-label-close>×</button></div><div class="label-frame-wrap"><iframe title="Forhåndsvisning av etikett" data-action-label-frame></iframe></div><div class="label-modal-actions"><button class="button ghost" type="button" data-action-label-close>Tilbake</button><button class="button" type="button" data-action-label-print>▤ Skriv ut etikett</button></div></dialog>
<script defer src="{{ in_array(request()->getHost(),['localhost','127.0.0.1','::1'],true) ? route('system.asset',['filename'=>'action-center.js']) : asset('action-center.js') }}?v=20261003-1"></script>
</x-layouts.app>
