<x-layouts.app title="Krever handling · DekkPilot" heading="Krever handling">
<link rel="stylesheet" href="{{ asset('action-center.css') }}?v=20260811-3">
<section class="stats"><a href="#action-list"><span class="stat-icon orange">{{ $items->count() }}</span><div><small>TOTALT</small><strong>{{ $items->count() }}</strong></div><b>↓</b></a>@foreach(['Hjulsett','Booking','Tilbud'] as $type)<a href="#action-list"><span class="stat-icon {{ $loop->iteration===1?'blue':($loop->iteration===2?'violet':'green') }}">{{ $counts[$type]??0 }}</span><div><small>{{ strtoupper($type) }}</small><strong>{{ $counts[$type]??0 }}</strong></div><b>↓</b></a>@endforeach</section>
@if(session('label_url'))<div class="flash action-success">✓ Hjulsettet er lagret. <button class="button" type="button" data-action-label-preview="{{ session('label_url') }}">Forhåndsvis og skriv etikett</button></div>@endif
<section class="panel action-toolbar"><div><p class="eyebrow">UTE VED REOLEN?</p><h2>Skann etiketten med kamera</h2><p>På mobil og nettbrett åpnes riktig hjulsett direkte.</p></div><div class="action-scan"><form method="get" action="{{ route('actions') }}"><input name="code" placeholder="HJ-XXXXXXXX" autocomplete="off" data-action-code><button class="button">Finn</button></form><button class="button ghost" type="button" data-action-camera-open>▣ Bruk kamera</button></div></section>
<section class="panel" id="action-list"><div class="panel-head"><div><p class="eyebrow">ÉN FELLES INNBOKS</p><h2>Dette bør håndteres nå</h2><p>Trykk på et hjulsett for å ordne lagerplass, målinger og vask uten å forlate siden.</p></div></div><div class="action-list">@forelse($items as $item)@if(isset($item['tire_set_id']))<button type="button" class="action-item priority-{{ $item['priority'] }}" data-action-tire-open="{{ $item['tire_set_id'] }}"><span class="status cancelled">{{ $item['type'] }}</span><span><strong>{{ $item['title'] }}</strong><small>{{ $item['detail'] }}</small></span><b>Ordne nå →</b></button>@else<a href="{{ $item['url'] }}" class="action-item priority-{{ $item['priority'] }}"><span class="status {{ $item['priority']===1?'cancelled':($item['priority']===2?'in_progress':'scheduled') }}">{{ $item['type'] }}</span><span><strong>{{ $item['title'] }}</strong><small>{{ Str::limit($item['detail']??'',180) }}</small></span><b>Åpne →</b></a>@endif @empty<div class="empty-state"><strong>✓ Ingen avvik krever handling</strong><span>Alle kontrollerte arbeidsflyter ser bra ut.</span></div>@endforelse</div></section>

@php
$tirePayload=$tireSets->map(function($set){$last=$set->inspections->first();$measurements=$last?->measurements?->pluck('tread_depth_mm','position')??collect();return ['id'=>$set->id,'action'=>route('actions.tire-set.update',$set),'code'=>$set->code,'registration'=>$set->vehicle?->registration_number,'customer'=>$set->vehicle?->customer?->name,'location_id'=>$set->storage_location_id,'wash_status'=>$set->wash_status??'not_assessed','minimum'=>$set->minimum_tread_depth,'measurements'=>$measurements];})->values();
@endphp
<dialog class="action-tire-dialog" data-action-tire-dialog data-tires='@json($tirePayload)' data-open-id="{{ $openTireSetId }}"><div class="action-dialog-head"><div><p class="eyebrow" data-action-tire-code>HJULSETT</p><h2 data-action-tire-title>Fullfør avvik</h2><p data-action-tire-customer></p></div><button type="button" data-action-tire-close aria-label="Lukk">×</button></div><form method="post" class="action-tire-form" data-action-tire-form>@csrf @method('PUT')<section class="action-dialog-section"><p class="step-label"><b>1</b><span><strong>Hvor skal hjulsettet stå?</strong><small>Velg reol. Ledig hylle tildeles automatisk.</small></span></p><div class="location-choice-grid">@foreach($locations as $location)<label><input type="radio" name="storage_location_id" value="{{ $location->id }}" required @disabled($location->tire_sets_count >= $location->capacity)><span><strong>{{ $location->code }}</strong><small>{{ $location->label?:$location->zone }} · {{ $location->tire_sets_count }}/{{ $location->capacity }}</small></span></label>@endforeach</div></section>
<section class="action-dialog-section"><p class="step-label"><b>2</b><span><strong>Mål mønsterdybden</strong><small>Fyll inn alle fire når måling mangler. Store felt er tilpasset nettbrett.</small></span></p><fieldset class="action-car-measurements"><legend class="screen-reader-only">Mønsterdybde på fire hjul</legend><svg class="action-car" viewBox="0 0 180 360" aria-label="Bil sett ovenfra"><path class="car-shadow" d="M40 52Q45 18 90 12q45 6 50 40l14 58v180l-14 50H40l-14-50V110z"/><path class="car-body" d="M48 55Q52 28 90 22q38 6 42 33l12 60-8 165 8 45H36l8-45-8-165z"/><path class="car-glass" d="m57 72 12-30h42l12 30 7 48H50zM50 239h80l-9 66H59z"/><path class="car-line" d="M48 132h84M48 226h84M90 132v94"/></svg>@foreach(['front_left'=>'Venstre foran','front_right'=>'Høyre foran','rear_left'=>'Venstre bak','rear_right'=>'Høyre bak'] as $position=>$label)<label class="action-wheel action-wheel-{{ str_replace('_','-',$position) }}"><span>{{ $label }}</span><span><input name="wheels[{{ $loop->index }}][tread_depth_mm]" type="number" inputmode="decimal" step="0.1" min="0" max="20" data-action-depth="{{ $position }}"><b>mm</b></span><input type="hidden" name="wheels[{{ $loop->index }}][position]" value="{{ $position }}"></label>@endforeach</fieldset><div class="action-depth-result" data-action-depth-result>Fyll inn målingene</div></section>
<section class="action-dialog-section"><p class="step-label"><b>3</b><span><strong>Vaskestatus</strong><small>Ett trykk er nok.</small></span></p><div class="wash-choice-grid"><label><input type="radio" name="wash_status" value="needed" required><span>💧<strong>Trenger vask</strong></span></label><label><input type="radio" name="wash_status" value="washed"><span>✓<strong>Vasket</strong></span></label><label><input type="radio" name="wash_status" value="not_needed"><span>–<strong>Trenger ikke vask</strong></span></label></div></section><div class="action-dialog-footer"><button type="button" class="button ghost" data-action-tire-close>Avbryt</button><button class="button">Lagre og gjør klar etikett</button></div></form></dialog>

<dialog class="camera-modal" data-action-camera-modal><div class="camera-head"><div><p class="eyebrow">SKANN HJULETIKETT</p><h2>Hold koden foran kameraet</h2></div><button type="button" data-action-camera-close>×</button></div><video playsinline data-action-camera-video></video><p data-action-camera-status>Kameraet starter når du trykker.</p><button class="button full" type="button" data-action-camera-start>Start kamera</button></dialog>
<dialog class="label-modal" data-action-label-modal><div class="label-modal-head"><div><p class="eyebrow">UTSKRIFTSKLAR</p><h2>Forhåndsvis etikett</h2></div><button type="button" data-action-label-close>×</button></div><div class="label-frame-wrap"><iframe title="Forhåndsvisning av etikett" data-action-label-frame></iframe></div><div class="label-modal-actions"><button class="button ghost" type="button" data-action-label-close>Tilbake</button><button class="button" type="button" data-action-label-print>▤ Skriv ut etikett</button></div></dialog>
<script defer src="{{ asset('action-center.js') }}?v=20260811-3"></script>
</x-layouts.app>
