<x-layouts.app title="Meldingskø · DekkPilot" heading="Kommunikasjon">
<link rel="stylesheet" href="{{ asset('sms-settings.css') }}?v=20260810-1">
<div class="usage-note"><strong>SMS krever egen Twilio-konto og faktureres etter bruk</strong><span>Virksomheten oppretter og betaler Twilio-kontoen selv. DekkPilot lagrer tilkoblingen kryptert, men tar ikke betalt for eller leverer selve SMS-trafikken. E-post er inkludert.</span></div>
<section class="stats"><article><span class="stat-icon blue">…</span><div><small>I KØ</small><strong>{{ $stats['queued'] ?? 0 }}</strong></div></article><article><span class="stat-icon green">✓</span><div><small>SENDT</small><strong>{{ $stats['sent'] ?? 0 }}</strong></div></article><article><span class="stat-icon orange">!</span><div><small>FEILET</small><strong>{{ $stats['failed'] ?? 0 }}</strong></div></article><article><span class="stat-icon violet">SMS</span><div><small>TWILIO</small><strong>{{ $twilioConfigured ? 'På':'Av' }}</strong></div></article></section>

<section class="sms-onboarding panel"><div><p class="eyebrow">SMS-OPPSETT</p><h2>Virksomheten kobler til sin egen Twilio-konto</h2><p>DekkPilot kan sende varslene automatisk etter at dere har opprettet Twilio-konto, kjøpt eller godkjent avsender og limt inn nøklene nedenfor.</p></div><ol><li><span>1</span><div><strong>Opprett Twilio-konto</strong><small>Registrer virksomheten og aktiver fakturering direkte hos Twilio.</small></div></li><li><span>2</span><div><strong>Opprett avsender og API-nøkkel</strong><small>Bruk et Twilio-nummer eller Messaging Service og en begrenset API Key.</small></div></li><li><span>3</span><div><strong>Koble til og test</strong><small>Lim inn verdiene manuelt, lagre og send én test-SMS.</small></div></li></ol><p class="sms-trial-note">Har dere prøveversjon hos Twilio, kan test-SMS normalt bare sendes til telefonnumre som er verifisert i Twilio-kontoen.</p></section>

<section class="grid two"><article class="panel"><p class="eyebrow">NY UTSENDING</p><h2>Send e-post eller SMS</h2><form method="post" action="{{ route('admin.communications.send') }}" class="stack" data-email-compose data-preview-url="{{ route('admin.communications.preview') }}">@csrf<label>Mottakere<select name="audience"><option value="customer">Én kunde</option><option value="all_consented">Alle kunder med markedsføringssamtykke</option></select></label><label>Kunde<select name="customer_id"><option value="">Velg ved enkeltutsending</option>@foreach($customers as $customer)<option value="{{ $customer->id }}">{{ $customer->name }} · {{ $customer->email ?: $customer->phone }}</option>@endforeach</select></label><label>Kanal<select name="channel"><option value="email">E-post</option><option value="sms">SMS</option></select></label><label>Emne (e-post)<input name="subject" maxlength="200"></label><label>Melding<textarea name="body" rows="7" maxlength="5000" required></textarea></label><div class="compose-actions"><button type="button" class="button ghost" data-preview-draft>Forhåndsvis e-post</button><button class="button">Legg i utsendingskø</button></div><p class="fine">Masseutsending går bare til kunder med aktivt markedsføringssamtykke. SMS-kampanjer må også aktiveres nedenfor.</p></form></article>

<article class="panel twilio-connect"><div class="panel-head"><div><p class="eyebrow">MANUELL TILKOBLING</p><h2>Twilio Messaging</h2></div><span class="status {{ $twilioConfigured?'completed':'cancelled' }}">{{ $twilioConfigured?'Tilkoblet':'Ikke tilkoblet' }}</span></div><p class="muted">Verdiene finner dere i Twilio Console. De krypteres og vises aldri igjen. Ved endring må alle fire fylles inn på nytt.</p><form method="post" action="{{ route('admin.twilio.update') }}" class="stack">@csrf @method('PUT')<label>Account SID<input name="account_sid" placeholder="AC + 32 tegn" required autocomplete="off"><small>Twilio Console → Account Info</small></label><label>API Key SID<input name="api_key" placeholder="SK + 32 tegn" required autocomplete="off"><small>Twilio Console → API keys &amp; tokens</small></label><label>API Key Secret<input type="password" name="api_secret" autocomplete="new-password" required><small>Vises bare én gang når API-nøkkelen opprettes.</small></label><label>Twilio-nummer eller Messaging Service SID<input name="from" placeholder="+47… eller MG…" required><small>Nummer i E.164-format eller en SID som starter med MG.</small></label><button class="button full">{{ $twilioConfigured?'Erstatt Twilio-tilkobling':'Koble til Twilio manuelt' }}</button></form></article></section>

<section class="grid two sms-controls"><article class="panel"><div class="panel-head"><div><p class="eyebrow">AUTOMATISKE VARSLER</p><h2>Hva skal sendes på SMS?</h2></div><span class="status {{ $smsSettings->sms_enabled?'completed':'cancelled' }}">{{ $smsSettings->sms_enabled?'Aktiv':'Av' }}</span></div><form method="post" action="{{ route('admin.twilio.settings') }}" class="sms-toggle-list">@csrf @method('PUT')<label><span><strong>Bruk SMS-varsling</strong><small>Hovedbryter for alle automatiske SMS-er.</small></span><input type="checkbox" name="sms_enabled" value="1" @checked($smsSettings->sms_enabled)></label><label><span><strong>Ny booking</strong><small>Send bekreftelseslenke når en time reserveres.</small></span><input type="checkbox" name="sms_booking_confirmation_enabled" value="1" @checked($smsSettings->sms_booking_confirmation_enabled)></label><label><span><strong>24-timers svarfrist</strong><small>Påminn syv dager før når timen fortsatt ikke er bekreftet.</small></span><input type="checkbox" name="sms_booking_reminder_enabled" value="1" @checked($smsSettings->sms_booking_reminder_enabled)></label><label><span><strong>SMS-kampanjer</strong><small>Tillat manuell masseutsending til kunder med samtykke.</small></span><input type="checkbox" name="sms_marketing_enabled" value="1" @checked($smsSettings->sms_marketing_enabled)></label><button class="button full">Lagre SMS-innstillinger</button></form></article>

<article class="panel sms-test"><div class="panel-head"><div><p class="eyebrow">TEST TILKOBLINGEN</p><h2>Send SMS til deg selv</h2></div><span class="status {{ $twilioConfigured?'in_progress':'cancelled' }}">1 SMS</span></div><p>Testen sendes umiddelbart gjennom virksomhetens Twilio-konto og registreres i meldingsloggen. Twilios ordinære pris gjelder.</p><form method="post" action="{{ route('admin.twilio.test') }}" class="stack">@csrf<label>Ditt mobilnummer<input name="phone" value="{{ old('phone') }}" inputmode="tel" autocomplete="tel" placeholder="99999999 eller +4799999999" required></label>@error('phone')<small class="field-error">{{ $message }}</small>@enderror<button class="button full" {{ $twilioConfigured?'':'disabled' }}>Send test-SMS nå</button></form>@unless($twilioConfigured)<p class="empty">Koble til Twilio først. Testknappen aktiveres etterpå.</p>@endunless</article></section>

<section class="panel"><div class="panel-head"><div><p class="eyebrow">SPORBAR KØ</p><h2>Alle meldinger</h2></div></div><div class="table-wrap"><table><thead><tr><th>Planlagt</th><th>Kanal</th><th>Mottaker</th><th>Innhold</th><th>Forsøk</th><th>Status</th><th></th></tr></thead><tbody>@forelse($messages as $message)@php($shownStatus=$message->delivery_status ?: $message->status)<tr><td>{{ $message->scheduled_at->format('d.m.Y H:i') }}<small>{{ $message->sent_at?->format('d.m.Y H:i') }}</small></td><td><span class="tag">{{ $message->channel }}</span></td><td>{{ $message->recipient }}</td><td>{{ Str::limit($message->subject ?: $message->body,70) }}@if($message->last_error)<small>{{ Str::limit($message->last_error,100) }}</small>@endif</td><td>{{ $message->attempts }}</td><td><span class="status {{ in_array($shownStatus,['sent','delivered'],true)?'completed':(in_array($shownStatus,['failed','undelivered'],true)?'cancelled':'in_progress') }}">{{ ['queued'=>'I kø','processing'=>'Sender','sent'=>'Sendt','delivered'=>'Levert','failed'=>'Feilet','undelivered'=>'Ikke levert'][$shownStatus] ?? ucfirst($shownStatus) }}</span></td><td>@if($message->channel==='email')<button type="button" class="table-action" data-preview-message="{{ route('admin.communications.message-preview',$message) }}">Forhåndsvis</button>@endif</td></tr>@empty<tr><td colspan="7" class="empty">Ingen meldinger i køen ennå.</td></tr>@endforelse</tbody></table></div>{{ $messages->links() }}</section>
<dialog class="email-preview-dialog" data-email-preview aria-labelledby="email-preview-title"><div class="email-preview-head"><div><p class="eyebrow">SLIK SER KUNDEN E-POSTEN</p><h2 id="email-preview-title">Forhåndsvisning</h2></div><button type="button" class="email-preview-close" data-preview-close aria-label="Lukk">×</button></div><div class="email-preview-state" data-preview-state>Laster forhåndsvisning …</div><iframe title="Forhåndsvisning av e-post" data-preview-frame></iframe><div class="email-preview-footer"><button type="button" class="button ghost" data-preview-close>Tilbake og rediger</button></div></dialog>
</x-layouts.app>
