<x-layouts.app title="Importer data · DekkPilot" heading="Importer fra annet system">
<div class="admin-subnav"><a href="{{ route('admin') }}">← Admin</a><a href="#upload">Last opp</a><a href="#history">Historikk</a></div>
@if($pending)
<section class="panel"><div class="panel-head"><div><p class="eyebrow">TRINN 2 AV 2</p><h2>Kontroller kolonnene</h2><p class="muted">{{ $pending->original_filename }} · {{ $pending->total_rows }} datarader</p></div><span class="status in_progress">Ikke importert ennå</span></div>
<form method="post" action="{{ route('admin.imports.execute',$pending) }}" class="stack">@csrf<div class="mapping-grid">@foreach($fields as $field=>$label)<label>{{ $label }}<select name="mapping[{{ $field }}]" {{ $field==='customer_name'?'required':'' }}><option value="">Ikke importer</option>@foreach($pending->headers as $header)<option value="{{ $header }}" @selected(($pending->mapping[$field]??'')===$header)>{{ $header }}</option>@endforeach</select></label>@endforeach</div><div class="table-wrap preview-table"><table><thead><tr>@foreach($pending->headers as $header)<th>{{ $header }}</th>@endforeach</tr></thead><tbody>@foreach($pending->preview as $row)<tr>@foreach($pending->headers as $header)<td>{{ $row[$header]??'' }}</td>@endforeach</tr>@endforeach</tbody></table></div><div class="import-confirm"><p><strong>Importen kan opprette kunder, biler og hjulsett.</strong><br><span class="muted">Eksisterende biler matches på registreringsnummer. Kunder matches på e-post.</span></p><button class="button" data-confirm="Start import av {{ $pending->total_rows }} rader?">Importer {{ $pending->total_rows }} rader</button></div></form></section>
@else
<section class="grid form-grid" id="upload"><article class="panel"><p class="eyebrow">TRINN 1 AV 2</p><h2>Last opp eksportfil</h2><p>Eksporter kundene fra det gamle systemet som <strong>Excel (.xlsx)</strong> eller <strong>CSV</strong>. Første rad må inneholde kolonnenavn.</p><form method="post" action="{{ route('admin.imports.upload') }}" enctype="multipart/form-data" class="stack">@csrf<label>Velg fil<input type="file" name="file" accept=".csv,.xlsx,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" required><small>Maks 50 MB og 5 000 rader per import. Store filer kan bruke noen minutter. Filen lagres privat og slettes etter behandling.</small></label><button class="button full">Les fil og forhåndsvis</button></form></article><aside class="panel"><p class="eyebrow">USIKKER PÅ FORMATET?</p><h2>Bruk importmalen</h2><p class="muted">Malen viser alle støttede felt. Kolonner du ikke har kan stå tomme.</p><a class="button ghost full" href="{{ route('admin.imports.template') }}">↓ Last ned CSV-mal</a><hr><p class="fine">Gamle Excel-filer av typen .xls må åpnes og lagres som .xlsx først.</p></aside></section>
@endif
<section class="panel" id="history"><div class="panel-head"><div><p class="eyebrow">HISTORIKK</p><h2>Tidligere importer</h2></div></div><div class="table-wrap"><table><thead><tr><th>Fil</th><th>Tidspunkt</th><th>Resultat</th><th>Status</th></tr></thead><tbody>@forelse($history as $item)<tr><td><strong>{{ $item->original_filename }}</strong><small>{{ strtoupper($item->file_type) }}</small></td><td>{{ $item->created_at->format('d.m.Y H:i') }}</td><td>{{ $item->imported_rows }} importert<small>{{ $item->failed_rows }} feilet · {{ $item->total_rows }} totalt</small>@if($item->errors)<details><summary>Se feil</summary><ul>@foreach($item->errors as $error)<li>{{ $error }}</li>@endforeach</ul></details>@endif</td><td><span class="status {{ $item->status==='completed'?'completed':($item->status==='failed'?'cancelled':'in_progress') }}">{{ $item->status }}</span></td></tr>@empty<tr><td colspan="4" class="empty">Ingen filer er importert ennå.</td></tr>@endforelse</tbody></table></div></section>
</x-layouts.app>
