<x-layouts.app title="Kundebetalinger · DekkPilot" heading="Ta betalt fra kundene dine">
<div class="admin-subnav"><a href="{{ route('admin') }}">← Admin</a><a href="#stripe">Stripe</a><a href="#zettle">Zettle</a><a href="#vipps">Vipps</a><a href="#terminal">Annen terminal</a><a href="{{ route('admin.accounting') }}">Regnskap og faktura</a></div>
<section class="panel"><h2>Velg hvordan verkstedets kunder skal betale</h2><p>Opprett konto hos betalingstilbyderen i virksomhetens eget navn, med organisasjonsnummer og konto for oppgjør. Pengene utbetales av leverandøren til virksomheten din. Leverandørens priser og avtalevilkår gjelder.</p><p>Denne siden gjelder kundebetalinger for verkstedjobber. <a href="{{ route('billing') }}">DekkPilot-abonnementet på 249 kr/mnd administreres separat</a>.</p>
<div class="table-wrap"><table><thead><tr><th>Løsning</th><th>Kunden betaler</th><th>Bekreftelse i DekkPilot</th><th>Status</th></tr></thead><tbody>
<tr><td><a href="#stripe">Stripe</a></td><td>Med kort på en sikker nettside</td><td>Automatisk fra Stripe</td><td>{{ $stripe['active'] ? 'Aktiv' : 'Ikke aktiv' }}</td></tr>
<tr><td><a href="#zettle">Zettle / PayPal Point of Sale</a></td><td>I appen med kortleser</td><td>Ansatt kontrollerer kvitteringen og registrerer referansen</td><td>{{ $zettle['active'] ? 'Aktiv' : 'Ikke aktiv' }}</td></tr>
<tr><td><a href="#vipps">Vipps</a></td><td>I Vipps-appen</td><td>Automatisk fra Vipps</td><td>{{ $vipps['active'] ? 'Aktiv' : 'Ikke aktiv' }}</td></tr>
<tr><td><a href="#terminal">Annen bankterminal</a></td><td>På terminalen i kassen</td><td>Krever egen terminal-/kasseintegrasjon</td><td>{{ $terminal['active'] ? 'Aktiv' : 'Ikke aktiv' }}</td></tr>
</tbody></table></div></section>
<section class="panel" id="stripe"><div class="panel-head"><div><p class="eyebrow">KORTBETALING PÅ NETT</p><h2>Stripe</h2></div><span class="status">{{ $stripe['active'] ? 'Aktiv' : 'Ikke aktiv' }}</span></div>
<ol><li><a href="https://dashboard.stripe.com/register" target="_blank" rel="noopener">Opprett Stripe-konto</a>, eller logg inn på virksomhetens eksisterende konto. Fullfør bedriftskontroll og oppgjørskonto hos Stripe.</li>
<li>Åpne <a href="https://dashboard.stripe.com/apikeys" target="_blank" rel="noopener">Developers / API keys</a> i live-miljø. Opprett en begrenset nøkkel (<code>rk_live_…</code>) for DekkPilot med lesetilgang til kontoopplysninger og skrive-/lesetilgang til Checkout Sessions og Webhook Endpoints. <a href="https://docs.stripe.com/keys" target="_blank" rel="noopener">Hjelp fra Stripe</a>.</li>
<li>Lim inn nøkkelen nedenfor og huk av for aktivering. DekkPilot kontrollerer kontoen og oppretter betalingsvarsler automatisk. Du trenger ikke pris-ID eller produkt-ID: beløpet hentes fra den ferdige jobben.</li></ol>
@if($stripe['account_id']??null)<p>Kontrollert konto: <strong>{{ $stripe['account_name']??$stripe['account_id'] }}</strong> · {{ $stripe['account_id'] }} · {{ ($stripe['live']??false) ? 'Live' : 'Test – kan ikke brukes til kundebetaling' }}</p>@endif
<form method="post" action="{{ route('admin.payments.stripe') }}" class="stack">@csrf @method('PUT')
<label>Virksomhetens private API-nøkkel<input type="password" name="merchant_secret" autocomplete="new-password" placeholder="{{ $stripe['key_saved'] ? 'Lagret – la stå tomt for å beholde' : 'rk_live_…' }}"><small>En eksisterende sk_live-nøkkel støttes også. Ikke bruk pk_-nøkkelen, Stripe-passordet eller nøkkelen for DekkPilot-abonnementet. Nøkkelen lagres kryptert og vises ikke igjen.</small></label>
<details><summary>Hvis du allerede har opprettet betalingsvarsler manuelt</summary><label>Signeringshemmelighet<input type="password" name="merchant_webhook_secret" autocomplete="new-password" placeholder="whsec_…"></label><p>Webhook-adresse: <code>{{ route('merchant.stripe.webhook',$organization) }}</code>. Velg hendelsene checkout.session.completed, checkout.session.async_payment_succeeded og checkout.session.expired. La feltet stå tomt for automatisk oppsett eller for å beholde lagret verdi.</p></details>
<label class="check"><input type="checkbox" name="active" value="1" @checked($stripe['active'])> Aktiver Stripe for kundebetalinger</label><small>En testnøkkel kan kontrolleres og lagres uten aktivering. Reelle jobber kan bare markeres betalt av live-betalinger. Fjerner du avhukingen, stoppes nye betalinger; påbegynte betalinger avklares fortsatt.</small>
<button class="button">Kontroller og lagre Stripe</button></form>
</section>
<section class="panel" id="zettle"><div class="panel-head"><div><p class="eyebrow">KORTLESER I KASSEN</p><h2>Zettle / PayPal Point of Sale</h2></div><span class="status">{{ $zettle['active'] ? 'Aktiv' : 'Ikke aktiv' }}</span></div>
<ol><li><a href="https://www.zettle.com/no/betalingsloesninger/kortterminal" target="_blank" rel="noopener">Opprett konto og bestill kortleser hos PayPal Point of Sale</a> (tidligere iZettle/Zettle). Fullfør registrering og oppgjørsopplysninger hos leverandøren.</li><li>Installer leverandørens Point of Sale-app, logg inn der og koble til kortleseren. Følg leverandørens oppsett for din telefon eller nettbrett.</li><li>Gi betalingsstedet et navn nedenfor og aktiver. Du skal ikke legge inn Zettle-passord, Client ID eller API-nøkler for denne flyten.</li></ol>
<p><strong>Slik tar dere betalt:</strong> Velg Zettle på den ferdige jobben. Tast samme beløp i Zettle-appen, gjennomfør betalingen og kontroller at kvitteringen viser godkjent betaling. En innlogget ansatt med kassetilgang registrerer kvitteringsreferansen og bekrefter beløpet i DekkPilot. Kunden kan ikke bekrefte betalingen selv.</p>
<p>DekkPilot sender ikke beløpet automatisk til Zettle-leseren. Den eventuelle OAuth-koblingen under regnskap gir tilgang til salgsdata og er ikke en terminalintegrasjon.</p>
<form method="post" action="{{ route('admin.payments.zettle') }}" class="stack">@csrf @method('PUT')<label>Navn på betalingssted<input name="name" value="{{ $zettle['name']??'Zettle i kundemottaket' }}" maxlength="100" required></label><label class="check"><input type="checkbox" name="manual_confirmation" value="1" required> Jeg forstår at en ansatt må kontrollere godkjent betaling i Zettle før den registreres i DekkPilot.</label><label class="check"><input type="checkbox" name="active" value="1" @checked($zettle['active'])> Aktiver Zettle som betalingsmåte</label><button class="button">Lagre Zettle-oppsett</button></form></section>
<section class="panel" id="vipps"><div class="panel-head"><div><p class="eyebrow">MOBILBETALING</p><h2>Vipps ePayment</h2></div><span class="status">{{ $vipps['active'] ? 'Aktiv' : 'Ikke aktiv' }}</span></div>
<ol><li><a href="https://vippsmobilepay.com/nb-NO/advanced" target="_blank" rel="noopener">Bestill Vipps for bedrift</a> med ePayment/nettbetaling. En vanlig privat Vipps-konto er ikke nok.</li><li>Logg inn i <a href="https://portal.vippsmobilepay.com" target="_blank" rel="noopener">Vipps MobilePay-portalen</a>, velg virksomhet og riktig salgsenhet. Hent API-opplysningene. <a href="https://developer.vippsmobilepay.com/docs/knowledge-base/api-keys/" target="_blank" rel="noopener">Se leverandørens veiledning</a>.</li><li>Fyll inn de fire feltene nedenfor. Kontroller at alle opplysninger kommer fra samme salgsenhet og miljø.</li></ol>
<form method="post" action="{{ route('admin.accounting.vipps') }}" class="stack">@csrf @method('PUT')
<label>Client ID<input name="client_id" value="{{ $vipps['client_id']??'' }}"><small>Identifiserer API-tilkoblingen.</small></label>
<label>Client Secret<input type="password" name="client_secret" autocomplete="new-password" placeholder="{{ $vipps['secret_saved'] ? 'Lagret – la stå tomt for å beholde' : 'Client Secret' }}"><small>Hemmelig nøkkel fra samme salgsenhet.</small></label>
<label>Subscription Key<input type="password" name="subscription_key" autocomplete="new-password" placeholder="{{ $vipps['key_saved'] ? 'Lagret – la stå tomt for å beholde' : 'Ocp-Apim-Subscription-Key' }}"><small>API-nøkkelen fra Vipps. Dette er ikke abonnementet på DekkPilot.</small></label>
<label>Merchant Serial Number (MSN)<input name="msn" value="{{ $vipps['msn']??'' }}" inputmode="numeric" pattern="[0-9]{4,10}"><small>Nummeret til salgsenheten som skal motta betalingen.</small></label>
<label class="check"><input type="checkbox" name="test" value="1" @checked($vipps['test']??false)> Testmiljø – ikke bruk til reelle kundeoppgjør</label><label class="check"><input type="checkbox" name="active" value="1" @checked($vipps['active'])> Aktiver Vipps</label><button class="button">Lagre Vipps-oppsett</button></form></section>
<section class="panel" id="terminal"><h2>Annen bankterminal</h2><p>Har dere allerede en terminal, kontakt terminal- eller kasseleverandøren for avtale og integrasjon. Å lagre et navn her kobler ikke terminalen til DekkPilot. Aktiver først når leverandøren har satt opp og testet overføring av betalingsstatus til DekkPilots betalings-API.</p><form method="post" action="{{ route('admin.accounting.terminal') }}" class="stack">@csrf @method('PUT')<label>Navn som vises kunden<input name="name" value="{{ $terminal['name']??'Bankterminal i kassen' }}" required></label><label class="check"><input type="checkbox" name="active" value="1" @checked($terminal['active'])> Terminalintegrasjonen er klar – vis bankterminal</label><button class="button">Lagre terminaloppsett</button></form><p><a href="{{ route('admin.accounting') }}">Faktura via Fiken, Tripletex, PowerOffice eller Uni Micro settes opp under regnskap</a>.</p></section>
<section class="panel"><h2>Åpne kundens betalingsside</h2><p>Når en jobb er fullført, åpner dere betalingen fra timeboken. Dere kan også bruke denne portalen på kundeskjermen. Bare betalingsmåter som virksomheten har aktivert, vises.</p><a class="button" target="_blank" rel="noopener" href="{{ route('checkout.show',$organization) }}">Åpne utsjekkingsportalen</a><label>Portaladresse<input readonly value="{{ route('checkout.show',$organization) }}"></label></section>
</x-layouts.app>
