<x-layouts.app title="E-postoppsett · DekkPilot" heading="E-postoppsett">
<div class="admin-subnav"><a href="{{ route('admin') }}">← Administrasjon</a><a href="{{ route('admin.communications') }}">Meldinger og SMS-oppsett</a></div>
<div class="admin-subnav"><a href="{{ route('admin') }}">← Admin</a><a href="#avsender">Avsenderadresse</a>@if(auth()->user()->is_super_admin)<a href="{{ route('superadmin.server-mail') }}">Servermail</a><a href="#backup">Backup</a>@endif</div>

<section class="panel" id="avsender"><div class="panel-head"><div><p class="eyebrow">VIRKSOMHETENS E-POST</p><h2>Avsenderadresse</h2></div></div><p class="muted">Svar fra kundene sendes til denne e-postadressen.</p><form method="post" action="{{ route('admin.system.tenant-mail') }}" class="stack">@csrf @method('PUT')<label>E-post dere sender fra<input type="email" name="from_address" value="{{ old('from_address',$tenantMail['from_address']??auth()->user()->organization->email??'') }}" required placeholder="kundeservice@firma.no"><small>Avsendernavnet hentes automatisk fra virksomhetens navn.</small></label><button class="button">Lagre avsenderadresse</button></form></section>

<section class="panel"><div class="panel-head"><div><p class="eyebrow">LEVERINGSKONTROLL</p><h2>Send test-e-post</h2></div></div><p class="muted">Test-e-posten legges i samme kø som øvrige meldinger. Følg status under Administrasjon → Kommunikasjon. Utsending starter normalt innen ti minutter, men kan ta lenger tid ved kø.</p><form method="post" action="{{ route('admin.system.test-mail') }}" class="search">@csrf<input type="email" name="recipient" value="{{ old('recipient',auth()->user()->email) }}" required aria-label="Mottaker"><button class="button">Send test</button></form></section>

@if(auth()->user()->is_super_admin)
<section class="panel" id="backup"><div class="panel-head"><div><p class="eyebrow">KUN SUPERADMIN</p><h2>Databasebackup</h2></div><span class="status">{{ $backups->count() }} filer</span></div><p class="muted">Backup lagres privat i <code>storage/app/backups</code>, komprimeres og får filrettighet 0600. Nedlasting krever innlogget superadmin.</p><form method="post" action="{{ route('admin.system.backup') }}" class="search">@csrf<label>Behold i dager<input type="number" name="retention" min="1" max="365" value="14" required></label><button class="button">Ta backup nå</button></form><p class="fine">Databaseverktøy: <code>{{ $mysqldump }}</code>.</p><div class="table-wrap"><table><thead><tr><th>Opprettet</th><th>Fil</th><th>Størrelse</th><th></th></tr></thead><tbody>@forelse($backups as $backup)<tr><td>{{ date('d.m.Y H:i',$backup['created_at']) }}</td><td><code>{{ $backup['name'] }}</code></td><td>{{ number_format($backup['size']/1024/1024,2,',',' ') }} MB</td><td><a class="button ghost" href="{{ route('admin.system.backup.download',$backup['name']) }}">Last ned</a></td></tr>@empty<tr><td colspan="4" class="empty">Ingen lokale backupfiler er funnet.</td></tr>@endforelse</tbody></table></div><details open><summary>Automatisk backup med cron</summary><div class="notice"><p>Bruk én cronjobb hvert tiende minutt. Systemet håndterer tidspunkt for backup og øvrige oppgaver:</p><pre>*/10 * * * * /sti/til/php /full/sti/til/system/artisan system:cron &gt;&gt; /dev/null 2&gt;&amp;1</pre><p>Kontroller neste dag at en ny fil vises her, og oppbevar jevnlig en sikker kopi et annet sted.</p></div></details></section>
@endif
</x-layouts.app>
