<x-layouts.app title="System og backup · DekkPilot" heading="E-post og backup">
<div class="admin-subnav"><a href="{{ route('admin') }}">← Admin</a><a href="#avsender">Virksomhetens avsender</a>@if(auth()->user()->is_super_admin)<a href="#servermail">Servermail</a><a href="#backup">Backup</a>@endif</div>

<section class="panel" id="avsender"><div class="panel-head"><div><p class="eyebrow">VIRKSOMHETENS E-POST</p><h2>Dette ser kundene</h2></div></div><p class="muted">Alle kunde-e-poster sendes med dette navnet og denne adressen. Svaradresse kan være en annen innboks. Serverens transport og system-e-poster styres separat av superadmin.</p><form method="post" action="{{ route('admin.system.tenant-mail') }}" class="stack">@csrf @method('PUT')<div class="fields"><label>Avsendernavn<input name="from_name" value="{{ old('from_name',$tenantMail['from_name']??auth()->user()->organization->name??'DekkPilot') }}" required maxlength="255" placeholder="Mitt Dekkhotell AS"></label><label>Avsenderadresse<input type="email" name="from_address" value="{{ old('from_address',$tenantMail['from_address']??auth()->user()->organization->email??'') }}" required placeholder="timebestilling@firma.no"><small>Må være tillatt av serverens e-postleverandør.</small></label></div><label>Svar til<input type="email" name="reply_to" value="{{ old('reply_to',$tenantMail['reply_to']??auth()->user()->organization->email??'') }}" required placeholder="kundeservice@firma.no"></label><button class="button">Lagre kundeavsender</button></form></section>

<section class="panel"><div class="panel-head"><div><p class="eyebrow">LEVERINGSKONTROLL</p><h2>Send test-e-post</h2></div></div><p class="muted">Testen bruker både serverinnstillingene og virksomhetens avsender ovenfor. Demo/testmiljø kan aldri sende.</p><form method="post" action="{{ route('admin.system.test-mail') }}" class="search">@csrf<input type="email" name="recipient" value="{{ old('recipient',auth()->user()->email) }}" required aria-label="Mottaker"><button class="button">Send test</button></form></section>

@if(auth()->user()->is_super_admin)
<section class="panel integration-card" id="servermail"><div class="panel-head"><div><p class="eyebrow">KUN SUPERADMIN</p><h2>Serverens e-posttransport</h2></div><span class="status {{ ($serverMail['transport']??'log')==='log'?'cancelled':'completed' }}">{{ strtoupper($serverMail['transport']??'log') }}</span></div><p class="muted">Denne innstillingen gjelder system-e-poster som glemt passord og er grunntransport for alle virksomheter. Hemmelighetene krypteres med APP_KEY og vises aldri igjen.</p><form method="post" action="{{ route('admin.system.server-mail') }}" class="stack">@csrf @method('PUT')<label>Sendemåte<select name="transport" data-mail-transport><option value="smtp" @selected(($serverMail['transport']??'')==='smtp')>SMTP med innlogging</option><option value="sendmail" @selected(($serverMail['transport']??'')==='sendmail')>Lokal servermail / sendmail (anbefalt på Domeneshop-webhotell)</option><option value="log" @selected(($serverMail['transport']??'log')==='log')>Kun logg – send ingenting</option></select></label><div class="fields"><label>SMTP-server<input name="host" value="{{ old('host',$serverMail['host']??'smtp.domeneshop.no') }}" placeholder="smtp.domeneshop.no"></label><label>Port<input type="number" name="port" min="1" max="65535" value="{{ old('port',$serverMail['port']??587) }}"></label><label>Kryptering<select name="security"><option value="tls" @selected(($serverMail['security']??'tls')==='tls')>STARTTLS / TLS (port 587)</option><option value="ssl" @selected(($serverMail['security']??'')==='ssl')>SSL/TLS (port 465)</option></select></label><label>SMTP-brukernavn<input name="username" value="{{ old('username',$serverMail['username']??'') }}" autocomplete="off"><small>Hos Domeneshop er brukernavn ikke nødvendigvis e-postadressen.</small></label></div><label>SMTP-passord<input type="password" name="password" autocomplete="new-password" placeholder="La stå tomt for å beholde lagret passord"></label><div class="fields"><label>Systemets avsenderadresse<input type="email" name="from_address" value="{{ old('from_address',$serverMail['from_address']??'') }}" required></label><label>Systemets avsendernavn<input name="from_name" value="{{ old('from_name',$serverMail['from_name']??'DekkPilot') }}" required></label><label>Maks meldinger per minutt<input type="number" name="messages_per_minute" min="1" max="600" value="{{ old('messages_per_minute',$serverMail['messages_per_minute']??60) }}" required><small>Domeneshop-webhotell: bruk 60 eller lavere.</small></label></div><button class="button">Lagre serverinnstillinger sikkert</button></form>
<details><summary>Domeneshop: hvilket valg skal jeg bruke?</summary><div class="notice"><p><strong>Vanlige systemmeldinger:</strong> SMTP kan bruke <code>smtp.domeneshop.no</code>, port 587, STARTTLS og autentisering. Port 465 med SSL støttes også.</p><p><strong>Masseutsending på Domeneshop-webhotell:</strong> Domeneshop sier at lokal e-posttjener skal brukes, ikke smtp.domeneshop.no. Velg «Lokal servermail». Avsender må tilhøre webhotellet. Maksimalt tempo er 1 melding/sekund, 60/minutt, 1 500/time og 5 000/døgn. Ved større volum bør spesialisert leverandør brukes.</p></div></details></section>

<section class="panel" id="backup"><div class="panel-head"><div><p class="eyebrow">KUN SUPERADMIN</p><h2>Databasebackup</h2></div><span class="status">{{ $backups->count() }} filer</span></div><p class="muted">Backup lagres privat i <code>storage/app/backups</code>, komprimeres og får filrettighet 0600. Nedlasting krever innlogget superadmin. Backup inneholder persondata og skal lagres kryptert og tilgangsbegrenset.</p><form method="post" action="{{ route('admin.system.backup') }}" class="search">@csrf<label>Behold i dager<input type="number" name="retention" min="1" max="365" value="14" required></label><button class="button">Ta backup nå</button></form><p class="fine">Databaseverktøy: <code>{{ $mysqldump }}</code>. Hvis backup feiler, må hostingen oppgi korrekt sti til <code>mysqldump</code> som <code>DB_DUMP_BINARY</code>.</p><div class="table-wrap"><table><thead><tr><th>Opprettet</th><th>Fil</th><th>Størrelse</th><th></th></tr></thead><tbody>@forelse($backups as $backup)<tr><td>{{ date('d.m.Y H:i',$backup['created_at']) }}</td><td><code>{{ $backup['name'] }}</code></td><td>{{ number_format($backup['size']/1024/1024,2,',',' ') }} MB</td><td><a class="button ghost" href="{{ route('admin.system.backup.download',$backup['name']) }}">Last ned</a></td></tr>@empty<tr><td colspan="4" class="empty">Ingen lokale backupfiler er funnet.</td></tr>@endforelse</tbody></table></div><details open><summary>Automatisk backup med cron</summary><div class="notice"><p>Laravel-planleggeren har allerede daglig backup kl. 03:15. Cron skal kjøre scheduler hvert minutt fra systemmappen:</p><pre>* * * * * /sti/til/php /full/sti/til/system/artisan schedule:run &gt;&gt; /dev/null 2&gt;&amp;1</pre><p>På Domeneshop fyller du inn den faktiske PHP- og prosjektstien fra kontrollpanelet. Alternativt kan bare backup kjøres direkte én gang per døgn:</p><pre>15 3 * * * /sti/til/php /full/sti/til/system/artisan backup:database --retention=14 &gt;&gt; /dev/null 2&gt;&amp;1</pre><p>Kontroller neste dag at en ny fil vises her, og last jevnlig ned en kopi til et annet sikkert lagringssted.</p></div></details></section>
@endif
</x-layouts.app>
