<x-layouts.app title="Lageroppsett · DekkPilot" heading="Bygg lageret">
<link rel="stylesheet" href="{{ asset('warehouse-map.css') }}?v=20260810-2">
<link rel="stylesheet" href="{{ asset('warehouse-shelves.css') }}?v=20260810-1">
<link rel="stylesheet" href="{{ asset('warehouse-floorplan.css') }}?v=20260810-1">
<section class="warehouse-hero panel"><div><p class="eyebrow">VISUELL LAGERSTYRING</p><h2>Bygg lageret slik det faktisk ser ut</h2><p>Opprett reoler og velg bare hvor mange hyller de har, og hvor mange hjulsett hver hylle rommer. DekkPilot bygger kartet automatisk.</p><div class="hero-actions"><a class="button" href="{{ route('warehouse.map') }}">Åpne teknikerkart →</a><a class="button ghost" href="#ny-reol">Legg til reol</a></div></div><img src="{{ asset('images/warehouse-map-hero.png') }}" alt="Illustrasjon av et organisert hjulhotell med reoler og digitale henteruter"></section>
<section class="stats warehouse-stats"><article><span class="stat-icon green">▦</span><div><small>REOLER/PLASSER</small><strong>{{ $stats['locations'] }}</strong></div></article><article><span class="stat-icon blue">◎</span><div><small>KAPASITET</small><strong>{{ $stats['capacity'] }}</strong></div></article><article><span class="stat-icon violet">●</span><div><small>I BRUK</small><strong>{{ $stats['occupied'] }}</strong></div></article><article><span class="stat-icon orange">!</span><div><small>UTEN PLASS</small><strong>{{ $stats['unplaced'] }}</strong></div></article></section>

<section class="panel"><div class="panel-head"><div><p class="eyebrow">LAGERKART SETT OVENFRA</p><h2>Plasser reolene slik de står</h2><p>Dra en reol til riktig sted. Posisjonen lagres automatisk.</p></div><div class="map-legend"><span><i class="free"></i>Ledig</span><span><i class="busy"></i>Nesten full</span><span><i class="full"></i>Full</span></div></div><div class="warehouse-canvas warehouse-floorplan" data-warehouse-floor data-move-url="{{ route('admin.warehouse.move') }}">@forelse($locations->where('active',true) as $location)@php
    $available = max(0, $location->capacity - $location->tire_sets_count);
    $usage = $location->capacity > 0 ? $location->tire_sets_count / $location->capacity : 0;
@endphp<article class="floor-rack {{ $usage>=1?'full':($usage>=.75?'busy':'free') }}" data-floor-rack data-location-id="{{ $location->id }}" style="--x:{{ $location->map_x??3 }};--y:{{ $location->map_y??5 }}" tabindex="0"><span class="floor-rack-grip" aria-hidden="true">⠿</span><small>{{ $location->zone }}</small><strong>{{ $location->code }}</strong><b>{{ $location->tire_sets_count }}/{{ $location->capacity }} i bruk</b><span>{{ $available }} ledige</span><a href="#location-{{ $location->id }}">Rediger reol</a></article>@empty<div class="map-empty"><strong>Ingen reoler ennå</strong><span>Legg til den første reolen nedenfor.</span></div>@endforelse</div><p class="rack-sort-status" data-floor-status aria-live="polite">Dra reolene rundt på kartet. Endringer lagres automatisk.</p></section>

<section class="warehouse-admin-grid"><article class="panel"><div class="panel-head"><div><p class="eyebrow">OPPSETT</p><h2>Rediger reoler</h2></div><span class="status">{{ $locations->count() }}</span></div><div class="location-editor-list">@forelse($locations as $location)<details id="location-{{ $location->id }}" class="location-editor"><summary><span><strong>{{ $location->code }}</strong><small>{{ $location->label ?: $location->zone }} · {{ $location->shelf_count }} hyller · {{ $location->sets_per_shelf }} sett per hylle</small></span><span class="status {{ $location->active?'completed':'cancelled' }}">{{ $location->active?'Aktiv':'Inaktiv' }}</span></summary><form method="post" action="{{ route('admin.warehouse.update',$location) }}" class="warehouse-location-form">@csrf @method('PUT')<div class="fields"><label>Kode<input name="code" value="{{ $location->code }}" required></label><label>Navn<input name="label" value="{{ $location->label }}"></label></div><div class="fields"><label>Sone<input name="zone" value="{{ $location->zone }}" required></label><label>Type<select name="location_type">@foreach(['rack'=>'Reol','floor'=>'Gulvplass','receiving'=>'Mottak','staging'=>'Klargjøring','workshop'=>'Verksted'] as $value=>$label)<option value="{{ $value }}" @selected(($location->location_type??'rack')===$value)>{{ $label }}</option>@endforeach</select></label></div><div class="shelf-settings"><label>Hyller i høyden<input type="number" name="shelf_count" min="1" max="20" value="{{ $location->shelf_count }}" required></label><label>Hjulsett per hylle<input type="number" name="sets_per_shelf" min="1" max="50" value="{{ $location->sets_per_shelf }}" required></label><label>Plukkefølge<input type="number" name="pick_order" min="0" max="9999" value="{{ $location->pick_order??0 }}"></label></div><input type="hidden" name="aisle" value="{{ $location->aisle }}"><input type="hidden" name="rack" value="{{ $location->rack }}"><p class="capacity-preview">Kapasitet: <strong>{{ $location->shelf_count*$location->sets_per_shelf }} hjulsett</strong></p><button class="button">Lagre reol</button></form><form method="post" action="{{ route('admin.warehouse.toggle',$location) }}">@csrf @method('PATCH')<button class="button ghost">{{ $location->active?'Deaktiver':'Aktiver' }}</button></form></details>@empty<div class="empty-state"><strong>Ingen lagerplasser ennå</strong></div>@endforelse</div></article>
<aside id="ny-reol" class="panel warehouse-create"><p class="eyebrow">NY REOL</p><h2>Hvor stor er reolen?</h2><p class="muted">Det er alt vi trenger. Kart og kapasitet beregnes automatisk.</p><form method="post" action="{{ route('admin.warehouse.store') }}" class="stack">@csrf<div class="fields"><label>Kode<input name="code" value="{{ old('code') }}" placeholder="A-01" required></label><label>Navn<input name="label" value="{{ old('label') }}" placeholder="Reol ved port"></label></div><div class="fields"><label>Sone<input name="zone" value="{{ old('zone','Sone A') }}" required></label><label>Type<select name="location_type"><option value="rack">Reol</option><option value="floor">Gulvplass</option><option value="receiving">Mottak</option><option value="staging">Klargjøring</option><option value="workshop">Verksted</option></select></label></div><div class="shelf-settings"><label>Hyller i høyden<input type="number" name="shelf_count" min="1" max="20" value="5" required></label><label>Hjulsett per hylle<input type="number" name="sets_per_shelf" min="1" max="50" value="4" required></label><label>Plukkefølge<input type="number" name="pick_order" min="0" max="9999" value="0"></label></div><input type="hidden" name="aisle"><input type="hidden" name="rack"><button class="button full">＋ Legg til reol</button></form></aside></section>
<script src="{{ asset('warehouse-map.js') }}?v=20260810-4" defer></script>
</x-layouts.app>
