<x-layouts.app title="Hjulhotell · DekkPilot" heading="Hjulhotell">
<link rel="stylesheet" href="{{ in_array(request()->getHost(),['localhost','127.0.0.1','::1'],true) ? route('system.asset',['filename'=>'tire-intake.css']) : asset('tire-intake.css') }}?v=20260812-2">
<link rel="stylesheet" href="{{ in_array(request()->getHost(),['localhost','127.0.0.1','::1'],true) ? route('system.asset',['filename'=>'inventory-actions.css']) : asset('inventory-actions.css') }}?v=20260812-3">
@unless($labelsEnabled)<style>[data-label-preview],[data-label-id]{display:none!important}</style>@endunless
<section class="stats inventory-stats">
    <a href="{{ route('inventory',['status'=>'stored']) }}"><span class="stat-icon green">▦</span><div><small>PÅ LAGER</small><strong>{{ $inventoryStats['stored'] }}</strong></div><b>→</b></a>
    <a href="{{ route('inventory',['status'=>'received']) }}"><span class="stat-icon orange">⇣</span><div><small>I MOTTAK</small><strong>{{ $inventoryStats['received'] }}</strong></div><b>→</b></a>
    <a href="{{ route('inventory',['status'=>'received']) }}"><span class="stat-icon blue">⌖</span><div><small>UTEN PLASS</small><strong>{{ $inventoryStats['unplaced'] }}</strong></div><b>→</b></a>
    <a href="{{ route('inventory',['condition'=>'attention','sort'=>'tread_low']) }}"><span class="stat-icon violet">!</span><div><small>TRENGER TILSYN</small><strong>{{ $inventoryStats['attention'] }}</strong></div><b>→</b></a>
</section>
@if($labelsEnabled&&session('label_url'))<div class="flash">✓ Hjulsettet er lagret. <button class="button" type="button" data-label-preview="{{ session('label_url') }}">Forhåndsvis 4 etiketter</button></div>@endif
<section class="inventory-workspace">
<article class="panel">
    <div class="panel-head"><div><p class="eyebrow">LAGEROVERSIKT</p><h2>{{ $sets->total() }} hjulsett</h2></div><div class="inventory-primary-actions"><a class="button ghost" href="{{ route('warehouse.map') }}">⌖ Åpne lagerkart</a>@if($labelsEnabled)<button class="button ghost" type="button" data-print-selected data-label-base="{{ route('tire-sets.labels') }}" disabled>▤ Skriv valgte etiketter</button>@endif<button class="button" type="button" data-intake-open>＋ Registrer hjulsett</button></div></div>
    <form class="filterbar inventory-search" id="inventory-filter" method="get"><label class="search-field">Søk<input name="q" value="{{ request('q') }}" placeholder="Navn, registreringsnummer eller hjulkode"></label><input type="hidden" name="sort" value="{{ request('sort','newest') }}"><button class="button">Søk</button><a class="reset" href="{{ route('inventory') }}">Nullstill alt</a></form>
    @php
      $sortUrl=fn(string $value)=>route('inventory',array_filter([...request()->query(),'sort'=>$value,'page'=>null],fn($v)=>$v!==null&&$v!==''));
      $nextRegistration=request('sort')==='registration_asc'?'registration_desc':'registration_asc'; $nextTread=request('sort')==='tread_low'?'tread_high':'tread_low'; $nextLocation=request('sort')==='location_asc'?'location_desc':'location_asc'; $nextStatus=request('sort')==='status_asc'?'status_desc':'status_asc';
    @endphp
    <div class="table-wrap"><table><thead><tr><th><input type="checkbox" data-select-all aria-label="Velg alle"></th>
      <th><a class="sortable-head" href="{{ $sortUrl($nextRegistration) }}">Identitet <span>{{ str_starts_with(request('sort',''),'registration_')?(request('sort')==='registration_asc'?'↑':'↓'):'↕' }}</span></a></th>
      <th><a class="sortable-head" href="{{ $sortUrl($nextTread) }}">Hjul og kontroll <span>{{ in_array(request('sort'),['tread_low','tread_high'])?(request('sort')==='tread_low'?'↑':'↓'):'↕' }}</span></a></th>
      <th><a class="sortable-head" href="{{ $sortUrl($nextLocation) }}">Plass <span>{{ str_starts_with(request('sort',''),'location_')?(request('sort')==='location_asc'?'↑':'↓'):'↕' }}</span></a></th>
      <th><a class="sortable-head" href="{{ $sortUrl($nextStatus) }}">Status og handling <span>{{ str_starts_with(request('sort',''),'status_')?(request('sort')==='status_asc'?'↑':'↓'):'↕' }}</span></a></th></tr></thead><tbody>
    @forelse($sets as $set)@php($needsAttention=($set->minimum_tread_depth!==null&&$set->minimum_tread_depth<3)||($set->dot_year!==null&&$set->dot_year<=now()->year-8))<tr>
        <td><input type="checkbox" value="{{ $set->id }}" data-label-id aria-label="Velg {{ $set->code }}"></td>
        <td><strong class="plate-inline">{{ $set->vehicle->registration_number }}</strong><small>{{ $set->vehicle->customer->name }}</small><small>{{ $set->code }} · {{ ['received'=>'Mottatt','stored'=>'På lager','picked'=>'Plukket','workshop'=>'Verksted','delivered'=>'Utlevert'][$set->status] }}</small></td>
        <td>{{ $set->manufacturer }} {{ $set->size }}<small>{{ $set->season === 'winter' ? '❄ Vinter' : ($set->season==='summer'?'☀ Sommer':'Helår') }} · {{ $set->quantity }} stk · DOT {{ $set->dot_year ?: 'ukjent' }}</small><span class="status {{ $needsAttention?'cancelled':'completed' }}"><i class="condition-dot {{ $needsAttention?'bad':'good' }}"></i>{{ $set->minimum_tread_depth ? $set->minimum_tread_depth.' mm' : 'Ikke målt' }}</span></td>
        <td><strong>{{ $set->storageLocation?->code ?? 'MOTTAK' }}</strong>@if($set->storage_shelf_number)<small>Hylle {{ $set->storage_shelf_number }}</small>@elseif(!$set->storage_location_id)<small class="attention-text">Må tildeles plass</small>@endif</td>
        <td><div class="row-actions"><span class="row-current-status">{{ ['received'=>'Mottatt','stored'=>'På lager','picked'=>'Hentet frem','workshop'=>'På verksted','delivered'=>'Utlevert'][$set->status] }}</span><details class="row-action-menu"><summary>Handlinger <span aria-hidden="true">•••</span></summary><div class="row-action-menu-content"><div class="row-action-links"><a class="mini-action" href="{{ route('tire-sets.inspection',$set) }}"><span>✓</span> Kontroller hjul</a><button class="mini-action" type="button" data-label-preview="{{ route('tire-sets.labels',['ids'=>$set->id]) }}"><span>▤</span> Vis etikett</button></div><form class="row-status-form" method="post" action="{{ route('tire-sets.status',$set) }}">@csrf @method('PATCH')<label><span>Flytt hjulsettet til</span><select name="status" aria-label="Flytt hjulsettet til status"><option value="received" @selected($set->status==='received')>Mottatt</option><option value="stored" @selected($set->status==='stored')>På lager</option><option value="picked" @selected($set->status==='picked')>Hentet frem</option><option value="workshop" @selected($set->status==='workshop')>På verksted</option><option value="delivered" @selected($set->status==='delivered')>Utlevert</option></select></label><button type="submit">Lagre status</button></form></div></details></div></td>
    </tr>@empty<tr><td colspan="5" class="empty">Ingen hjulsett matcher filtrene.</td></tr>@endforelse
    </tbody></table></div>{{ $sets->links() }}
</article>
<aside><article class="panel"><p class="eyebrow">MOTTAK</p><h2>Registrer og merk hjulsett</h2><p class="muted">Kontroller hjulene mens kunden er til stede. Etiketten er klar straks settet lagres.</p><form method="post" action="{{ route('tire-sets.store') }}" class="stack" data-intake-form data-customer-search-url="{{ route('bookings.customer-search') }}">@csrf
    <div class="intake-customer-picker" data-intake-customer-picker><label>Finn kunde eller bil<input type="search" placeholder="Skriv navn eller registreringsnummer" autocomplete="off" data-intake-customer-search></label><p class="muted" data-intake-search-status>Skriv minst to tegn, og velg riktig bil.</p><div class="intake-search-results" data-intake-search-results></div><div class="intake-selected-vehicle" data-intake-selected hidden><span><small>VALGT KJØRETØY</small><strong data-intake-selected-registration></strong><em data-intake-selected-customer></em></span><button type="button" class="button ghost" data-intake-change>Bytt</button></div><input type="hidden" name="vehicle_id" value="{{ old('vehicle_id') }}" required data-intake-vehicle-id><p class="field-error" data-intake-vehicle-error></p></div>
    <div class="fields"><label>Sesong<select name="season" data-intake-season><option value="summer">Sommer</option><option value="winter">Vinter</option><option value="all_season">Helår</option></select></label><label>Type<select name="kind"><option value="complete_wheels">Komplette hjul</option><option value="tires">Løse dekk</option><option value="rims">Felger</option></select></label></div><div class="fields"><label>Produsent<input name="manufacturer"></label><label>Dimensjon<input name="size" placeholder="205/55 R16"></label></div>
    <fieldset class="tire-intake-measurements" data-tire-measurements><legend>Mål alle fire dekk</legend><p>Mål i hovedsporet. Bilen vises med fronten opp.</p><div class="car-measurement-map"><svg class="car-top-view" viewBox="0 0 180 360" role="img" aria-label="Bil sett ovenfra med fronten opp"><path class="car-shadow" d="M40 52Q45 18 90 12q45 6 50 40l14 58v180l-14 50H40l-14-50V110z"/><path class="car-body" d="M48 55Q52 28 90 22q38 6 42 33l12 60-8 165 8 45H36l8-45-8-165z"/><path class="car-glass" d="m57 72 12-30h42l12 30 7 48H50zM50 239h80l-9 66H59z"/><path class="car-line" d="M48 132h84M48 226h84M90 132v94"/><path class="car-light" d="M52 48h18M110 48h18"/></svg>@foreach(['front_left'=>'Venstre foran','front_right'=>'Høyre foran','rear_left'=>'Venstre bak','rear_right'=>'Høyre bak'] as $position=>$label)<label class="wheel-measure wheel-{{ str_replace('_','-',$position) }}"><span>{{ $label }}</span><span class="measurement-input"><input name="wheels[{{ $loop->index }}][tread_depth_mm]" value="{{ old('wheels.'.$loop->index.'.tread_depth_mm') }}" type="number" inputmode="decimal" step="0.1" min="0" max="20" placeholder="–" required data-wheel-depth><b>mm</b></span><input type="hidden" name="wheels[{{ $loop->index }}][position]" value="{{ $position }}"></label>@endforeach</div><div class="measurement-summary" data-measurement-summary><span>Laveste måling</span><strong data-lowest-depth>Fyll inn fire mål</strong><small data-depth-advice>Alle fire dekk må måles før hjulsettet kan lagres.</small></div></fieldset>
    <div class="fields"><label>DOT-år<input name="dot_year" type="number" min="1990" max="2100" placeholder="F.eks. 2023"></label><label>Lagerplass<select name="storage_location_id"><option value="">Mottak – plasser senere</option>@foreach($locations as $location)<option value="{{ $location->id }}" @disabled($location->tire_sets_count >= $location->capacity)>{{ $location->code }} · {{ $location->tire_sets_count }}/{{ $location->capacity }}{{ $location->tire_sets_count >= $location->capacity ? ' FULL' : '' }}</option>@endforeach</select></label></div><button class="button full">Registrer kontrollert hjulsett</button>
</form></article><article class="panel location-capacity"><p class="eyebrow">PLASSKAPASITET</p><h2>Finn ledig plass</h2>@foreach($locations->take(8) as $location)@php($percent=min(100,round(($location->tire_sets_count/max(1,$location->capacity))*100)))<div><span><b>{{ $location->code }}</b><small>{{ $location->tire_sets_count }}/{{ $location->capacity }}</small></span><progress value="{{ $percent }}" max="100"></progress></div>@endforeach</article></aside>
</section>
@if($labelsEnabled)<dialog class="label-modal" data-label-modal><div class="label-modal-head"><div><p class="eyebrow">UTSKRIFTSKLAR</p><h2>Forhåndsvis 4 etiketter</h2></div><button type="button" data-label-close aria-label="Lukk">×</button></div><div class="label-modal-info"><span>Format <strong>100 × 50 mm</strong></span><span>Antall <strong>4 per hjulsett</strong></span></div><div class="label-frame-wrap"><iframe title="Forhåndsvisning av hjuletiketter" data-label-frame></iframe></div><div class="label-modal-actions"><button class="button ghost" type="button" data-label-close>Avbryt</button><button class="button" type="button" data-label-print>▤ Skriv ut 4 etiketter</button></div></dialog>@endif
<script defer src="{{ in_array(request()->getHost(),['localhost','127.0.0.1','::1'],true) ? route('system.asset',['filename'=>'inventory.js']) : asset('inventory.js') }}?v=20260812-2"></script>
</x-layouts.app>
