@php
$labelSettings=$labelSettings??\App\Services\LabelSettings::defaults();
[$labelWidth,$labelHeight]=\App\Services\LabelSettings::SIZES[$labelSettings['size']];
$scale=(int)$labelSettings['text_scale']/100;
@endphp
<!doctype html><html lang="nb"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Hjuletiketter · DekkPilot</title><style>
*{box-sizing:border-box}body{margin:0;background:#eef1ef;color:#111;font-family:Arial,sans-serif}.toolbar{position:sticky;top:0;background:#14241d;color:white;padding:12px 18px;display:flex;align-items:center;justify-content:space-between;z-index:2}.toolbar p{margin:0}.toolbar button{border:0;border-radius:9px;background:#38c97c;color:#092c1b;padding:10px 18px;font-weight:800;cursor:pointer}.labels{display:grid;gap:14px;justify-content:center;padding:20px}.label{width:100mm;height:50mm;background:#fff;border:1px dashed #777;padding:5mm;display:grid;grid-template-columns:1fr 29mm;gap:4mm;overflow:hidden;page-break-after:always}.label:last-child{page-break-after:auto}.label-main{min-width:0}.brand{font-size:10px;font-weight:bold;letter-spacing:1px}.registration{font-size:28px;font-weight:900;letter-spacing:2px;line-height:1;margin:5px 0}.customer{font-size:13px;font-weight:bold;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.details{font-size:10px;margin-top:6px;display:grid;grid-template-columns:1fr 1fr;gap:2px 8px}.details b{display:block;font-size:8px;text-transform:uppercase;color:#555}.label-side{border-left:1px solid #bbb;padding-left:4mm;display:flex;flex-direction:column;justify-content:space-between;align-items:center}.label-side>div:first-child{align-self:stretch}.location{font-size:18px;font-weight:900;overflow-wrap:anywhere}.code{text-align:center;font-size:9px;font-weight:bold;letter-spacing:1px}.qr-code{display:block;width:19mm;height:19mm;object-fit:contain;image-rendering:pixelated}@media print{body{background:#fff}.toolbar{display:none}.labels{display:block;padding:0}.label{border:0;margin:0}@page{size:100mm 50mm;margin:0}}@media(max-width:500px){.label{transform:scale(.85);transform-origin:top center;margin-bottom:-25px}}
.label{width:{{ $labelWidth }}mm;height:{{ $labelHeight }}mm}.registration{font-size:{{ 28*$scale }}px}.location{font-size:{{ 18*$scale }}px}.label-side>div>small{font-size:{{ 10*$scale }}px}
.label-location,.label-simple{grid-template-columns:minmax(0,1fr) 25mm;padding:4mm;gap:3mm}.label-location .registration,.label-simple .registration{font-size:{{ 32*$scale }}px;letter-spacing:0;overflow-wrap:anywhere}.label-location .location,.label-simple .location{font-size:{{ 22*$scale }}px}.label-location .details,.label-simple .details,.label-simple .customer,.label-simple .brand{display:none}.large-placement{font-size:{{ 16*$scale }}px;line-height:1.1;font-weight:900;margin-top:3mm;overflow-wrap:anywhere}.label-simple .label-side>div:first-child,.label-location .label-side>div:first-child{display:none}.label-no-qr.label-location,.label-no-qr.label-simple{grid-template-columns:minmax(0,1fr)}.label-no-qr.label-location .label-side,.label-no-qr.label-simple .label-side{border:0;padding:0;align-items:flex-start}.label-standard .large-placement{display:none}
@media print{@page{size:{{ $labelWidth }}mm {{ $labelHeight }}mm;margin:0}}
</style><script defer src="{{ route('system.asset.query',['filename'=>'label-print.js']) }}"></script></head><body>@unless(request()->boolean('embed'))<div class="toolbar"><p><strong>{{ $sets->count() }} etiketter</strong> · én etikett per hjulsett · velg {{ $labelWidth }} × {{ $labelHeight }} mm{{ ($isPreview??false)?' · PRØVEETIKETT':'' }}</p><button type="button" data-print-labels>Skriv ut etiketter</button></div>@endunless<main class="labels">
@foreach($sets as $set)<article class="label label-{{ $labelSettings['template'] }} {{ $labelSettings['show_qr']?'':'label-no-qr' }}"><section class="label-main"><div class="brand">DEKKPILOT · HJULHOTELL</div><div class="registration">{{ $set->vehicle->registration_number }}</div><div class="large-placement">{{ $set->storageLocation?->code ?? 'MOTTAK' }}<br>Lengde {{ $set->storage_position_number??'—' }} · Høyde {{ $set->storage_shelf_number??'—' }}</div><div class="customer">{{ $set->vehicle->customer->name }}</div><div class="details"><span><b>Hjul</b>{{ $set->manufacturer ?: 'Ukjent' }} {{ $set->size }}</span><span><b>Sesong/type</b>{{ $set->season==='winter'?'Vinter':($set->season==='summer'?'Sommer':'Helår') }} · {{ $set->quantity }} stk</span><span><b>Kontroll</b>{{ $set->minimum_tread_depth ? $set->minimum_tread_depth.' mm' : 'Ikke målt' }} · DOT {{ $set->dot_year ?: '—' }}</span><span><b>Mottatt</b>{{ $set->received_at?->format('d.m.Y') }}</span></div></section><aside class="label-side"><div><small>PLASS</small><div class="location">{{ $set->storageLocation?->code ?? 'MOTTAK' }}</div><small>Lengde {{ $set->storage_position_number??'—' }} · Høyde {{ $set->storage_shelf_number??'—' }}</small></div>@if($labelSettings['show_qr'])<img class="qr-code" src="{{ $qrCodes->get($set->id) }}" alt="QR-kode for {{ $set->code }}">@endif<div class="code">{{ $set->code }}</div></aside></article>@endforeach
</main></body></html>
