<x-layouts.app title="Git-oppdatering · DekkPilot" heading="Hent programoppdatering">
<link rel="stylesheet" href="{{ asset('git-update.css') }}?v=20260812-1">
@php($status=session('git_status',session('git_error',$gitStatus)))
<div class="admin-subnav"><a href="{{ route('superadmin') }}">← Superadmin</a><a href="{{ route('superadmin.system-update') }}">Databaseoppdatering</a></div>
<section class="panel"><div class="panel-head"><div><p class="eyebrow">SIKKER GITHUB-OPPDATERING</p><h2>{{ ($status['available']??false) ? (($status['behind']??0)>0 ? ($status['behind'].' nye commits er tilgjengelige') : 'Kontroller GitHub for endringer') : 'Git er ikke klart' }}</h2><p class="muted">Velg filene som skal hentes. Servermiljø, databasekobling, lagringsdata og andre beskyttede filer ignoreres automatisk.</p></div>@if($status['available']??false)<span class="status {{ ($status['behind']??0)>0?'in_progress':'completed' }}">{{ ($status['behind']??0)>0?'Oppdatering klar':'Status lokal' }}</span>@endif</div>
@if(!($status['available']??false))<div class="notice warning"><strong>GitHub er ikke koblet til ennå</strong><p>{{ $status['error']??'Ukjent feil' }}</p><p>Kontrollert mappe: <code>{{ $status['path']??'' }}</code></p></div>
<div class="setup-card"><p class="eyebrow">FØRSTEGANGSOPPSETT</p><h3>Koble servermappen til GitHub</h3><p class="muted">Dette oppretter kun Git-metadata og sammenligner eksisterende filer med GitHub. Ingen programfiler overskrives i dette steget.</p><form method="post" action="{{ route('superadmin.git-update.connect') }}" class="stack">@csrf<label>GitHub repository-adresse<input type="text" name="repository_url" value="{{ old('repository_url') }}" placeholder="https://github.com/brukernavn/dekkpilot.git" required autocomplete="off"><small>HTTPS- og SSH-adresser fra GitHub støttes. Ikke lim inn token eller passord.</small></label><label>Gren<input name="branch" value="{{ old('branch','main') }}" required pattern="[A-Za-z0-9._/-]+"></label><label class="check"><input type="checkbox" name="confirmation" value="1" required> Jeg bekrefter at denne servermappen skal kobles til repositoryet</label><button class="button">Koble til GitHub uten å overskrive filer</button></form><div class="notice"><strong>Privat repository?</strong><p>Legg først serverens read-only Deploy Key inn i GitHub. Bruk deretter SSH-adressen <code>git@github.com:eier/repository.git</code>. Ikke lagre et Personal Access Token i URL-en.</p></div></div>
@else
<div class="stats"><article><div><small>GREN</small><strong>{{ $status['branch'] }}</strong></div></article><article><div><small>VERSJON</small><strong>{{ $status['head'] }}</strong></div></article><article><div><small>NYE COMMITS</small><strong>{{ $status['behind'] }}</strong></div></article><article><div><small>LOKALE COMMITS</small><strong>{{ $status['ahead'] }}</strong></div></article></div>
<div class="notice {{ $status['dirty']?'danger':'' }}"><strong>{{ $status['dirty']?'Lokale serverendringer oppdaget':'Arbeidstreet er rent' }}</strong><p>{{ $status['dirty']?'GitHub-oppdatering er sperret til serverendringene er håndtert manuelt.':'Ingen sporede lokale filer vil bli overskrevet.' }}</p></div>
@if(($status['dirty']||$status['ahead'])&&($status['files']??[]))<div class="notice warning"><strong>Velg hvilke avvik GitHub skal erstatte</strong><p>Alle vanlige filer er valgt på forhånd. Fjern haken ved filer som skal beholdes på serveren.</p></div><form method="post" action="{{ route('superadmin.git-update.synchronize') }}" class="stack git-file-form">@csrf<div class="git-file-select"><div class="git-file-select-head"><strong>{{ count($status['files']) }} filer kan oppdateres</strong><button type="button" class="button ghost" data-git-toggle>Fjern alle valg</button></div>@foreach($status['files'] as $file)<label class="check"><input type="checkbox" name="selected_files[]" value="{{ $file }}" checked><code>{{ $file }}</code></label>@endforeach</div><label class="check"><input type="checkbox" name="confirmation" value="1" required> Jeg bekrefter at GitHub-versjonen skal erstatte de valgte programfilene</label><button class="button">Oppdater valgte filer</button></form>@endif
@if($status['checked_remote']??false)
 @if(!$status['files'])<div class="empty-state"><strong>✓ Ingen valgbare programfiler</strong><span>Det finnes ingen vanlige filer som må oppdateres.</span></div>@endif
@endif
<div class="quote-actions"><form method="post" action="{{ route('superadmin.git-update.check') }}">@csrf<button class="button ghost">Kontroller GitHub nå</button></form></div>@if(($status['checked_remote']??false)&&($status['behind']??0)>0&&!$status['dirty']&&!$status['ahead']&&!$status['vendor_required']&&($status['files']??[]))<form method="post" action="{{ route('superadmin.git-update.pull') }}" class="stack git-file-form">@csrf<div class="git-file-select"><div class="git-file-select-head"><strong>Velg filer fra oppdateringen</strong><button type="button" class="button ghost" data-git-toggle>Fjern alle valg</button></div>@foreach($status['files'] as $file)<label class="check"><input type="checkbox" name="selected_files[]" value="{{ $file }}" checked><code>{{ $file }}</code></label>@endforeach</div><label class="check"><input type="checkbox" name="confirmation" value="1" required> Jeg bekrefter at valgte filer skal hentes og installeres</label><button class="button">Hent valgte filer</button></form>@endif
@if($status['ignored_files']??[])<details class="notice"><summary>{{ count($status['ignored_files']) }} beskyttede filer ignoreres automatisk</summary><ul>@foreach($status['ignored_files'] as $file)<li><code>{{ $file }}</code></li>@endforeach</ul></details>@endif
@if(($status['vendor_ready']??false)&&($status['vendor_message']??null))<div class="notice success"><strong>✓ Composer og vendor er kontrollert</strong><p>{{ $status['vendor_message'] }} Git-oppdateringen kan fortsette uten å overskrive servermiljøet.</p></div>@elseif($status['vendor_required']??false)<div class="notice warning"><strong>Ny vendor-mappe kreves</strong><p>{{ $status['vendor_message']??'composer.lock er endret. Last opp matchende vendor og kontroller på nytt.' }}</p></div>@endif
@if($status['database_required']??false)<div class="notice warning"><strong>Databaseoppdatering følger med</strong><p>Etter at filene er hentet må du åpne Databaseoppdatering og installere migreringene.</p></div>@endif
@endif
</section>
<section class="panel"><p class="eyebrow">BESKYTTEDE DATA</p><h2>Dette røres aldri</h2><p class="muted"><code>.env</code>, databaseinnhold, <code>storage</code>, opplastede filer og serverens hemmeligheter skal være ignorert av Git. Oppdateringen avbrytes hvis GitHub likevel forsøker å endre slike stier.</p><p class="fine">Remote: {{ $status['remote_url']??'Ikke tilgjengelig' }} · Mappe: {{ $status['path']??'' }}</p></section>
<script src="{{ asset('git-update.js') }}?v=20260812-1" defer></script>
</x-layouts.app>
