<x-layouts.app title="Git-oppdatering · DekkPilot" heading="Hent programoppdatering">
@php($status=session('git_status',session('git_error',$gitStatus)))
<div class="admin-subnav"><a href="{{ route('superadmin') }}">← Superadmin</a><a href="{{ route('superadmin.system-update') }}">Databaseoppdatering</a></div>
<section class="panel"><div class="panel-head"><div><p class="eyebrow">SIKKER GITHUB-OPPDATERING</p><h2>{{ ($status['available']??false) ? (($status['behind']??0)>0 ? ($status['behind'].' nye commits er tilgjengelige') : 'Kontroller GitHub for endringer') : 'Git er ikke klart' }}</h2><p class="muted">Henter bare fra låst GitHub-remote og aktiv gren. Fast-forward er påkrevd; lokale endringer, divergens og beskyttede filer stopper oppdateringen.</p></div>@if($status['available']??false)<span class="status {{ ($status['behind']??0)>0?'in_progress':'completed' }}">{{ ($status['behind']??0)>0?'Oppdatering klar':'Status lokal' }}</span>@endif</div>
@if(!($status['available']??false))<div class="notice warning"><strong>GitHub er ikke koblet til ennå</strong><p>{{ $status['error']??'Ukjent feil' }}</p><p>Kontrollert mappe: <code>{{ $status['path']??'' }}</code></p></div>
<div class="setup-card"><p class="eyebrow">FØRSTEGANGSOPPSETT</p><h3>Koble servermappen til GitHub</h3><p class="muted">Dette oppretter kun Git-metadata og sammenligner eksisterende filer med GitHub. Ingen programfiler overskrives i dette steget.</p><form method="post" action="{{ route('superadmin.git-update.connect') }}" class="stack">@csrf<label>GitHub repository-adresse<input type="url" name="repository_url" value="{{ old('repository_url') }}" placeholder="https://github.com/brukernavn/dekkpilot.git" required autocomplete="off"><small>Ikke lim inn token eller passord i adressen.</small></label><label>Gren<input name="branch" value="{{ old('branch','main') }}" required pattern="[A-Za-z0-9._/-]+"></label><label>Bekreft sikkert oppsett<input name="confirmation" placeholder="Skriv KOBLE TIL GITHUB" required autocomplete="off"></label><button class="button">Koble til GitHub uten å overskrive filer</button></form><div class="notice"><strong>Privat repository?</strong><p>Legg først serverens read-only Deploy Key inn i GitHub. Bruk deretter SSH-adressen <code>git@github.com:eier/repository.git</code>. Ikke lagre et Personal Access Token i URL-en.</p></div></div>
@else
<div class="stats"><article><div><small>GREN</small><strong>{{ $status['branch'] }}</strong></div></article><article><div><small>VERSJON</small><strong>{{ $status['head'] }}</strong></div></article><article><div><small>NYE COMMITS</small><strong>{{ $status['behind'] }}</strong></div></article><article><div><small>LOKALE COMMITS</small><strong>{{ $status['ahead'] }}</strong></div></article></div>
<div class="notice {{ $status['dirty']?'danger':'' }}"><strong>{{ $status['dirty']?'Lokale serverendringer oppdaget':'Arbeidstreet er rent' }}</strong><p>{{ $status['dirty']?'GitHub-oppdatering er sperret til serverendringene er håndtert manuelt.':'Ingen sporede lokale filer vil bli overskrevet.' }}</p></div>
@if($status['dirty']||$status['ahead'])<div class="notice warning"><strong>GitHub kan erstatte avvikene</strong><p>Dette erstatter alle sporede programfiler med versjonen på GitHub. <code>.env</code>, databasekobling, <code>storage</code>, opplastinger og usporede filer beholdes.</p></div><form method="post" action="{{ route('superadmin.git-update.synchronize') }}" class="stack">@csrf<label>Bekreft at GitHub er fasiten<input name="confirmation" placeholder="Skriv ERSTATT SERVERFILER" required autocomplete="off"></label><button class="button">Erstatt avvikende programfiler</button></form>@endif
@if($status['checked_remote']??false)
 @if($status['files'])<details open><summary>{{ count($status['files']) }} filer blir oppdatert</summary><div class="update-list"><ul>@foreach(array_slice($status['files'],0,100) as $file)<li><code>{{ $file }}</code></li>@endforeach</ul>@if(count($status['files'])>100)<p>… og {{ count($status['files'])-100 }} filer til.</p>@endif</div></details>@else<div class="empty-state"><strong>✓ Serveren har nyeste versjon</strong><span>Det finnes ingen nye filer på {{ $status['remote'] }}/{{ $status['branch'] }}.</span></div>@endif
@endif
<div class="quote-actions"><form method="post" action="{{ route('superadmin.git-update.check') }}">@csrf<button class="button ghost">Kontroller GitHub nå</button></form>@if(($status['checked_remote']??false)&&($status['behind']??0)>0&&!$status['dirty']&&!$status['ahead']&&!$status['vendor_required'])<form method="post" action="{{ route('superadmin.git-update.pull') }}" class="stack">@csrf<label>Bekreft oppdatering<input name="confirmation" placeholder="Skriv HENT OPPDATERING" required autocomplete="off"></label><button class="button">Hent {{ count($status['files']) }} nye/endret filer</button></form>@endif</div>
@if($status['vendor_required']??false)<div class="notice warning"><strong>Ny vendor-mappe kreves</strong><p><code>composer.lock</code> er endret. Weboppdateringen er sperret til avhengighetene er bygget og lastet opp på en kontrollert måte.</p></div>@endif
@if($status['database_required']??false)<div class="notice warning"><strong>Databaseoppdatering følger med</strong><p>Etter at filene er hentet må du åpne Databaseoppdatering og installere migreringene.</p></div>@endif
@endif
</section>
<section class="panel"><p class="eyebrow">BESKYTTEDE DATA</p><h2>Dette røres aldri</h2><p class="muted"><code>.env</code>, databaseinnhold, <code>storage</code>, opplastede filer og serverens hemmeligheter skal være ignorert av Git. Oppdateringen avbrytes hvis GitHub likevel forsøker å endre slike stier.</p><p class="fine">Remote: {{ $status['remote_url']??'Ikke tilgjengelig' }} · Mappe: {{ $status['path']??'' }}</p></section>
</x-layouts.app>
