<x-layouts.app title="Superadmin · DekkPilot" heading="SaaS-kunder">
<div class="superadmin-banner"><span>★</span><div><strong>Plattformadministrasjon</strong><p>Du ser data på tvers av virksomheter fordi kontoen din er eksplisitt godkjent som superadmin.</p></div></div>
@php($diagnostics=app(\App\Services\SuperAdminDiagnostics::class))
<section class="panel system-update-summary"><div><p class="eyebrow">SIKKER DIAGNOSE</p><h2>{{ $diagnostics->enabled()?'Diagnosemodus er aktiv':'Diagnosemodus er av' }}</h2><p class="muted">Viser maskert Laravel-logg bare til innlogget superadmin. Vanlige besøkende får aldri tekniske feildetaljer.</p></div><div class="quote-actions">@if($diagnostics->enabled())<a class="button ghost" href="{{ route('superadmin.diagnostics') }}">Se siste feil</a>@endif<form method="post" action="{{ route('superadmin.diagnostics.toggle') }}">@csrf<input type="hidden" name="enabled" value="{{ $diagnostics->enabled()?0:1 }}"><button class="button {{ $diagnostics->enabled()?'ghost':'' }}">{{ $diagnostics->enabled()?'Slå av diagnose':'Slå på diagnose' }}</button></form></div></section>
<section class="panel system-update-summary"><div><p class="eyebrow">SYSTEMSTATUS</p><h2>{{ $updateStatus['current'] ? 'Databasen er oppdatert' : 'Oppdatering må kontrolleres' }}</h2><p class="muted">{{ $updateStatus['available'] ? ($updateStatus['current'] ? 'Alle '.$updateStatus['ran_count'].' databaseoppdateringer er installert.' : count($updateStatus['pending']).' oppdateringer venter på installasjon.') : $updateStatus['error'] }}</p></div><a class="button {{ $updateStatus['current'] ? 'ghost' : '' }}" href="{{ route('superadmin.system-update') }}">Se systemoppdatering →</a></section>
@php($gitRouteReady=\Illuminate\Support\Facades\Route::has('superadmin.git-update'))
<section class="panel system-update-summary"><div><p class="eyebrow">PROGRAMFILER</p><h2>Oppdater fra GitHub</h2><p class="muted">{{ $gitRouteReady ? 'Kontroller om GitHub har en nyere versjon, se hvilke filer som endres og hent dem med sikker fast-forward.' : 'Git-funksjonen er lastet opp delvis eller route-cache er ikke tømt. Kjør update.php etter at alle Git-filene er lastet opp.' }}</p></div>@if($gitRouteReady)<a class="button ghost" href="{{ route('superadmin.git-update') }}">Åpne Git-oppdatering →</a>@else<span class="status in_progress">Ikke ferdig installert</span>@endif</section>
<section class="panel system-update-summary"><div><p class="eyebrow">PLATTFORMENS E-POST</p><h2>PHP, SMTP og Domeneshop</h2><p class="muted">Administrer den felles transporten for systemmeldinger og alle virksomhetenes utsendinger.</p></div><a class="button ghost" href="{{ route('superadmin.server-mail') }}">Åpne e-postserver →</a></section>
<section class="panel system-update-summary"><div><p class="eyebrow">PRODUKSJONSDRIFT</p><h2>Cron, køer, backup og helse</h2><p class="muted">Opprett sikker cronjobb og kontroller at automatisering, lagerreservasjoner og backup faktisk kjører.</p></div><a class="button ghost" href="{{ route('superadmin.operations') }}">Åpne driftssenter →</a></section>
<section class="panel system-update-summary"><div><p class="eyebrow">NUMMEROPPLYSNING</p><h2>1881 – navn og adresse</h2><p class="muted">Aktiver eller skjul telefonoppslag for alle virksomhetenes kunderegistrering.</p></div><a class="button ghost" href="{{ route('superadmin.phone-directory') }}">Administrer 1881 →</a></section>
<section class="stats"><article><span class="stat-icon violet">◎</span><div><small>VIRKSOMHETER</small><strong>{{ $stats['organizations'] }}</strong></div></article><article><span class="stat-icon green">✓</span><div><small>AKTIVE</small><strong>{{ $stats['active'] }}</strong></div></article><article><span class="stat-icon orange">!</span><div><small>KREVER OPPFØLGING</small><strong>{{ $stats['attention'] }}</strong></div></article><article><span class="stat-icon blue">♙</span><div><small>BRUKERE</small><strong>{{ $stats['users'] }}</strong></div></article></section>
<section class="panel"><div class="panel-head"><div><p class="eyebrow">ALLE SAAS-KUNDER</p><h2>Virksomheter</h2></div><form class="search" method="get"><input name="q" value="{{ request('q') }}" placeholder="Bedrift, org.nr. eller e-post"><select name="status"><option value="">Alle statuser</option>@foreach(['active'=>'Aktiv','trialing'=>'Prøveperiode','past_due'=>'Forfalt','incomplete'=>'Ikke startet','canceled'=>'Avsluttet','unpaid'=>'Ikke betalt'] as $value=>$label)<option value="{{ $value }}" @selected(request('status')===$value)>{{ $label }}</option>@endforeach</select><button>Søk</button></form></div>
<div class="table-wrap"><table><thead><tr><th>Virksomhet</th><th>Eier / kontakt</th><th>Abonnement</th><th>Bruk</th><th>Opprettet</th><th></th></tr></thead><tbody>@forelse($organizations as $organization)@php($owner=$organization->users->firstWhere('role','owner')??$organization->users->first())<tr><td><strong>{{ $organization->name }}</strong><small>{{ $organization->organization_number ?: 'Org.nr. mangler' }} · ID {{ $organization->id }}</small></td><td>{{ $owner?->name ?? 'Ingen eier' }}<small>{{ $owner?->email }}{{ $owner?->last_login_at ? ' · Sist inne '.$owner->last_login_at->format('d.m.Y H:i') : '' }}</small></td><td><span class="status {{ in_array($organization->subscription_status,['active','trialing'],true)?'completed':($organization->subscription_status==='past_due'?'in_progress':'cancelled') }}">{{ $organization->subscription_status }}</span><small>Betaling: faktura</small></td><td>{{ $organization->customers_count }} kunder · {{ $organization->vehicles_count }} biler<small>{{ $organization->bookings_count }} bookinger · {{ $organization->tire_sets_count }} hjulsett · {{ $organization->users_count }} brukere</small></td><td>{{ $organization->created_at->format('d.m.Y') }}</td><td><form method="post" action="{{ route('superadmin.enter',$organization) }}">@csrf<button class="button ghost">Gå inn →</button></form></td></tr>@empty<tr><td colspan="6" class="empty">Ingen virksomheter matcher søket.</td></tr>@endforelse</tbody></table></div>{{ $organizations->links() }}</section>
</x-layouts.app>
