@php($diagnostics=app(\App\Services\SuperAdminDiagnostics::class))
<section class="panel system-update-summary"><div><p class="eyebrow">SIKKER DIAGNOSE</p><h2>{{ $diagnostics->enabled()?'Diagnosemodus er aktiv':'Diagnosemodus er av' }}</h2><p class="muted">Viser maskert Laravel-logg bare til innlogget superadmin. Vanlige besøkende får aldri tekniske feildetaljer.</p></div><div class="quote-actions">@if($diagnostics->enabled())<a class="button ghost" href="{{ route('superadmin.diagnostics') }}">Se siste feil</a>@endif<form method="post" action="{{ route('superadmin.diagnostics.toggle') }}">@csrf<input type="hidden" name="enabled" value="{{ $diagnostics->enabled()?0:1 }}"><button class="button {{ $diagnostics->enabled()?'ghost':'' }}">{{ $diagnostics->enabled()?'Slå av diagnose':'Slå på diagnose' }}</button></form></div></section>
<section class="panel system-update-summary"><div><p class="eyebrow">SYSTEMSTATUS</p><h2>{{ $updateStatus['current'] ? 'Databasen er oppdatert' : 'Oppdatering må kontrolleres' }}</h2><p class="muted">{{ $updateStatus['available'] ? ($updateStatus['current'] ? 'Alle '.$updateStatus['ran_count'].' databaseoppdateringer er installert.' : count($updateStatus['pending']).' oppdateringer venter på installasjon.') : $updateStatus['error'] }}</p></div><a class="button {{ $updateStatus['current'] ? 'ghost' : '' }}" href="{{ route('superadmin.system-update') }}">Se systemoppdatering →</a></section>
@php($gitRouteReady=\Illuminate\Support\Facades\Route::has('superadmin.git-update'))
<section class="panel system-update-summary"><div><p class="eyebrow">PROGRAMFILER</p><h2>Oppdater fra GitHub</h2><p class="muted">{{ $gitRouteReady ? 'Kontroller om GitHub har en nyere versjon, se hvilke filer som endres og hent dem med sikker fast-forward.' : 'Git-funksjonen er lastet opp delvis eller route-cache er ikke tømt. Kjør update.php etter at alle Git-filene er lastet opp.' }}</p></div>@if($gitRouteReady)<a class="button ghost" href="{{ route('superadmin.git-update') }}">Åpne Git-oppdatering →</a>@else<span class="status in_progress">Ikke ferdig installert</span>@endif</section>
<section class="panel system-update-summary"><div><p class="eyebrow">PLATTFORMENS E-POST</p><h2>PHP, SMTP og Domeneshop</h2><p class="muted">Administrer den felles transporten for systemmeldinger og alle virksomhetenes utsendinger.</p></div><a class="button ghost" href="{{ route('superadmin.server-mail') }}">Åpne e-postserver →</a></section>
<section class="panel system-update-summary"><div><p class="eyebrow">PRODUKSJONSDRIFT</p><h2>Cron, køer, backup og helse</h2><p class="muted">Opprett sikker cronjobb og kontroller at automatisering, lagerreservasjoner og backup faktisk kjører.</p></div><a class="button ghost" href="{{ route('superadmin.operations') }}">Åpne driftssenter →</a></section>
<section class="panel system-update-summary"><div><p class="eyebrow">TESTMILJØER</p><h2>Dummydata per virksomhet</h2><p class="muted">Velg nøyaktig hvilket miljø som skal fylles eller ryddes. Ordinære administratorer ser ikke funksjonen.</p></div><a class="button ghost" href="{{ route('superadmin.dummy') }}">Administrer dummydata →</a></section>
<section class="panel system-update-summary"><div><p class="eyebrow">NUMMEROPPLYSNING</p><h2>1881 – navn og adresse</h2><p class="muted">Aktiver eller skjul telefonoppslag for alle virksomhetenes kunderegistrering.</p></div><a class="button ghost" href="{{ route('superadmin.phone-directory') }}">Administrer 1881 →</a></section>
