<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\OperationsController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\ManagementController;
use App\Http\Controllers\QuoteController;
use App\Http\Controllers\CommunicationController;
use App\Http\Controllers\BookingConfirmationController;
use App\Http\Controllers\AccountingController;
use App\Http\Controllers\RegistrationController;
use App\Http\Controllers\BillingController;
use App\Http\Controllers\DataImportController;
use App\Http\Controllers\SuperAdminController;
use App\Http\Controllers\TireCatalogController;
use App\Http\Controllers\WorkdayController;
use App\Http\Controllers\StatisticsController;
use App\Http\Controllers\WorkshopController;
use App\Http\Controllers\CustomerPortalController;
use App\Http\Controllers\PasswordResetController;
use App\Http\Controllers\DemoUpdateController;
use App\Http\Controllers\SuperAdminSystemUpdateController;
use App\Http\Controllers\SuperAdminGitUpdateController;
use App\Http\Controllers\WarehouseController;
use App\Http\Controllers\UiModeController;
use App\Http\Controllers\ActionCenterController;
use App\Http\Controllers\HotelAgreementController;
use App\Http\Controllers\TwoFactorController;
use App\Http\Controllers\SystemSettingsController;
use App\Http\Controllers\CheckoutPortalController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SuperAdminOperationsController;
use App\Http\Controllers\SuperAdminDummyDataController;
use App\Http\Controllers\SeasonRecallController;

// Lever nye CSS/JS-filer gjennom den vanlige frontcontrolleren. Enkelte delte
// webhotell sender ikke /api/* videre til Laravel, men /index.php/* fungerer.
Route::get('/systemressurs/{filename}', [\App\Http\Controllers\AssetController::class, 'show'])
    ->where('filename', '[A-Za-z0-9._-]+\.(?:css|js)')
    ->name('system.asset');
Route::get('/api/systemressurs/{filename}', [\App\Http\Controllers\AssetController::class, 'show'])
    ->where('filename', '[A-Za-z0-9._-]+\.(?:css|js)')
    ->name('system.asset.compat');

Route::middleware('guest')->group(function () {
    Route::get('/login', [AuthController::class, 'form'])->name('login');
    Route::post('/login', [AuthController::class, 'login'])->name('login.submit');
    Route::get('/glemt-passord', [PasswordResetController::class, 'requestForm'])->name('password.request');
    Route::post('/glemt-passord', [PasswordResetController::class, 'send'])->middleware('throttle:5,1')->name('password.email');
    Route::get('/nytt-passord/{token}', [PasswordResetController::class, 'resetForm'])->name('password.reset');
    Route::post('/nytt-passord', [PasswordResetController::class, 'reset'])->middleware('throttle:5,1')->name('password.update');
    Route::get('/demo/test/test', [AuthController::class, 'demo'])->middleware('throttle:10,1')->name('demo.login');
    Route::get('/registrer', [RegistrationController::class, 'form'])->name('register');
    Route::get('/registrer/virksomhet', [RegistrationController::class, 'lookup'])->middleware('throttle:30,1')->name('register.lookup');
    Route::post('/registrer', [RegistrationController::class, 'store'])->middleware('throttle:5,1')->name('register.store');
});
Route::view('/vilkar', 'legal.terms')->name('legal.terms');
Route::view('/personvern', 'legal.privacy')->name('legal.privacy');
Route::match(['get','post'],'/system-cron/{token}',[SuperAdminOperationsController::class,'run'])->middleware('throttle:3,1')->name('system.cron');
Route::get('/utsjekk/{organization:public_id}',[CheckoutPortalController::class,'show'])->middleware('throttle:60,1')->name('checkout.show');
Route::post('/utsjekk/{organization:public_id}',[CheckoutPortalController::class,'lookup'])->middleware('throttle:15,1')->name('checkout.lookup');
// Status-URL-en er skrivebeskyttet og sikret med en tilfeldig 64-tegns token.
// Nettleseren poller denne under aktiv betaling, derfor skal den ikke dele en
// IP-basert grense med andre kunder bak samme bedriftsnett/proxy.
Route::get('/utsjekk/betaling/{payment:public_id}/{token}',[CheckoutPortalController::class,'status'])->name('checkout.status');
Route::get('/utsjekk/betaling/{payment:public_id}/{token}/vis',[CheckoutPortalController::class,'showPayment'])->middleware('throttle:60,1')->name('checkout.payment');
Route::post('/utsjekk/betaling/{payment:public_id}/{token}/start',[CheckoutPortalController::class,'start'])->middleware('throttle:15,1')->name('checkout.start');
Route::get('/utsjekk/betaling/{payment:public_id}/{token}/vipps-retur',[CheckoutPortalController::class,'vippsReturn'])->middleware('throttle:60,1')->name('checkout.vipps.return');
Route::get('/utsjekk/betaling/{payment:public_id}/{token}/kvittering',[CheckoutPortalController::class,'receipt'])->middleware('throttle:60,1')->name('checkout.receipt');
Route::middleware('auth')->group(function () {
    Route::get('/tofaktor', [TwoFactorController::class, 'challenge'])->name('two-factor.challenge');
    Route::post('/tofaktor', [TwoFactorController::class, 'verify'])->middleware('throttle:6,1')->name('two-factor.verify');
    Route::get('/velg-visning', [UiModeController::class, 'choose'])->name('ui-mode.choose');
    Route::post('/velg-visning', [UiModeController::class, 'store'])->name('ui-mode.store');
});
Route::middleware(['auth','superadmin'])->group(function(){Route::get('/superadmin',[SuperAdminController::class,'index'])->name('superadmin');Route::post('/superadmin/{organization}/ga-inn',[SuperAdminController::class,'enter'])->name('superadmin.enter');Route::post('/superadmin/avslutt',[SuperAdminController::class,'leave'])->name('superadmin.leave');Route::get('/superadmin/demo-oppdatering',[DemoUpdateController::class,'show'])->name('superadmin.demo-update');Route::post('/superadmin/demo-oppdatering',[DemoUpdateController::class,'run'])->middleware('throttle:3,10')->name('superadmin.demo-update.run');Route::get('/superadmin/systemoppdatering',[SuperAdminSystemUpdateController::class,'show'])->name('superadmin.system-update');Route::post('/superadmin/systemoppdatering',[SuperAdminSystemUpdateController::class,'run'])->middleware('throttle:2,10')->name('superadmin.system-update.run');});
Route::middleware(['auth','2fa','superadmin'])->group(function(){Route::get('/superadmin/git-oppdatering',[SuperAdminGitUpdateController::class,'show'])->name('superadmin.git-update');Route::post('/superadmin/git-oppdatering/koble-til',[SuperAdminGitUpdateController::class,'connect'])->middleware('throttle:5,1')->name('superadmin.git-update.connect');Route::post('/superadmin/git-oppdatering/kontroller',[SuperAdminGitUpdateController::class,'check'])->name('superadmin.git-update.check');Route::post('/superadmin/git-oppdatering/hent',[SuperAdminGitUpdateController::class,'pull'])->name('superadmin.git-update.pull');Route::post('/superadmin/git-oppdatering/synkroniser',[SuperAdminGitUpdateController::class,'synchronize'])->name('superadmin.git-update.synchronize');});
Route::middleware(['auth','2fa','superadmin'])->group(function(){Route::get('/superadmin/epostserver',[SystemSettingsController::class,'serverMail'])->name('superadmin.server-mail');Route::put('/superadmin/epostserver',[SystemSettingsController::class,'saveServerMail'])->name('superadmin.server-mail.save');});
Route::middleware(['auth','2fa','superadmin'])->group(function(){Route::get('/superadmin/produksjonsdrift',[SuperAdminOperationsController::class,'show'])->name('superadmin.operations');Route::post('/superadmin/produksjonsdrift/cron',[SuperAdminOperationsController::class,'generate'])->middleware('throttle:3,10')->name('superadmin.operations.cron');});
Route::middleware(['auth','2fa','superadmin'])->group(function(){Route::get('/superadmin/dummydata',[SuperAdminDummyDataController::class,'index'])->name('superadmin.dummy');Route::post('/superadmin/dummydata',[SuperAdminDummyDataController::class,'generate'])->middleware('throttle:2,10')->name('superadmin.dummy.generate');Route::delete('/superadmin/dummydata',[SuperAdminDummyDataController::class,'delete'])->middleware('throttle:2,10')->name('superadmin.dummy.delete');});
Route::middleware(['auth','2fa','superadmin'])->group(function(){Route::get('/superadmin/1881',[SystemSettingsController::class,'phoneDirectory'])->name('superadmin.phone-directory');Route::put('/superadmin/1881',[SystemSettingsController::class,'savePhoneDirectory'])->name('superadmin.phone-directory.save');});

Route::middleware(['auth','2fa','superadmin'])->group(function(){
    Route::get('/superadmin/diagnose',[\App\Http\Controllers\SuperAdminDiagnosticsController::class,'show'])->name('superadmin.diagnostics');
    Route::post('/superadmin/diagnose',[\App\Http\Controllers\SuperAdminDiagnosticsController::class,'toggle'])->middleware('throttle:6,1')->name('superadmin.diagnostics.toggle');
});

Route::middleware(['auth','2fa','impersonate','subscribed','demo.readonly','tenant.rbac'])->group(function () {
    Route::get('/', [OperationsController::class, 'dashboard'])->name('dashboard');
    Route::view('/hjelp', 'help.index')->name('help');
    Route::get('/krever-handling', [ActionCenterController::class, 'index'])->name('actions');
    Route::put('/krever-handling/hjulsett/{tireSet}', [ActionCenterController::class, 'updateTireSet'])->name('actions.tire-set.update');
    Route::post('/krever-handling/{kind}/{id}', [ActionCenterController::class, 'resolve'])->where('kind','booking|message|agreement|count')->whereNumber('id')->name('actions.resolve');
    Route::get('/statistikk', [StatisticsController::class, 'index'])->name('statistics');
    Route::get('/min-arbeidsdag', [WorkdayController::class, 'index'])->name('workday');
    Route::patch('/min-arbeidsdag/hjulsett/{tireSet}', [WorkdayController::class, 'move'])->name('workday.move');
    Route::patch('/min-arbeidsdag/mottak/{tireSet}', [WorkdayController::class, 'intakeStep'])->name('workday.intake-step');
    Route::post('/logout', [AuthController::class, 'logout'])->name('logout');
    Route::get('/abonnement', [BillingController::class, 'index'])->name('billing');
    Route::get('/kunder', [OperationsController::class, 'customers'])->name('customers');
    Route::get('/postnummer/{postalCode}', [OperationsController::class, 'postalCode'])->where('postalCode', '\\d{4}')->middleware('throttle:120,1')->name('postal-code.lookup');
    Route::get('/nummeropplysning', [\App\Http\Controllers\PhoneDirectoryController::class, 'lookup'])->middleware('throttle:20,1')->name('phone-directory.lookup');
    Route::post('/kunder', [OperationsController::class, 'storeCustomer'])->name('customers.store');
    Route::get('/kunder/{customer}', [OperationsController::class, 'customer'])->name('customers.show');
    Route::put('/kunder/{customer}', [OperationsController::class, 'updateCustomer'])->name('customers.update');
    Route::delete('/kunder/{customer}', [OperationsController::class, 'destroyCustomer'])->name('customers.destroy');
    Route::get('/kunder/{customer}/dataeksport', [OperationsController::class, 'exportCustomer'])->name('customers.export');
    Route::post('/kunder/{customer}/kjoretoy', [OperationsController::class, 'storeVehicle'])->name('vehicles.store');
    Route::get('/kjoretoy/{vehicle}/historikk', [OperationsController::class, 'vehicleHistory'])->name('vehicles.history');
    Route::put('/kunder/{customer}/kjoretoy/{vehicle}/flytt', [OperationsController::class, 'transferVehicle'])->name('vehicles.transfer');
    Route::delete('/kunder/{customer}/kjoretoy/{vehicle}', [OperationsController::class, 'archiveVehicle'])->name('vehicles.archive');
    Route::get('/kunder/{customer}/kjoretoy-oppslag', [OperationsController::class, 'lookupVehicle'])->middleware('throttle:30,1')->name('vehicles.lookup');
    Route::get('/lager', [OperationsController::class, 'inventory'])->name('inventory');
    Route::get('/lager/hjulsett/{tireSet}', [OperationsController::class, 'tireSet'])->name('tire-sets.show');
    Route::get('/dekkhotellavtaler', [HotelAgreementController::class, 'index'])->name('hotel-agreements.index');
    Route::post('/dekkhotellavtaler', [HotelAgreementController::class, 'store'])->name('hotel-agreements.store');
    Route::patch('/dekkhotellavtaler/{agreement}/status', [HotelAgreementController::class, 'status'])->name('hotel-agreements.status');
    Route::post('/lager/hjulsett/{tireSet}/tell', [HotelAgreementController::class, 'count'])->name('tire-sets.count');
    Route::get('/lagerkart', [WarehouseController::class, 'map'])->name('warehouse.map');
    Route::post('/lager/hjulsett', [OperationsController::class, 'storeTireSet'])->name('tire-sets.store');
    Route::patch('/lager/hjulsett/{tireSet}/status', [OperationsController::class, 'updateTireSetStatus'])->name('tire-sets.status');
    Route::get('/lager/etiketter', [OperationsController::class, 'tireLabels'])->name('tire-sets.labels');
    Route::post('/lager/etiketter/utskrevet', [OperationsController::class, 'markLabelsPrinted'])->name('tire-sets.labels.printed');
    Route::get('/lager/hjulsett/{tireSet}/kontroll', [WorkshopController::class, 'inspection'])->name('tire-sets.inspection');
    Route::post('/lager/hjulsett/{tireSet}/kontroll', [WorkshopController::class, 'storeInspection'])->name('tire-sets.inspection.store');
    Route::get('/arbeidsordrer', [WorkshopController::class, 'index'])->name('work-orders.index');
    Route::get('/arbeidsordrer/{workOrder}', [WorkshopController::class, 'show'])->name('work-orders.show');
    Route::patch('/arbeidsordrer/{workOrder}/status', [WorkshopController::class, 'status'])->name('work-orders.status');
    Route::patch('/arbeidsordrer/{workOrder}/oppgaver/{task}', [WorkshopController::class, 'task'])->name('work-orders.task');
    Route::post('/kunder/{customer}/portal', [CustomerPortalController::class, 'invite'])->name('customers.portal.invite');
    Route::get('/bookinger', [OperationsController::class, 'bookings'])->name('bookings');
    Route::get('/sesonginnkalling', [SeasonRecallController::class, 'index'])->middleware('role:owner,admin,manager,customer_service')->name('season-recall.index');
    Route::post('/sesonginnkalling', [SeasonRecallController::class, 'send'])->middleware(['role:owner,admin,manager','throttle:3,10'])->name('season-recall.send');
    Route::get('/bookinger/kundesok', [OperationsController::class, 'bookingCustomerSearch'])->middleware('throttle:60,1')->name('bookings.customer-search');
    Route::get('/bookinger/ledige-tider', [OperationsController::class, 'bookingAvailability'])->middleware('throttle:60,1')->name('bookings.availability');
    Route::post('/bookinger', [OperationsController::class, 'storeBooking'])->name('bookings.store');
    Route::post('/bookinger/{booking}/fullfor', [OperationsController::class, 'completeBooking'])->name('bookings.complete');
    Route::post('/bookinger/{booking}/angre-fullfort', [OperationsController::class, 'reopenBooking'])->name('bookings.reopen');
    Route::get('/bookinger/kvittering/{payment:public_id}',[CheckoutPortalController::class,'staffReceipt'])->name('bookings.receipt');
    Route::post('/bookinger/kvittering/{payment:public_id}/send-pa-nytt',[CheckoutPortalController::class,'resendReceipt'])->middleware('throttle:10,1')->name('bookings.receipt.resend');
    Route::get('/tilbud', [QuoteController::class, 'index'])->name('quotes');
    Route::get('/tilbud/forslag/{tireSet}', [QuoteController::class, 'suggestion'])->name('quotes.suggestion');
    Route::post('/tilbud/forslag/{tireSet}/forhandsvis', [QuoteController::class, 'previewSuggestion'])->name('quotes.suggestion.preview');
    Route::post('/tilbud/forslag/{tireSet}', [QuoteController::class, 'sendSuggestion'])->name('quotes.suggestion.send');
    Route::get('/tilbud/masseutsending/kontroll', [QuoteController::class, 'bulkReview'])->name('quotes.bulk.review');
    Route::post('/tilbud/masseutsending/send', [QuoteController::class, 'bulkSend'])->middleware('throttle:3,1')->name('quotes.bulk.send');
    Route::post('/tilbud', [QuoteController::class, 'store'])->name('quotes.store');
    Route::middleware('admin')->prefix('admin')->group(function () {
        Route::get('/', [AdminController::class, 'hub'])->name('admin');
        Route::get('/portaler', [AdminController::class, 'portals'])->name('admin.portals');
        Route::post('/portaler/kunde', [AdminController::class, 'openCustomerPortal'])->middleware('throttle:30,1')->name('admin.portals.customer');
        Route::get('/portaler/kunde/{customer}', [CustomerPortalController::class, 'adminPreview'])->name('admin.portals.customer-preview');
        Route::get('/sikkerhet', [TwoFactorController::class, 'setup'])->name('admin.security');
        Route::post('/sikkerhet/tofaktor', [TwoFactorController::class, 'enable'])->middleware('throttle:6,1')->name('admin.security.2fa.enable');
        Route::delete('/sikkerhet/tofaktor', [TwoFactorController::class, 'disable'])->name('admin.security.2fa.disable');
        Route::delete('/sikkerhet/token/{token}', [TwoFactorController::class, 'revokeToken'])->name('admin.security.token.revoke');
        Route::get('/oppsett', [AdminController::class, 'index'])->name('admin.settings');
        Route::get('/system-og-backup', [SystemSettingsController::class, 'index'])->name('admin.system');
        Route::put('/system-og-backup/virksomhetsavsender', [SystemSettingsController::class, 'saveTenantMail'])->name('admin.system.tenant-mail');
        Route::post('/system-og-backup/test-epost', [SystemSettingsController::class, 'testMail'])->middleware('throttle:3,10')->name('admin.system.test-mail');
        Route::post('/system-og-backup/backup', [SystemSettingsController::class, 'createBackup'])->middleware(['superadmin','throttle:2,10'])->name('admin.system.backup');
        Route::get('/system-og-backup/backup/{filename}', [SystemSettingsController::class, 'downloadBackup'])->middleware(['superadmin','throttle:10,1'])->where('filename','[A-Za-z0-9._-]+')->name('admin.system.backup.download');
        Route::get('/lageroppsett', [WarehouseController::class, 'admin'])->name('admin.warehouse');
        Route::put('/lageroppsett/rekkefolge', [WarehouseController::class, 'reorder'])->name('admin.warehouse.reorder');
        Route::put('/lageroppsett/kartplassering', [WarehouseController::class, 'move'])->name('admin.warehouse.move');
        Route::post('/lageroppsett/plasser', [WarehouseController::class, 'store'])->name('admin.warehouse.store');
        Route::put('/lageroppsett/plasser/{location}', [WarehouseController::class, 'update'])->name('admin.warehouse.update');
        Route::patch('/lageroppsett/plasser/{location}/status', [WarehouseController::class, 'toggle'])->name('admin.warehouse.toggle');
        Route::get('/regnskap', [AccountingController::class, 'index'])->name('admin.accounting');
        Route::match(['get','post'], '/regnskap/fiken/koble-til', [AccountingController::class, 'connectFiken'])->name('admin.accounting.fiken.connect');
        Route::get('/regnskap/fiken/callback', [AccountingController::class, 'fikenCallback'])->name('admin.accounting.fiken.callback');
        Route::put('/regnskap/plattform/fiken', [AccountingController::class, 'saveFikenPlatform'])->middleware('superadmin')->name('admin.accounting.fiken.platform');
        Route::put('/regnskap/plattform/tripletex', [AccountingController::class, 'saveTripletexPlatform'])->middleware('superadmin')->name('admin.accounting.tripletex.platform');
        Route::put('/regnskap/plattform/poweroffice', [AccountingController::class, 'savePowerOfficePlatform'])->middleware('superadmin')->name('admin.accounting.poweroffice.platform');
        Route::put('/regnskap/plattform/zettle', [AccountingController::class, 'saveZettlePlatform'])->middleware('superadmin')->name('admin.accounting.zettle.platform');
        Route::put('/regnskap/betaling/vipps', [AccountingController::class, 'saveVipps'])->name('admin.accounting.vipps');
        Route::put('/regnskap/betaling/terminal', [AccountingController::class, 'saveTerminal'])->name('admin.accounting.terminal');
        Route::get('/regnskap/zettle/koble-til', [AccountingController::class, 'connectZettle'])->name('admin.accounting.zettle.connect');
        Route::get('/regnskap/zettle/callback', [AccountingController::class, 'zettleCallback'])->name('admin.accounting.zettle.callback');
        Route::put('/regnskap', [AccountingController::class, 'save'])->name('admin.accounting.save');
        Route::post('/regnskap/test', [AccountingController::class, 'test'])->middleware('throttle:5,1')->name('admin.accounting.test');
        Route::post('/regnskap/ko', [AccountingController::class, 'queueAll'])->name('admin.accounting.queue-all');
        Route::post('/regnskap/ko/{invoice}', [AccountingController::class, 'queue'])->name('admin.accounting.queue');
        Route::get('/import', [DataImportController::class, 'index'])->name('admin.imports');
        Route::post('/import', [DataImportController::class, 'upload'])->name('admin.imports.upload');
        Route::post('/import/{import}/utfor', [DataImportController::class, 'execute'])->name('admin.imports.execute');
        Route::get('/importmal', [DataImportController::class, 'template'])->name('admin.imports.template');
        Route::post('/ansatte', [ManagementController::class, 'employee'])->name('admin.employees.store');
        Route::put('/ansatte/{employee}', [ManagementController::class, 'updateEmployee'])->name('admin.employees.update');
        Route::patch('/ansatte/{employee}/status', [ManagementController::class, 'toggleEmployee'])->name('admin.employees.toggle');
        Route::post('/arbeidsbukker', [ManagementController::class, 'bay'])->name('admin.bays.store');
        Route::put('/tidsinnstillinger', [ManagementController::class, 'timing'])->name('admin.timing.update');
        Route::patch('/etikettvarsler', [ManagementController::class, 'labelReminders'])->name('admin.label-reminders');
        Route::post('/dekkprodukter', [ManagementController::class, 'tireProduct'])->name('admin.products.store');
        Route::get('/dekkatalog', [TireCatalogController::class, 'index'])->name('admin.tires');
        Route::post('/dekkatalog', [TireCatalogController::class, 'store'])->name('admin.tires.store');
        Route::post('/dekkatalog/lim-inn', [TireCatalogController::class, 'bulk'])->name('admin.tires.bulk');
        Route::post('/dekkatalog/import', [TireCatalogController::class, 'upload'])->name('admin.tires.upload');
        Route::get('/dekkatalog/importmal', [TireCatalogController::class, 'template'])->name('admin.tires.template');
        Route::patch('/dekkatalog/{product}', [TireCatalogController::class, 'update'])->name('admin.tires.update');
        Route::put('/integrasjoner/vegvesen', [ManagementController::class, 'saveVegvesen'])->name('admin.vegvesen.update');
        Route::delete('/integrasjoner/vegvesen', [ManagementController::class, 'deleteVegvesen'])->name('admin.vegvesen.delete');
        Route::get('/kommunikasjon', [CommunicationController::class, 'index'])->name('admin.communications');
        Route::post('/kommunikasjon/forhandsvis', [CommunicationController::class, 'previewDraft'])->name('admin.communications.preview');
        Route::get('/kommunikasjon/meldinger/{message}/forhandsvis', [CommunicationController::class, 'previewMessage'])->name('admin.communications.message-preview');
        Route::post('/kommunikasjon/send', [CommunicationController::class, 'send'])->name('admin.communications.send');
        Route::put('/integrasjoner/twilio', [CommunicationController::class, 'saveTwilio'])->name('admin.twilio.update');
        Route::put('/integrasjoner/twilio/varsler', [CommunicationController::class, 'saveSmsSettings'])->name('admin.twilio.settings');
        Route::post('/integrasjoner/twilio/test', [CommunicationController::class, 'testSms'])->middleware('throttle:3,10')->name('admin.twilio.test');
        Route::post('/tjenester', [ManagementController::class, 'serviceProduct'])->name('admin.services.store');
        Route::put('/tjenester/{service}', [ManagementController::class, 'updateService'])->name('admin.services.update');
        Route::patch('/tjenester/{service}/status', [ManagementController::class, 'toggleService'])->name('admin.services.toggle');
    });
});

Route::get('/tilbud/svar/{token}', [QuoteController::class, 'showPublic'])->middleware('throttle:60,1')->name('quote.public.show');
Route::get('/tilbud/svar/{token}/kjopsvilkar', [QuoteController::class, 'purchaseTerms'])->middleware('throttle:60,1')->name('quote.public.terms');
Route::post('/tilbud/svar/{token}', [QuoteController::class, 'respond'])->middleware('throttle:10,1')->name('quote.public.respond');
Route::get('/booking/bekreft/{token}', [BookingConfirmationController::class, 'show'])->middleware('throttle:60,1')->name('booking.confirm.show');
Route::post('/booking/bekreft/{token}', [BookingConfirmationController::class, 'respond'])->middleware('throttle:10,1')->name('booking.confirm.respond');
Route::get('/kundeportal/{token}', [CustomerPortalController::class, 'show'])->middleware('throttle:60,1')->name('portal.show');
Route::get('/avmelding/{customer}', [CommunicationController::class, 'unsubscribe'])->middleware(['signed','throttle:20,1'])->name('communications.unsubscribe');
Route::post('/webhooks/twilio/{message}/{token}', [CommunicationController::class, 'twilioStatus'])->middleware('throttle:120,1')->name('webhooks.twilio.status');
Route::get('/kundeportal/{token}/ledige-tider', [CustomerPortalController::class, 'availability'])->middleware('throttle:30,1')->name('portal.availability');
Route::post('/kundeportal/{token}/ny-time', [CustomerPortalController::class, 'createBooking'])->middleware('throttle:5,1')->name('portal.booking.create');
Route::post('/kundeportal/{token}/booking/{booking}', [CustomerPortalController::class, 'booking'])->middleware('throttle:10,1')->name('portal.booking');
Route::post('/kundeportal/{token}/tilbud/{quote}', [CustomerPortalController::class, 'quote'])->middleware('throttle:10,1')->name('portal.quote');
Route::post('/kundeportal/{token}/hjulsett/{tireSet}/bestill', [CustomerPortalController::class, 'orderTires'])->middleware('throttle:5,1')->name('portal.tires.order');
