<?php
namespace Tests\Feature;use App\Models\Branch;use App\Models\DataImport;use App\Models\Organization;use App\Models\User;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Http\UploadedFile;use Illuminate\Support\Facades\Storage;use Illuminate\Support\Str;use Tests\TestCase;
class DataImportTest extends TestCase
{
 use RefreshDatabase;
 private function owner():User{$org=Organization::create(['public_id'=>Str::uuid(),'name'=>'Import AS']);$branch=Branch::create(['public_id'=>Str::uuid(),'organization_id'=>$org->id,'name'=>'Hoved','code'=>'HOVED']);return User::factory()->create(['organization_id'=>$org->id,'branch_id'=>$branch->id,'role'=>'owner','active'=>true]);}
 public function test_csv_is_previewed_mapped_and_imported_inside_tenant():void{Storage::fake('local');$user=$this->owner();$csv="Kundenavn;E-post;Telefon;Registreringsnummer;Bilmerke;Bilmodell;Dekksesong;Dekkdimensjon;Mønsterdybde mm\nKari Test;kari@example.no;99999999;AB12345;Volvo;XC60;Vinter;235/55 R19;6,5\n";$response=$this->actingAs($user)->post(route('admin.imports.upload'),['file'=>UploadedFile::fake()->createWithContent('export.csv',$csv)]);$import=DataImport::firstOrFail();$response->assertRedirect(route('admin.imports',['import'=>$import->public_id]));$this->actingAs($user)->get(route('admin.imports',['import'=>$import->public_id]))->assertOk()->assertSee('Kontroller kolonnene')->assertSee('Kari Test');$this->actingAs($user)->post(route('admin.imports.execute',$import),['mapping'=>$import->mapping])->assertRedirect(route('admin.imports'));$this->assertDatabaseHas('customers',['organization_id'=>$user->organization_id,'name'=>'Kari Test']);$this->assertDatabaseHas('vehicles',['organization_id'=>$user->organization_id,'registration_number'=>'AB12345','make'=>'Volvo']);$this->assertDatabaseHas('tire_sets',['organization_id'=>$user->organization_id,'season'=>'winter','size'=>'235/55 R19']);$this->assertDatabaseHas('data_imports',['id'=>$import->id,'status'=>'completed','imported_rows'=>1]);}
 public function test_other_tenant_cannot_open_import_preview():void{Storage::fake('local');$owner=$this->owner();$this->actingAs($owner)->post(route('admin.imports.upload'),['file'=>UploadedFile::fake()->createWithContent('a.csv',"Kundenavn;E-post\nA;a@a.no\n")]);$import=DataImport::firstOrFail();$other=$this->owner();$this->actingAs($other)->get(route('admin.imports',['import'=>$import->public_id]))->assertNotFound();}
}
