<?php
namespace Tests\Feature;
use App\Mail\QuoteMail;use App\Models\Branch;use App\Models\Customer;use App\Models\Organization;use App\Models\Quote;use App\Models\TireProduct;use App\Models\TireSet;use App\Models\User;use App\Models\Vehicle;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Support\Facades\Mail;use Illuminate\Support\Str;use Tests\TestCase;
class QuoteSuggestionTest extends TestCase{
 use RefreshDatabase;
 public function test_low_tread_creates_three_stock_matched_options_and_customer_selects_one():void{
  Mail::fake();$org=Organization::create(['public_id'=>Str::uuid(),'name'=>'Salg AS']);$branch=Branch::create(['public_id'=>Str::uuid(),'organization_id'=>$org->id,'name'=>'Hoved','code'=>'HOVED']);$owner=User::factory()->create(['organization_id'=>$org->id,'branch_id'=>$branch->id,'role'=>'owner','active'=>true]);$customer=Customer::create(['public_id'=>Str::uuid(),'organization_id'=>$org->id,'branch_id'=>$branch->id,'customer_number'=>'K1','name'=>'Salg Kunde','email'=>'kunde@example.no']);$vehicle=Vehicle::create(['public_id'=>Str::uuid(),'organization_id'=>$org->id,'customer_id'=>$customer->id,'registration_number'=>'EV55555']);$set=TireSet::create(['public_id'=>Str::uuid(),'organization_id'=>$org->id,'vehicle_id'=>$vehicle->id,'code'=>'HJ-SALG','season'=>'winter','kind'=>'complete_wheels','size'=>'205/55 R16','quantity'=>4,'minimum_tread_depth'=>2.4,'status'=>'stored']);$products=collect();foreach([['Premium',220000],['Quality',180000],['Value',140000],['Feil størrelse',100000]]as$i=>[$model,$price])$products->push(TireProduct::create(['public_id'=>Str::uuid(),'organization_id'=>$org->id,'sku'=>'SKU-'.$i,'brand'=>'Test','model'=>$model,'size'=>$i===3?'225/45 R18':'205/55 R16','season'=>'winter','price_cents'=>$price,'stock_quantity'=>8,'active'=>true]));
  $this->actingAs($owner)->get(route('quotes'))->assertOk()->assertSee('EV55555')->assertSee('3 treff på lager')->assertSee('Send til alle kunder');
  $this->actingAs($owner)->get(route('quotes.bulk.review'))->assertOk()->assertSee('Salg Kunde')->assertSee('krav 3 mm');
  $this->actingAs($owner)->get(route('quotes.suggestion',$set))->assertOk()->assertSee('Det beste')->assertSee('Bra valg')->assertSee('Godt valg')->assertSee('Forhåndsvis e-post')->assertDontSee('Feil størrelse');
  $this->actingAs($owner)->post(route('quotes.suggestion.preview',$set),['product_ids'=>$products->take(3)->pluck('id')->all(),'message'=>'Personlig testmelding'])->assertOk()->assertSee('2.4 mm')->assertSee('3 mm')->assertSee('Personlig testmelding');
  $this->assertDatabaseCount('quotes',0);
  $this->withSession(['demo_read_only'=>true])->postJson(route('quotes.suggestion.preview',$set),['product_ids'=>$products->take(3)->pluck('id')->all()])->assertOk()->assertHeader('X-DekkPilot-Preview','quote-email')->assertSee('FORHÅNDSVISNING');
  Mail::assertNothingSent();$this->assertDatabaseCount('quotes',0);
  $this->post(route('quotes.suggestion.send',$set),['product_ids'=>$products->take(3)->pluck('id')->all()])->assertSessionHasErrors('demo');
  Mail::assertNothingSent();$this->assertDatabaseCount('quotes',0);
  $this->withSession(['demo_read_only'=>false])->postJson(route('quotes.suggestion.preview',$set),['product_ids'=>[$products->last()->id]])->assertUnprocessable()->assertJsonValidationErrors('product_ids');

  $this->actingAs($owner)->post(route('quotes.bulk.send'))->assertRedirect(route('quotes'))->assertSessionHas('success','1 tilbud ble sendt til kundene.');$quote=Quote::with('items')->firstOrFail();$this->assertCount(3,$quote->items);$this->assertSame(['Det beste','Bra valg','Godt valg'],$quote->items->sortBy('position')->pluck('recommendation_label')->all());$mail=Mail::sent(QuoteMail::class)->first();$rendered=$mail->render();$this->assertStringContainsString('Premium',$rendered);$this->assertStringContainsString('Quality',$rendered);$this->assertStringContainsString('Value',$rendered);$this->assertStringContainsString('Se, velg og bekreft tilbudet',$rendered);$token=basename(parse_url($mail->responseUrl,PHP_URL_PATH));$choice=$quote->items->sortBy('position')->values()[1];$this->post('/tilbud/svar/'.$token,['decision'=>'accepted','quote_item_id'=>$choice->id,'terms_accepted'=>1])->assertRedirect();$this->assertDatabaseHas('quotes',['id'=>$quote->id,'status'=>'accepted','selected_quote_item_id'=>$choice->id,'total_cents'=>$choice->line_total_cents,'purchase_terms_version'=>'2026-08-09']);
 }
 public function test_ten_year_old_tires_create_an_offer_even_with_good_tread():void{
  Mail::fake();$org=Organization::create(['public_id'=>Str::uuid(),'name'=>'Alder AS']);$branch=Branch::create(['public_id'=>Str::uuid(),'organization_id'=>$org->id,'name'=>'Hoved','code'=>'HOVED']);$owner=User::factory()->create(['organization_id'=>$org->id,'branch_id'=>$branch->id,'role'=>'owner','active'=>true]);$customer=Customer::create(['public_id'=>Str::uuid(),'organization_id'=>$org->id,'branch_id'=>$branch->id,'customer_number'=>'K2','name'=>'Alder Kunde','email'=>'alder@example.no']);$vehicle=Vehicle::create(['public_id'=>Str::uuid(),'organization_id'=>$org->id,'customer_id'=>$customer->id,'registration_number'=>'EV10101']);$set=TireSet::create(['public_id'=>Str::uuid(),'organization_id'=>$org->id,'vehicle_id'=>$vehicle->id,'code'=>'HJ-ALDER','season'=>'summer','kind'=>'tires','size'=>'205/55 R16','quantity'=>4,'minimum_tread_depth'=>6.0,'dot_year'=>now()->year-10,'status'=>'stored']);TireProduct::create(['public_id'=>Str::uuid(),'organization_id'=>$org->id,'sku'=>'ALDER-1','brand'=>'Test','model'=>'Sommer','size'=>'205/55 R16','season'=>'summer','price_cents'=>120000,'stock_quantity'=>8,'active'=>true]);
  $this->assertSame('replace',$set->age_assessment);$this->assertContains('age',$set->replacement_reasons);$this->actingAs($owner)->get(route('quotes'))->assertOk()->assertSee('EV10101');$this->actingAs($owner)->get(route('quotes.suggestion',$set))->assertOk()->assertSee('Alder')->assertSee('DOT '.$set->dot_year);
 }
}
