<?php
namespace Tests\Feature;use App\Models\Branch;use App\Models\Organization;use App\Models\User;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Support\Str;use Tests\TestCase;
class SuperAdminTest extends TestCase
{
 use RefreshDatabase;
 private function user(string $email,bool $super=false):User{$org=Organization::create(['public_id'=>Str::uuid(),'name'=>$super?'Plattform AS':'Kunde AS']);$branch=Branch::create(['public_id'=>Str::uuid(),'organization_id'=>$org->id,'name'=>'Hoved','code'=>'HOVED']);return User::factory()->create(['organization_id'=>$org->id,'branch_id'=>$branch->id,'email'=>$email,'role'=>'owner','active'=>true,'is_super_admin'=>$super]);}
 public function test_only_explicit_superadmin_can_see_all_saas_customers():void{$ordinary=$this->user('kunde@example.no');$super=$this->user('tordgladnordahl@gmail.com',true);$this->actingAs($ordinary)->get('/superadmin')->assertForbidden();$this->actingAs($super)->get('/superadmin')->assertOk()->assertSee('SaaS-kunder')->assertSee('Kunde AS')->assertSee('kunde@example.no');}
 public function test_superadmin_button_is_shown_only_to_superadmin():void{$ordinary=$this->user('vanlig@example.no');$this->actingAs($ordinary)->get('/')->assertOk()->assertDontSee('title="Superadmin"',false);$super=$this->user('tordgladnordahl@gmail.com',true);$this->actingAs($super)->get('/')->assertOk()->assertSee('title="Superadmin"',false);}
 public function test_superadmin_can_enter_and_leave_a_tenant_without_changing_account():void{$super=$this->user('tordgladnordahl@gmail.com',true);$originalOrganization=$super->organization_id;$tenantUser=$this->user('tenant@example.no');$tenant=$tenantUser->organization_id;$this->actingAs($super)->post(route('superadmin.enter',$tenant))->assertRedirect('/');$this->get('/')->assertOk()->assertSee('Du arbeider som superadmin i')->assertSee('Kunde AS');$this->assertDatabaseHas('users',['id'=>$super->id,'organization_id'=>$originalOrganization]);$this->post(route('superadmin.leave'))->assertRedirect('/superadmin');$this->get('/')->assertOk()->assertDontSee('Du arbeider som superadmin i');}
 public function test_demo_update_page_reuses_superadmin_login():void{$ordinary=$this->user('vanlig@example.no');$this->actingAs($ordinary)->get(route('superadmin.demo-update'))->assertForbidden();$super=$this->user('tordgladnordahl@gmail.com',true);$this->actingAs($super)->get(route('superadmin.demo-update'))->assertOk()->assertSee('Ingen ekstra innlogging er nødvendig')->assertDontSee('type="password"',false);}
 public function test_superadmin_always_has_admin_access_and_can_save_vegvesen_key():void{$super=$this->user('tordgladnordahl@gmail.com',true);$super->update(['role'=>'technician']);$super->organization()->update(['subscription_status'=>'canceled']);$this->actingAs($super)->withSession(['demo_read_only'=>true])->get(route('admin.settings'))->assertOk()->assertSee('Statens vegvesen');$this->put(route('admin.vegvesen.update'),['api_key'=>'test-vegvesen-key-123456'])->assertSessionHasNoErrors();$this->assertDatabaseHas('integration_settings',['organization_id'=>$super->organization_id,'provider'=>'vegvesen','active'=>true,'updated_by'=>$super->id]);}
}
