<?php
namespace Tests\Feature;
use App\Models\Branch;use App\Models\Customer;use App\Models\CustomerPortalToken;use App\Models\Organization;use App\Models\Quote;use App\Models\QuoteItem;use App\Models\TireProduct;use App\Models\TireSet;use App\Models\User;use App\Models\Vehicle;use App\Services\AcceptedQuoteWorkflow;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;use Tests\TestCase;
class WorkshopOperationsTest extends TestCase{use RefreshDatabase;
 private function base():array{$org=Organization::create(['public_id'=>Str::uuid(),'name'=>'Drift AS']);$branch=Branch::create(['public_id'=>Str::uuid(),'organization_id'=>$org->id,'name'=>'Hoved','code'=>'H']);$user=User::factory()->create(['organization_id'=>$org->id,'branch_id'=>$branch->id,'role'=>'owner','active'=>true]);$customer=Customer::create(['public_id'=>Str::uuid(),'organization_id'=>$org->id,'branch_id'=>$branch->id,'customer_number'=>'K1','name'=>'Kari','email'=>'kari@example.no']);$vehicle=Vehicle::create(['public_id'=>Str::uuid(),'organization_id'=>$org->id,'customer_id'=>$customer->id,'registration_number'=>'EV12345','make'=>'Tesla','model'=>'Model 3']);$set=TireSet::create(['public_id'=>Str::uuid(),'organization_id'=>$org->id,'vehicle_id'=>$vehicle->id,'code'=>'HJ-TEST','season'=>'winter','kind'=>'complete_wheels','size'=>'205/55 R16','quantity'=>4,'status'=>'stored']);return compact('org','branch','user','customer','vehicle','set');}
 public function test_four_wheel_inspection_updates_set_and_is_available_to_app():void{$b=$this->base();$wheels=collect(['front_left','front_right','rear_left','rear_right'])->map(fn($p,$i)=>['position'=>$p,'tread_depth_mm'=>$i===0?2.7:5.2,'dot_year'=>2024,'tpms_status'=>'ok'])->all();$this->actingAs($b['user'])->post(route('tire-sets.inspection.store',$b['set']),['wheels'=>$wheels])->assertRedirect();$this->assertDatabaseHas('tire_inspections',['tire_set_id'=>$b['set']->id,'overall_status'=>'replace']);$this->assertDatabaseHas('tire_sets',['id'=>$b['set']->id,'minimum_tread_depth'=>2.7]);$plain=Str::random(64);DB::table('personal_access_tokens')->insert(['user_id'=>$b['user']->id,'name'=>'app','token_hash'=>hash('sha256',$plain),'created_at'=>now(),'updated_at'=>now()]);$this->withToken($plain)->getJson('/api/v1/tire-sets/'.$b['set']->id.'/inspections')->assertStatus(405);}
 public function test_accepted_quote_creates_work_order_tasks_and_stock_reservation():void{$b=$this->base();$product=TireProduct::create(['public_id'=>Str::uuid(),'organization_id'=>$b['org']->id,'sku'=>'P1','brand'=>'Nokian','model'=>'Snow','size'=>'205/55 R16','season'=>'winter','price_cents'=>150000,'stock_quantity'=>8]);$quote=Quote::create(['public_id'=>Str::uuid(),'organization_id'=>$b['org']->id,'branch_id'=>$b['branch']->id,'customer_id'=>$b['customer']->id,'vehicle_id'=>$b['vehicle']->id,'reference'=>'T-1','status'=>'accepted','access_token_hash'=>hash('sha256',Str::random(64)),'subtotal_cents'=>600000,'total_cents'=>600000,'expires_at'=>now()->addDay()]);$item=QuoteItem::create(['quote_id'=>$quote->id,'tire_product_id'=>$product->id,'description'=>'Nokian Snow','quantity'=>4,'unit_price_cents'=>150000,'line_total_cents'=>600000]);$quote->update(['selected_quote_item_id'=>$item->id]);$order=app(AcceptedQuoteWorkflow::class)->create($quote);$this->assertCount(5,$order->tasks);$this->assertDatabaseHas('stock_reservations',['work_order_id'=>$order->id,'quantity'=>4,'status'=>'reserved']);$this->actingAs($b['user'])->get(route('work-orders.show',$order))->assertOk()->assertSee('Momentkontroll');}
 public function test_customer_portal_is_expiring_scoped_and_renders_vehicle():void{$b=$this->base();$plain=Str::random(64);CustomerPortalToken::create(['organization_id'=>$b['org']->id,'customer_id'=>$b['customer']->id,'token_hash'=>hash('sha256',$plain),'expires_at'=>now()->addDay()]);$this->get(route('portal.show',$plain))->assertOk()->assertSee('EV12345')->assertSee('Kari');$this->get(route('portal.show',Str::random(64)))->assertNotFound();}
}
