<x-layouts.app title="{{ $order->reference }} · DekkPilot" heading="Arbeidsordre {{ $order->reference }}">
<link rel="stylesheet" href="{{ route('system.asset', ['filename' => 'work-order.css']) }}?v=20260812-1">
<section class="stats"><article><span class="stat-icon green">✓</span><div><small>STATUS</small><strong>{{ ['draft'=>'Utkast','ready'=>'Klar','in_progress'=>'Pågår','quality_check'=>'Kontroll','completed'=>'Fullført','cancelled'=>'Avbrutt'][$order->status] }}</strong></div></article><article><span class="stat-icon blue">▣</span><div><small>BIL</small><strong>{{ $order->vehicle?->registration_number ?? '—' }}</strong></div></article><article><span class="stat-icon violet">◎</span><div><small>KUNDE</small><strong style="font-size:18px">{{ $order->customer->name }}</strong></div></article><article><span class="stat-icon orange">◷</span><div><small>TID</small><strong style="font-size:18px">{{ $order->booking?->starts_at?->format('d.m H:i') ?? 'Ikke booket' }}</strong></div></article></section>
@php
    $bookedServices = $order->booking?->services ?? collect();
    $bookedDuration = $bookedServices->sum(fn ($service) => (int) $service->pivot->duration_minutes);
    $bookedTotal = $bookedServices->sum(fn ($service) => (int) $service->pivot->price_cents);
    $selectedQuoteItems = $order->quote
        ? $order->quote->items->where('id', $order->quote->selected_quote_item_id)
        : collect();
@endphp
<section class="panel ordered-work"><div class="panel-head"><div><p class="eyebrow">KUNDENS BESTILLING</p><h2>Dette skal utføres</h2></div>@if($bookedDuration)<span class="ordered-work-duration">◷ {{ $bookedDuration }} min</span>@endif</div><div class="ordered-work-list">
@forelse($bookedServices as $service)<article><span class="ordered-work-number">{{ $loop->iteration }}</span><div><strong>{{ $service->pivot->service_name ?: $service->name }}</strong>@if($service->description)<small>{{ $service->description }}</small>@endif</div><b>{{ number_format($service->pivot->price_cents/100,0,',',' ') }} kr</b></article>
@empty
@if($order->booking?->service_name)<article><span class="ordered-work-number">1</span><div><strong>{{ $order->booking->service_name }}</strong><small>Registrert på bookingen</small></div><b>{{ number_format(($order->booking->agreed_price_cents ?? 0)/100,0,',',' ') }} kr</b></article>@else<div class="empty-state"><strong>Bestilt arbeid mangler</strong><span>Kontroller bookingen eller det godkjente tilbudet før arbeidet starter.</span></div>@endif
@endforelse
@foreach($selectedQuoteItems as $item)<article class="ordered-work-product"><span class="ordered-work-number">＋</span><div><strong>{{ $item->description }}</strong><small>Godkjent tilbud · {{ $item->quantity }} stk.</small></div><b>{{ number_format($item->line_total_cents/100,0,',',' ') }} kr</b></article>@endforeach
</div>@if($bookedServices->isNotEmpty())<footer><span>Avtalt tjenestesum</span><strong>{{ number_format($bookedTotal/100,0,',',' ') }} kr</strong></footer>@endif
@if($order->booking?->notes)<div class="ordered-work-note"><span>MERKNAD FRA BOOKING</span><p>{{ $order->booking->notes }}</p></div>@endif</section>
<section class="grid two"><article class="panel"><p class="eyebrow">JOBBKORT</p><h2>Kontrollpunkter</h2><p class="muted">Åpne et punkt, registrer resultatet og lagre. Obligatoriske punkter må være utført før jobben kan fullføres.</p><div class="work-task-list">@foreach($order->tasks as $task)<button type="button" class="work-task {{ $task->completed?'is-complete':'' }}" data-task-open="task-dialog-{{ $task->id }}"><span class="work-task-check">{{ $task->completed?'✓':'○' }}</span><span><strong>{{ $task->name }}</strong><small>{{ $task->completed_at ? $task->completed_at->format('H:i').' · Informasjon lagret' : 'Trykk for å utføre og dokumentere' }}</small>@if($task->notes)<em>{{ Str::limit(preg_replace('/^\[[^]]+\]\s*/u','',$task->notes),90) }}</em>@endif</span><b>{{ $task->completed?'Rediger':'Start' }} →</b></button>@endforeach</div></article>
<aside><article class="panel"><p class="eyebrow">NESTE STEG</p><h2>Oppdater arbeidsflyt</h2><form method="post" action="{{ route('work-orders.status',$order) }}" class="stack">@csrf @method('PATCH')<label>Status<select name="status">@foreach(['ready'=>'Klar til arbeid','in_progress'=>'Start arbeid','quality_check'=>'Send til sluttkontroll','completed'=>'Fullfør jobb','cancelled'=>'Avbryt'] as $value=>$label)<option value="{{ $value }}" @selected($order->status===$value)>{{ $label }}</option>@endforeach</select></label><button class="button full">Oppdater</button></form></article>
@if($order->quote)<article class="panel"><p class="eyebrow">GODKJENT TILBUD</p><h2>{{ number_format($order->quote->total_cents/100,0,',',' ') }} kr</h2>@foreach($order->quote->items->where('id',$order->quote->selected_quote_item_id) as $item)<p>{{ $item->description }} · {{ $item->quantity }} stk</p>@endforeach<p class="muted">Lageret er reservert automatisk og forbrukes når jobben fullføres.</p></article>@endif</aside></section>
@foreach($order->tasks as $task)
@php
    $savedResult = str_starts_with((string) $task->notes, '[Avvik') ? 'deviation'
        : (str_starts_with((string) $task->notes, '[Utført –') ? 'attention'
        : (str_starts_with((string) $task->notes, '[Ikke relevant') ? 'not_applicable' : 'ok'));
    $savedNotes = trim((string) preg_replace('/^\[[^]]+\]\s*/u', '', $task->notes));
@endphp
<dialog class="work-task-dialog" id="task-dialog-{{ $task->id }}"><form method="post" action="{{ route('work-orders.task',[$order,$task->id]) }}" data-task-form>@csrf @method('PATCH')<div class="work-task-dialog-head"><div><p class="eyebrow">KONTROLLPUNKT</p><h2>{{ $task->name }}</h2></div><button type="button" data-task-close aria-label="Lukk">×</button></div><div class="work-task-dialog-body"><label>Resultat<select name="result" required><option value="ok" @selected($savedResult==='ok')>Utført og godkjent</option><option value="attention" @selected($savedResult==='attention')>Utført – bør følges opp</option><option value="deviation" @selected($savedResult==='deviation')>Avvik registrert</option><option value="not_applicable" @selected($savedResult==='not_applicable')>Ikke relevant</option></select></label><label>Hva ble gjort eller observert?<textarea name="notes" rows="5" maxlength="2000" placeholder="Skriv kort hva som ble kontrollert, utført eller oppdaget.">{{ $savedNotes }}</textarea><small>Forklaring er obligatorisk når du registrerer et avvik.</small></label></div><div class="work-task-dialog-actions">@if($task->completed)<button class="button ghost danger" name="completed" value="0">Åpne punktet igjen</button>@endif<button class="button" name="completed" value="1">{{ $task->completed?'Lagre endringer':'Lagre og fullfør' }}</button></div></form></dialog>
@endforeach
<script defer src="{{ route('system.asset', ['filename' => 'work-order.js']) }}?v=20260812-1"></script>
</x-layouts.app>
