<x-layouts.app title="{{ $vehicle->registration_number }} · Bilhistorikk" heading="{{ $vehicle->registration_number }}">
@if(in_array(auth()->user()->role,['owner','admin','manager','customer_service'],true))
<p><a class="button ghost" href="{{ route('vehicles.edit',$vehicle) }}">Rediger bil</a></p>
@endif
@include('vehicles.contact')
<div class="admin-subnav"><a href="{{ route('customers.show',$vehicle->customer) }}">← {{ $vehicle->customer->name }}</a><a href="#ownership">Eiere</a><a href="#work">Arbeid</a><a href="#hotel">Dekkhotell</a></div>
<section class="panel"><div class="panel-head"><div><p class="eyebrow">KJØRETØYKORT</p><h2>{{ trim($vehicle->make.' '.$vehicle->model) ?: 'Kjøretøy' }}</h2><p>Hele historikken følger bilen internt. Kundeportalen avgrenser opplysninger etter kundens eierperiode.</p></div><span class="tag">Nå: {{ $vehicle->customer->name }}</span></div></section>
<section class="grid two"><article class="panel" id="ownership"><div class="panel-head"><div><p class="eyebrow">EIERSKAP</p><h2>Eierperioder</h2></div></div>@forelse($vehicle->ownershipPeriods->sortByDesc('started_at') as $period)<div class="person"><span class="avatar">{{ mb_substr($period->customer->name,0,1) }}</span><div><strong>{{ $period->customer->name }}</strong><p>{{ $period->started_at->format('d.m.Y H:i') }} – {{ $period->ended_at?->format('d.m.Y H:i')??'nå' }}</p></div><span class="status {{ $period->ended_at?'':'completed' }}">{{ $period->ended_at?'Tidligere':'Nåværende' }}</span></div>@empty<p class="empty">Ingen eierperioder.</p>@endforelse</article><article class="panel"><div class="panel-head"><div><p class="eyebrow">HJULSETT</p><h2>{{ $vehicle->tireSets->count() }} registrert</h2></div></div>@forelse($vehicle->tireSets as $set)<a class="person" href="{{ route('tire-sets.show',$set) }}"><div><strong>{{ ['summer'=>'Sommerhjul','winter'=>'Vinterhjul','all_season'=>'Helårshjul'][$set->season]??'Hjulsett' }}</strong><p>{{ $set->code }} · {{ $set->storage_label }}</p></div><span class="status">{{ $set->status }}</span></a>@empty<p class="empty">Ingen hjulsett.</p>@endforelse</article></section>
<section class="panel" id="work"><div class="panel-head"><div><p class="eyebrow">FULL INTERN HISTORIKK</p><h2>Bookinger og arbeidsordrer</h2></div></div>@forelse($bookings as $booking)<div class="person"><div><strong>{{ $booking->starts_at->format('d.m.Y H:i') }} · {{ $booking->service_name }}</strong><p>{{ $booking->customer->name }} · {{ $booking->reference }}</p></div><span class="status {{ $booking->status }}">{{ $booking->status }}</span></div>@empty<p class="empty">Ingen bookinger.</p>@endforelse @foreach($orders as $order)<a class="person" href="{{ route('work-orders.show',$order) }}"><div><strong>{{ $order->reference }} · {{ $order->customer->name }}</strong><p>{{ $order->tasks->where('completed',true)->count() }}/{{ $order->tasks->count() }} kontrollpunkter</p></div><span class="status {{ $order->status }}">{{ $order->status }}</span></a>@endforeach</section>
<section class="panel" id="hotel"><div class="panel-head"><div><p class="eyebrow">AVTALER OG TILBUD</p><h2>Dekkhotellhistorikk</h2></div></div>@forelse($agreements as $agreement)<div class="person"><div><strong>{{ $agreement->customer->name }} · {{ number_format($agreement->price_cents/100,2,',',' ') }} kr</strong><p>{{ $agreement->starts_on->format('d.m.Y') }} – {{ $agreement->ends_on?->format('d.m.Y')??'aktiv' }}</p></div><span class="status {{ $agreement->status==='active'?'completed':'' }}">{{ $agreement->status }}</span></div>@empty<p class="empty">Ingen hotellavtaler.</p>@endforelse @foreach($quotes as $quote)<div class="person"><div><strong>{{ $quote->reference }} · {{ $quote->customer->name }}</strong><p>Tilbud · {{ $quote->created_at->format('d.m.Y') }}</p></div><span class="status {{ $quote->status }}">{{ $quote->status }}</span></div>@endforeach</section>
</x-layouts.app>
