<?php
declare(strict_types=1);

session_start(['cookie_httponly'=>true,'cookie_samesite'=>'Lax','cookie_secure'=>isset($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off']);
header("Content-Security-Policy: default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'none'; img-src 'self' data:; frame-ancestors 'none'; base-uri 'self'; form-action 'self'");
header('X-Content-Type-Options: nosniff'); header('X-Frame-Options: DENY'); header('Referrer-Policy: no-referrer');

$lockFile=__DIR__.'/storage/app/installed.lock';
if(is_file($lockFile)){http_response_code(403);exit('DekkPilot er låst som allerede installert. Dersom dette er en helt ny server og filene ble kopiert fra en lokal installasjon, slett KUN storage/app/installed.lock på serveren og last siden på nytt. Ikke slett låsen dersom databasen allerede er tatt i bruk.');}
if(!isset($_SESSION['install_csrf']))$_SESSION['install_csrf']=bin2hex(random_bytes(32));
$errors=[];$success=false;$databaseWasCreated=false;$previousEnv=null;$envWritten=false;$envPath=__DIR__.'/.env';

function e(string $value):string{return htmlspecialchars($value,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
function envValue(string $value):string{return '"'.str_replace(['\\','"',"\r","\n"],['\\\\','\\"','',''],$value).'"';}
function uuid():string{$d=random_bytes(16);$d[6]=chr((ord($d[6])&0x0f)|0x40);$d[8]=chr((ord($d[8])&0x3f)|0x80);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($d),4));}
function databaseDsn(string $host,int $port,string $socket='',?string $database=null):string{$base=$socket!==''?'mysql:unix_socket='.$socket:'mysql:host='.$host.';port='.$port;return $base.($database!==null?';dbname='.$database:'').';charset=utf8mb4';}
function tableNames(PDO $pdo,string $database):array{$q=$pdo->prepare('SELECT table_name FROM information_schema.tables WHERE table_schema=? AND table_type=\'BASE TABLE\'');$q->execute([$database]);return $q->fetchAll(PDO::FETCH_COLUMN);}
function defaultUrl():string{$https=isset($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off';$scheme=$https?'https':'http';$host=$_SERVER['HTTP_HOST']??'localhost';$path=rtrim(str_replace('\\','/',dirname($_SERVER['SCRIPT_NAME']??'/install.php')),'/');return $scheme.'://'.$host.$path.'/index.php';}

$requirements=[
 'PHP 8.2 eller nyere'=>PHP_VERSION_ID>=80200,
 'PDO MySQL'=>extension_loaded('pdo_mysql'),
 'OpenSSL'=>extension_loaded('openssl'),
 'Mbstring'=>extension_loaded('mbstring'),
 'Composer-pakker'=>is_file(__DIR__.'/vendor/autoload.php'),
 'Skrivbar systemmappe'=>is_writable(__DIR__),
 'Skrivbar storage'=>is_dir(__DIR__.'/storage')&&is_writable(__DIR__.'/storage'),
 'Skrivbar bootstrap/cache'=>is_dir(__DIR__.'/bootstrap/cache')&&is_writable(__DIR__.'/bootstrap/cache'),
];

if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!hash_equals($_SESSION['install_csrf'],(string)($_POST['_token']??'')))$errors[]='Sikkerhetstokenet er utløpt. Last siden på nytt.';
 foreach($requirements as$name=>$ok)if(!$ok)$errors[]=$name.' mangler eller er ikke tilgjengelig.';
 $database=trim((string)($_POST['database']??''));$host=trim((string)($_POST['host']??'127.0.0.1'));$port=(int)($_POST['port']??3306);$username=trim((string)($_POST['username']??''));$password=(string)($_POST['password']??'');$socket=trim((string)($_POST['socket']??''));$sslCa=trim((string)($_POST['ssl_ca']??''));$databaseMode=(string)($_POST['database_mode']??'existing');
 $company=trim((string)($_POST['company']??''));$branch=trim((string)($_POST['branch']??'Hovedavdeling'));$adminName=trim((string)($_POST['admin_name']??''));$adminEmail=strtolower(trim((string)($_POST['admin_email']??'')));$adminPassword=(string)($_POST['admin_password']??'');$appUrl=rtrim(trim((string)($_POST['app_url']??defaultUrl())),'/');
 if(!preg_match('/^[A-Za-z0-9_$-]{1,64}$/',$database))$errors[]='Databasenavnet inneholder tegn MySQL-installasjonen ikke kan bruke.';
 if($host===''||strlen($host)>253||!preg_match('/^[A-Za-z0-9._:-]+$/',$host))$errors[]='Oppgi et gyldig vertsnavn eller en IP-adresse.';
 if($port<1||$port>65535)$errors[]='Porten må være mellom 1 og 65535.';
 if($username===''||strlen($username)>128)$errors[]='Oppgi databasebrukernavn.';
 if(!in_array($databaseMode,['existing','create_if_missing'],true))$errors[]='Ugyldig databasevalg.';
 if($sslCa!==''&&!is_readable($sslCa))$errors[]='SSL CA-filen kan ikke leses av PHP.';
 if($company===''||mb_strlen($company)>255)$errors[]='Oppgi bedriftsnavn.';
 if($branch===''||mb_strlen($branch)>255)$errors[]='Oppgi avdelingsnavn.';
 if($adminName===''||mb_strlen($adminName)>255)$errors[]='Oppgi administratorens navn.';
 if(!filter_var($adminEmail,FILTER_VALIDATE_EMAIL))$errors[]='Oppgi en gyldig e-postadresse.';
 if(strlen($adminPassword)<12||!preg_match('/[a-z]/',$adminPassword)||!preg_match('/[A-Z]/',$adminPassword)||!preg_match('/\d/',$adminPassword))$errors[]='Passordet må være minst 12 tegn og inneholde stor bokstav, liten bokstav og tall.';
 if(!isset($_POST['accept_legal']))$errors[]='Du må godkjenne vilkår, personvern og fakturabetaling før installasjon.';
 if(!filter_var($appUrl,FILTER_VALIDATE_URL)||!in_array(parse_url($appUrl,PHP_URL_SCHEME),['http','https'],true))$errors[]='Oppgi en gyldig HTTP- eller HTTPS-adresse.';

 if(!$errors){
  try{
   $pdoOptions=[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_EMULATE_PREPARES=>false,PDO::ATTR_TIMEOUT=>10];if($sslCa!==''&&defined('PDO::MYSQL_ATTR_SSL_CA'))$pdoOptions[PDO::MYSQL_ATTR_SSL_CA]=$sslCa;
   $server=new PDO(databaseDsn($host,$port,$socket),$username,$password,$pdoOptions);
   $exists=$server->prepare('SELECT COUNT(*) FROM information_schema.schemata WHERE schema_name=?');$exists->execute([$database]);$databaseExists=(bool)$exists->fetchColumn();
   if(!$databaseExists&&$databaseMode==='existing')throw new RuntimeException('Databasen «'.$database.'» finnes ikke, eller brukeren har ikke tilgang. Velg riktig forhåndsopprettet database.');
   if(!$databaseExists){$quoted='`'.str_replace('`','``',$database).'`';$server->exec("CREATE DATABASE {$quoted} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");$databaseWasCreated=true;}
   $db=new PDO(databaseDsn($host,$port,$socket,$database),$username,$password,$pdoOptions);$tables=tableNames($db,$database);
   if($tables&&!in_array('migrations',$tables,true))throw new RuntimeException('Databasen inneholder allerede tabeller som ikke tilhører en DekkPilot-installasjon. Av sikkerhetshensyn blir ingenting overskrevet.');
   if(in_array('organizations',$tables,true)&&(int)$db->query('SELECT COUNT(*) FROM organizations')->fetchColumn()>0)throw new RuntimeException('Databasen inneholder allerede en virksomhet. Bruk oppgradering/migrering i den eksisterende installasjonen, ikke install.php.');
   if(in_array('users',$tables,true)&&(int)$db->query('SELECT COUNT(*) FROM users')->fetchColumn()>0)throw new RuntimeException('Databasen inneholder allerede brukere. Installasjonen stoppes for å beskytte eksisterende data.');

   $key='base64:'.base64_encode(random_bytes(32));$assetUrl=str_ends_with($appUrl,'/index.php')?substr($appUrl,0,-10):$appUrl;$secureCookie=parse_url($appUrl,PHP_URL_SCHEME)==='https'?'true':'false';
   $env="APP_NAME=\"DekkPilot\"\nAPP_ENV=production\nAPP_KEY=".envValue($key)."\nAPP_DEBUG=false\nHASH_DRIVER=argon2id\nAPP_URL=".envValue($appUrl)."\nASSET_URL=".envValue($assetUrl)."\nAPP_LOCALE=nb\nAPP_FALLBACK_LOCALE=nb\nAPP_FAKER_LOCALE=nb_NO\n\nLOG_CHANNEL=stack\nLOG_LEVEL=warning\n\nDB_CONNECTION=mysql\nDB_HOST=".envValue($host)."\nDB_PORT={$port}\nDB_DATABASE=".envValue($database)."\nDB_USERNAME=".envValue($username)."\nDB_PASSWORD=".envValue($password)."\nDB_SOCKET=".envValue($socket)."\nDB_CHARSET=utf8mb4\nDB_COLLATION=utf8mb4_unicode_ci\nMYSQL_ATTR_SSL_CA=".envValue($sslCa)."\n\nSESSION_DRIVER=database\nSESSION_LIFETIME=120\nSESSION_ENCRYPT=true\nSESSION_SECURE_COOKIE={$secureCookie}\nSESSION_SAME_SITE=lax\nQUEUE_CONNECTION=database\nCACHE_STORE=database\nFILESYSTEM_DISK=local\n\nMAIL_MAILER=log\nMAIL_FROM_ADDRESS=".envValue($adminEmail)."\nMAIL_FROM_NAME=".envValue($company)."\n";
   $previousEnv=is_file($envPath)?file_get_contents($envPath):null;$temp=__DIR__.'/.env.installing';if(file_put_contents($temp,$env,LOCK_EX)===false||!rename($temp,$envPath))throw new RuntimeException('Kunne ikke skrive .env. Kontroller filrettighetene.');$envWritten=true;@chmod($envPath,0600);if(is_file(__DIR__.'/bootstrap/cache/config.php'))@unlink(__DIR__.'/bootstrap/cache/config.php');

   require_once __DIR__.'/vendor/autoload.php';$app=require __DIR__.'/bootstrap/app.php';$kernel=$app->make(Illuminate\Contracts\Console\Kernel::class);$kernel->bootstrap();$exit=$kernel->call('migrate',['--force'=>true,'--no-interaction'=>true]);if($exit!==0)throw new RuntimeException('Migrasjonene stoppet: '.$kernel->output());

   $db->beginTransaction();$now=date('Y-m-d H:i:s');
   $stmt=$db->prepare('INSERT INTO organizations (public_id,name,email,timezone,locale,subscription_status,billing_model,created_at,updated_at) VALUES (?,?,?,?,?,\'active\',\'invoice\',?,?)');$stmt->execute([uuid(),$company,$adminEmail,'Europe/Oslo','nb',$now,$now]);$organizationId=(int)$db->lastInsertId();
   $stmt=$db->prepare('INSERT INTO branches (public_id,organization_id,name,code,active,created_at,updated_at) VALUES (?,?,?,?,1,?,?)');$stmt->execute([uuid(),$organizationId,$branch,'HOVED',$now,$now]);$branchId=(int)$db->lastInsertId();
   $hash=password_hash($adminPassword,defined('PASSWORD_ARGON2ID')?PASSWORD_ARGON2ID:PASSWORD_BCRYPT);$isSuperAdmin=$adminEmail==='tordgladnordahl@gmail.com'?1:0;$stmt=$db->prepare('INSERT INTO users (organization_id,branch_id,name,email,password,role,active,is_super_admin,created_at,updated_at) VALUES (?,?,?,?,?,\'owner\',1,?,?,?)');$stmt->execute([$organizationId,$branchId,$adminName,$adminEmail,$hash,$isSuperAdmin,$now,$now]);$userId=(int)$db->lastInsertId();
   $location=$db->prepare('INSERT INTO storage_locations (public_id,organization_id,branch_id,code,zone,location_type,map_x,map_y,map_width,map_height,pick_order,capacity,active,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,18,14,?,20,1,?,?)');foreach(['MOTTAK','A-01','A-02','B-01','B-02']as$i=>$code)$location->execute([uuid(),$organizationId,$branchId,$code,$i===0?'Mottak':substr($code,0,1),$i===0?'receiving':'rack',($i%4)*23+3,intdiv($i,4)*20+5,$i+1,$now,$now]);
   $db->prepare('INSERT INTO service_settings (organization_id,branch_id,minutes_per_wheel,booking_buffer_minutes,quote_expiry_days,created_at,updated_at) VALUES (?,?,8,5,14,?,?)')->execute([$organizationId,$branchId,$now,$now]);
   $service=$db->prepare('INSERT INTO service_products (public_id,organization_id,code,name,category,fixed_price_cents,vat_rate,duration_minutes,active,created_at,updated_at) VALUES (?,?,?,?,?,?,25,?,1,?,?)');foreach([['HOTELL','Dekkhotell','storage',129900,20],['SKIFT','Sesongskift','tire_change',69900,40],['PLUGG','Plugging av dekk','repair',59900,30],['OMLEGG','Omlegging og balansering','workshop',129900,60],['BALANS','Balansering av hjul','workshop',79900,45],['VASK','Hjulvask','other',29900,20],['TPMS','TPMS-service','workshop',49900,30],['ETTER','Etterstramming','other',0,10]]as$s)$service->execute([uuid(),$organizationId,$s[0],$s[1],$s[2],$s[3],$s[4],$now,$now]);
   $legal=$db->prepare('INSERT INTO legal_acceptances (organization_id,user_id,document,version,ip_address,user_agent,accepted_at) VALUES (?,?,?,?,?,?,?)');foreach(['eula','privacy','pricing']as$document)$legal->execute([$organizationId,$userId,$document,'2026-08-09',$_SERVER['REMOTE_ADDR']??null,substr((string)($_SERVER['HTTP_USER_AGENT']??''),0,500),$now]);
   $db->commit();if(!is_dir(dirname($lockFile))&&!mkdir(dirname($lockFile),0750,true))throw new RuntimeException('Kunne ikke opprette installasjonslåsen.');if(file_put_contents($lockFile,json_encode(['installed_at'=>date(DATE_ATOM),'version'=>'0.2.0','database'=>$database],JSON_PRETTY_PRINT),LOCK_EX)===false)throw new RuntimeException('Kunne ikke låse installasjonen.');unset($_SESSION['install_csrf']);$success=true;
  }catch(Throwable$e){if(isset($db)&&$db instanceof PDO&&$db->inTransaction())$db->rollBack();if($envWritten&&$previousEnv!==null)file_put_contents($envPath,$previousEnv,LOCK_EX);elseif($envWritten&&$previousEnv===null&&is_file($envPath))@unlink($envPath);$errors[]=$e->getMessage();}
 }
}
?>
<!doctype html><html lang="nb"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Installer DekkPilot</title><link rel="stylesheet" href="app.css"><style>.installer{max-width:960px;margin:40px auto}.install-head{background:#173a2b;color:white;padding:32px;border-radius:22px 22px 0 0}.install-body{background:white;padding:32px;border:1px solid #e5e9e6;border-radius:0 0 22px 22px}.install-grid{display:grid;grid-template-columns:1fr 1fr;gap:28px}.mode{display:flex;gap:10px;align-items:flex-start;border:1px solid #dce2de;border-radius:12px;padding:12px;margin:8px 0}.mode input{width:auto;margin-top:4px}.mode span{display:grid}.requirements{display:flex;gap:8px;flex-wrap:wrap;margin:18px 0}.requirements span{padding:5px 9px;border-radius:20px;background:#daf3e5;color:#155c3b;font-size:12px}.requirements .bad{background:#fbe4e1;color:#8b3025}.success-box{text-align:center;padding:40px}.fine{text-align:left}@media(max-width:700px){.installer{margin:10px}.install-grid{grid-template-columns:1fr}}</style></head><body><main class="installer"><header class="install-head"><div class="brand"><span class="brandmark">D</span><span>DekkPilot<small>Sikker førstegangsinstallasjon</small></span></div><h1>Koble DekkPilot til MySQL</h1><p>Bruk helst en tom database som allerede er opprettet av hostingleverandøren.</p></header><section class="install-body">
<div class="requirements"><?php foreach($requirements as$name=>$ok):?><span class="<?=$ok?'':'bad'?>"><?=$ok?'✓':'×'?> <?=e($name)?></span><?php endforeach?></div>
<?php if($success):?><div class="success-box"><span class="stat-icon green" style="margin:auto">✓</span><h1>Alt er klart</h1><p>Alle migrasjoner, standardtjenester, lagerplasser og administratorkontoen er opprettet.</p><a class="button" href="<?=e($appUrl.'/login')?>">Gå til innlogging →</a><p class="fine">Av sikkerhetsgrunner bør install.php slettes eller blokkeres i webserveren etter kontroll.</p></div><?php else:?>
<?php if($errors):?><div class="errors"><strong>Installasjonen ble stoppet uten å overskrive data:</strong><ul><?php foreach($errors as$error):?><li><?=e($error)?></li><?php endforeach?></ul></div><?php endif?>
<form method="post" class="stack"><input type="hidden" name="_token" value="<?=e($_SESSION['install_csrf'])?>"><div class="install-grid"><div><p class="eyebrow">1 · DATABASE</p><h2>MySQL-tilkobling</h2><label class="mode"><input type="radio" name="database_mode" value="existing" <?=($_POST['database_mode']??'existing')==='existing'?'checked':''?>><span><strong>Bruk eksisterende database</strong><small>Anbefalt for webhotell og drift. Databasen må være tom.</small></span></label><label class="mode"><input type="radio" name="database_mode" value="create_if_missing" <?=($_POST['database_mode']??'')==='create_if_missing'?'checked':''?>><span><strong>Opprett bare hvis den mangler</strong><small>Krever CREATE DATABASE-rettighet. Eksisterende database slettes aldri.</small></span></label><label>Databasenavn<input name="database" value="<?=e((string)($_POST['database']??'dekkpilot'))?>" required maxlength="64"></label><div class="fields"><label>Databasevert<input name="host" value="<?=e((string)($_POST['host']??'127.0.0.1'))?>" required></label><label>Port<input type="number" name="port" value="<?=(int)($_POST['port']??3306)?>" min="1" max="65535" required></label></div><div class="fields"><label>Brukernavn<input name="username" value="<?=e((string)($_POST['username']??''))?>" required autocomplete="username"></label><label>Passord<input type="password" name="password" autocomplete="new-password"></label></div><details><summary>Avanserte tilkoblingsvalg</summary><label>Unix socket – normalt tom på server<input name="socket" value="<?=e((string)($_POST['socket']??''))?>" placeholder="/path/to/mysql.sock"></label><label>SSL CA-fil – valgfritt<input name="ssl_ca" value="<?=e((string)($_POST['ssl_ca']??''))?>" placeholder="/path/to/ca.pem"></label></details><label>Systemadresse<input type="url" name="app_url" value="<?=e((string)($_POST['app_url']??defaultUrl()))?>" required><small>Ta med /index.php bare dersom serveren ikke bruker pene URL-er.</small></label></div>
<div><p class="eyebrow">2 · FØRSTE KONTO</p><h2>Virksomheten</h2><label>Bedriftsnavn<input name="company" value="<?=e((string)($_POST['company']??''))?>" required></label><label>Avdeling<input name="branch" value="<?=e((string)($_POST['branch']??'Hovedavdeling'))?>" required></label><label>Administratorens navn<input name="admin_name" value="<?=e((string)($_POST['admin_name']??''))?>" required></label><label>E-post<input type="email" name="admin_email" value="<?=e((string)($_POST['admin_email']??''))?>" required autocomplete="email"></label><label>Passord<input type="password" name="admin_password" required minlength="12" autocomplete="new-password"><small>Minst 12 tegn med stor bokstav, liten bokstav og tall.</small></label><label class="mode"><input type="checkbox" name="accept_legal" value="1" <?=isset($_POST['accept_legal'])?'checked':''?> required><span><strong>Jeg godkjenner avtalegrunnlaget</strong><small><a href="index.php/vilkar" target="_blank">Brukervilkår/EULA</a>, <a href="index.php/personvern" target="_blank">personvern</a> og abonnement til 249 kr/mnd. fakturert med faktura. SMS faktureres etter bruk.</small></span></label><div class="booking-guidance"><strong>Trygg kontroll før installasjon</strong><br>Databasen undersøkes først. Har den virksomheter, brukere eller ukjente tabeller, stopper installasjonen uten å overskrive noe.</div></div></div><button class="button full">Kontroller og installer DekkPilot</button></form><?php endif?></section></main></body></html>
