<?php
declare(strict_types=1);
ini_set('display_errors','0');
session_name('dekkpilot_recovery');
session_set_cookie_params(['httponly'=>true,'secure'=>!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off','samesite'=>'Strict','path'=>'/']);
session_start();
header('X-Robots-Tag: noindex, nofollow');header('X-Frame-Options: DENY');header("Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; form-action 'self'; base-uri 'none'");header('Referrer-Policy: no-referrer');header('Cache-Control: no-store');

$envPath=__DIR__.'/.env';$csrf=$_SESSION['csrf']??=bin2hex(random_bytes(32));$message='';$error='';$details='';$success=false;$verifiedSuperadmin=false;
function h(string$v):string{return htmlspecialchars($v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
function envValue(string$path,string$key,string$default=''):string{if(!is_readable($path))return$default;$text=(string)file_get_contents($path);if(!preg_match('/^'.preg_quote($key,'/').'=(.*)$/m',$text,$m))return$default;$v=trim($m[1]);if(strlen($v)>1&&(($v[0]==='"'&&str_ends_with($v,'"'))||($v[0]==="'"&&str_ends_with($v,"'"))))$v=substr($v,1,-1);return stripcslashes($v);}
function quoted(string$v):string{if(preg_match('/[\r\n\0]/',$v))throw new RuntimeException('Feltene kan ikke inneholde linjeskift.');return'"'.str_replace(['\\','"'],['\\\\','\\"'],$v).'"';}
function writeEnv(string$path,array$values):void{if(!is_file($path)||!is_readable($path)||!is_writable($path))throw new RuntimeException('.env finnes ikke eller er ikke skrivbar av PHP.');$text=(string)file_get_contents($path);$backup=$path.'.backup-'.date('Ymd-His');if(!copy($path,$backup))throw new RuntimeException('Kunne ikke sikkerhetskopiere .env.');@chmod($backup,0600);foreach($values as$key=>$value){$line=$key.'='.quoted((string)$value);$pattern='/^'.preg_quote($key,'/').'=.*$/m';$text=preg_match($pattern,$text)?(string)preg_replace($pattern,$line,$text,1):rtrim($text).PHP_EOL.$line.PHP_EOL;}$tmp=$path.'.tmp-'.bin2hex(random_bytes(4));if(file_put_contents($tmp,$text,LOCK_EX)===false)throw new RuntimeException('Kunne ikke skrive konfigurasjonen.');@chmod($tmp,0600);if(!rename($tmp,$path)){@unlink($tmp);throw new RuntimeException('Kunne ikke erstatte .env.');}@chmod($path,0600);foreach(glob(__DIR__.'/bootstrap/cache/config*.php')?:[]as$file)@unlink($file);}
function attemptsBlocked():bool{return(int)($_SESSION['attempts']??0)>=8&&time()-(int)($_SESSION['last_attempt']??0)<900;}
function attempt():void{$_SESSION['attempts']=(int)($_SESSION['attempts']??0)+1;$_SESSION['last_attempt']=time();}
function recoveryAvailable():bool{$lock=__DIR__.'/storage/app/database-recovery.lock';$uploaded=@filemtime(__FILE__)?:0;if(time()-$uploaded>3600)return false;if(!is_file($lock))return true;return$uploaded>(int)trim((string)file_get_contents($lock));}
function clearCompiledFiles():array{$removed=0;$failed=[];foreach([__DIR__.'/storage/framework/views/*.php',__DIR__.'/bootstrap/cache/*.php']as$pattern){foreach(glob($pattern)?:[]as$file){if(basename($file)==='.gitignore')continue;if(@unlink($file)){$removed++;}else{$failed[]=$file;}}}if(function_exists('opcache_reset'))@opcache_reset();return[$removed,$failed];}
function parseDatabaseUrl(string$url,string$currentDatabase,string$currentPort):array{$url=trim($url);if($url==='')throw new RuntimeException('Database-URL må fylles ut.');$candidate=str_contains($url,'://')?$url:'mysql://'.$url;$parts=parse_url($candidate);if($parts===false||empty($parts['host']))throw new RuntimeException('URL-en må være host, host:port/database eller mysql://host:port/database.');$host=(string)$parts['host'];$port=(int)($parts['port']??($currentPort!==''?$currentPort:3306));$database=trim((string)($parts['path']??''),'/');if($database==='')$database=$currentDatabase;if($database===''||!preg_match('/^[A-Za-z0-9_$.-]+$/',$database))throw new RuntimeException('Databasenavn mangler. Ta det med i URL-en, for eksempel host:3306/databasenavn.');return[$host,$port,$database];}

// Kan brukes uten fungerende Laravel/DB, men bare i én time etter at filen er
// lastet opp. Etter vellykket lagring låses funksjonen til filen lastes opp igjen.
if($_SERVER['REQUEST_METHOD']==='POST'&&($_POST['action']??'')==='save_database'){
 if(!recoveryAvailable()){$error='Databaseendring er låst. Last opp update.php på nytt for å åpne et nytt 60-minutters gjenopprettingsvindu.';}
 elseif(attemptsBlocked()){http_response_code(429);$error='For mange forsøk. Vent 15 minutter.';}
 elseif(!hash_equals($csrf,(string)($_POST['_token']??''))){http_response_code(419);$error='Skjemaet er utløpt. Last siden på nytt.';}
 else{attempt();try{$url=trim((string)($_POST['db_url']??''));$username=trim((string)($_POST['db_username']??''));$password=(string)($_POST['db_password']??'');if($username==='')throw new RuntimeException('Databasebruker må fylles ut.');[$host,$port,$database]=parseDatabaseUrl($url,envValue($envPath,'DB_DATABASE'),envValue($envPath,'DB_PORT','3306'));$pdo=new PDO('mysql:host='.$host.';port='.$port.';dbname='.$database.';charset=utf8mb4',$username,$password,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_TIMEOUT=>8]);$pdo->query('SELECT 1');writeEnv($envPath,['DB_CONNECTION'=>'mysql','DB_URL'=>'','DB_HOST'=>$host,'DB_PORT'=>(string)$port,'DB_DATABASE'=>$database,'DB_USERNAME'=>$username,'DB_PASSWORD'=>$password,'DB_SOCKET'=>'']);$lock=__DIR__.'/storage/app/database-recovery.lock';file_put_contents($lock,(string)(@filemtime(__FILE__)?:time()),LOCK_EX);@chmod($lock,0600);$_SESSION['attempts']=0;$_SESSION['database_saved']='Databasekoblingen er testet og lagret. Kjør nå databaseoppdateringen.';header('Location: '.($_SERVER['PHP_SELF']??'update.php'),true,303);exit;}catch(Throwable$e){$error='Databaseoppsettet ble ikke lagret: '.$e->getMessage();}}
}

require __DIR__.'/vendor/autoload.php';
use App\Services\SuperAdminDiagnostics;use Illuminate\Contracts\Console\Kernel;use Illuminate\Support\Facades\Artisan;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Hash;
$app=require __DIR__.'/bootstrap/app.php';$app->make(Kernel::class)->bootstrap();
if(isset($_SESSION['database_saved'])){$message=(string)$_SESSION['database_saved'];unset($_SESSION['database_saved']);}
if($_SERVER['REQUEST_METHOD']==='POST'&&($_POST['action']??'')==='migrate'){
 if(attemptsBlocked()){http_response_code(429);$error='For mange forsøk. Vent 15 minutter.';}
 elseif(!hash_equals($csrf,(string)($_POST['_token']??''))){http_response_code(419);$error='Skjemaet er utløpt. Last siden på nytt.';}
 else{attempt();try{$user=DB::table('users')->whereRaw('LOWER(email)=?',[strtolower(trim((string)($_POST['email']??'')))])->first(['id','password','is_super_admin','active']);if(!$user||!(bool)$user->is_super_admin||!(bool)$user->active||!Hash::check((string)($_POST['password']??''),(string)$user->password)){usleep(350000);throw new RuntimeException('E-post eller passord er feil, eller kontoen er ikke superadmin.');}$verifiedSuperadmin=true;$_SESSION['attempts']=0;$lock=fopen(storage_path('app/system-update.lock'),'c+');if(!$lock||!flock($lock,LOCK_EX|LOCK_NB))throw new RuntimeException('En oppdatering kjører allerede.');try{$exit=Artisan::call('migrate',['--force'=>true,'--no-interaction'=>true]);if($exit!==0)throw new RuntimeException('Migreringen returnerte feilkode '.$exit.'.');try{Artisan::call('optimize:clear');}catch(Throwable$cacheError){report($cacheError);}[$removed,$failed]=clearCompiledFiles();if($failed)throw new RuntimeException('Kunne ikke tømme alle cachefiler. Kontroller skrivetilgang til storage/framework/views og bootstrap/cache.');$message='Databasen er oppdatert. '.$removed.' kompilerte cachefiler ble fjernet, og PHP OPcache ble nullstilt.';$success=true;if(isset($_POST['diagnostics']))app(SuperAdminDiagnostics::class)->set(true);}finally{flock($lock,LOCK_UN);fclose($lock);}}catch(Throwable$e){report($e);$error=$e->getMessage();if($verifiedSuperadmin)$details=app(SuperAdminDiagnostics::class)->latest(50000);}}
}
$base=rtrim(str_replace('\\','/',dirname($_SERVER['SCRIPT_NAME']??'/update.php')),'/');$host=envValue($envPath,'DB_HOST','127.0.0.1');$port=envValue($envPath,'DB_PORT','3306');$database=envValue($envPath,'DB_DATABASE');$suggested=$host.($port!==''?':'.$port:'').($database!==''?'/'.$database:'');
?><!doctype html><html lang="nb"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>DekkPilot nødoppdatering</title><style>body{margin:0;background:#eef3f0;color:#15201b;font:15px/1.5 system-ui,sans-serif}.card{width:min(720px,calc(100% - 28px));margin:5vh auto;background:#fff;border:1px solid #dfe6e2;border-radius:20px;padding:28px;box-sizing:border-box;box-shadow:0 20px 60px #173a2b20}h1{margin:2px 0}.eyebrow{color:#267452;font-size:11px;font-weight:800;letter-spacing:1px}.notice{padding:13px;border-radius:11px;background:#fff3df;margin:14px 0}.error{background:#fbe3df;color:#8b3025}.success{background:#dff4e9;color:#176541}form{display:grid;gap:14px;margin-top:20px}label{display:grid;gap:5px;font-weight:700;font-size:12px}input{padding:12px;border:1px solid #ccd8d1;border-radius:10px;font:inherit}.check{display:flex;gap:8px}.check input{width:auto}button,a.button{display:inline-flex;justify-content:center;border:0;border-radius:10px;padding:12px 16px;background:#176541;color:#fff;font-weight:800;text-decoration:none;cursor:pointer}details{margin:20px 0;border:1px solid #dce5e0;border-radius:14px;padding:14px}summary{cursor:pointer;color:#176541;font-weight:850}.help{color:#64736b;font-size:12px}pre{max-height:320px;overflow:auto;padding:13px;border-radius:10px;background:#101b16;color:#d9eee3;white-space:pre-wrap;font-size:11px}</style></head><body><main class="card"><p class="eyebrow">SIKKER GJENOPPRETTING</p><h1>DekkPilot systemoppdatering</h1><p>Rett databasekoblingen og installer deretter ventende databaseoppdateringer.</p><?php if($message):?><div class="notice success"><?=h($message)?></div><?php endif?><?php if($error):?><div class="notice error"><strong>Handlingen stoppet</strong><br><?=h($error)?></div><?php endif?>
<details <?=isset($_GET['database'])||str_contains($error,'Database')?'open':''?>><summary>1. Endre databasekobling</summary><p class="help">Kun URL, databasebruker og databasepassord kreves. URL kan være <code>host:3306/databasenavn</code> eller <code>mysql://host:3306/databasenavn</code>. Skjemaet låses etter vellykket lagring.</p><?php if(recoveryAvailable()):?><form method="post"><input type="hidden" name="_token" value="<?=h($csrf)?>"><input type="hidden" name="action" value="save_database"><label>Database-URL / host<input name="db_url" value="<?=h($suggested)?>" placeholder="db.example.no:3306/databasenavn" required></label><label>Databasebruker<input name="db_username" value="<?=h(envValue($envPath,'DB_USERNAME'))?>" autocomplete="off" required></label><label>Databasepassord<input type="password" name="db_password" autocomplete="new-password"></label><button>Test og lagre databasekobling</button></form><?php else:?><div class="notice">Databaseendring er låst. Last opp denne <code>update.php</code>-filen på nytt dersom du må åpne et nytt 60-minutters vindu.</div><?php endif?></details>
<?php if(!$success):?><form method="post"><input type="hidden" name="_token" value="<?=h($csrf)?>"><input type="hidden" name="action" value="migrate"><h2>2. Installer databaseoppdateringer</h2><label>Superadmin e-post<input type="email" name="email" autocomplete="username" required></label><label>Passord<input type="password" name="password" autocomplete="current-password" required></label><label class="check"><input type="checkbox" name="diagnostics" value="1"> Slå på sikker diagnosevisning etter oppdateringen</label><button>Kontroller og installer databaseoppdateringer</button></form><?php else:?><p><a class="button" href="<?=h($base)?>/index.php/login">Gå til innlogging</a></p><?php endif?><?php if($details):?><h2>Maskert feillogg</h2><pre><?=h($details)?></pre><?php endif?></main></body></html>
