<?php
namespace App\Services;use RuntimeException;use ZipArchive;
class TabularImportReader
{
 public function read(string $path,string $type,int $limit=5001):array{return $type==='csv'?$this->csv($path,$limit):$this->xlsx($path,$limit);}
 private function csv(string $path,int $limit):array{$handle=fopen($path,'rb');if(!$handle)throw new RuntimeException('Kunne ikke lese CSV-filen.');$sample=(string)fgets($handle);rewind($handle);$delimiter=$this->delimiter($sample);$rows=[];while(($row=fgetcsv($handle,0,$delimiter,'"','\\'))!==false&&count($rows)<$limit){$rows[]=array_map(fn($v)=>trim(mb_convert_encoding((string)$v,'UTF-8','UTF-8, ISO-8859-1, Windows-1252')),$row);}fclose($handle);return $this->normalize($rows);}
 private function delimiter(string $line):string{$scores=[];foreach([','=>',',';'=>';',"\t"=>"\t"]as$key=>$value)$scores[$value]=substr_count($line,$value);arsort($scores);return (string)array_key_first($scores);}
 private function xlsx(string $path,int $limit):array{$zip=new ZipArchive;if($zip->open($path)!==true)throw new RuntimeException('Excel-filen er ugyldig eller passordbeskyttet.');if($zip->numFiles>1000)throw new RuntimeException('Excel-filen inneholder for mange elementer.');$total=0;for($i=0;$i<$zip->numFiles;$i++){$stat=$zip->statIndex($i);$total+=(int)($stat['size']??0);if($total>50_000_000){$zip->close();throw new RuntimeException('Excel-filen er for stor når den pakkes ut.');}}$shared=[];$sharedXml=$this->zipEntry($zip,'xl/sharedStrings.xml',15_000_000,false);if($sharedXml!==false){$xml=simplexml_load_string($sharedXml,'SimpleXMLElement',LIBXML_NONET|LIBXML_NOERROR|LIBXML_NOWARNING);if($xml===false){$zip->close();throw new RuntimeException('Excel-filen inneholder ugyldig tekstdata.');}foreach($xml->si??[]as$item){$shared[]=mb_substr(trim(implode('',array_map('strval',$item->xpath('.//t')?:[]))),0,10000);if(count($shared)>100000){$zip->close();throw new RuntimeException('Excel-filen inneholder for mange delte tekstverdier.');}}}$sheet=$this->zipEntry($zip,'xl/worksheets/sheet1.xml',25_000_000,true);$xml=simplexml_load_string($sheet,'SimpleXMLElement',LIBXML_NONET|LIBXML_NOERROR|LIBXML_NOWARNING);if($xml===false){$zip->close();throw new RuntimeException('Første arbeidsark inneholder ugyldig XML.');}$rows=[];foreach($xml->sheetData->row??[]as$row){$values=[];foreach($row->c as$cell){$reference=(string)$cell['r'];preg_match('/^[A-Z]+/',$reference,$match);$index=$this->columnIndex($match[0]??'A');if($index>99)continue;$type=(string)$cell['t'];$value=$type==='inlineStr'?trim(implode('',array_map('strval',$cell->xpath('.//t')?:[]))):(string)$cell->v;if($type==='s')$value=$shared[(int)$value]??'';$values[$index]=mb_substr(trim($value),0,10000);}if($values){$max=max(array_keys($values));$rows[]=array_map(fn($i)=>$values[$i]??'',range(0,$max));}if(count($rows)>=$limit)break;}$zip->close();return$this->normalize($rows);}
 private function zipEntry(ZipArchive $zip,string$name,int$max,bool$required):string|false{$stat=$zip->statName($name);if($stat===false){if($required){$zip->close();throw new RuntimeException('Fant ikke første arbeidsark i Excel-filen.');}return false;}if((int)($stat['size']??0)>$max){$zip->close();throw new RuntimeException('Excel-filen inneholder et element som er for stort.');}$content=$zip->getFromName($name);if($content===false&&$required){$zip->close();throw new RuntimeException('Kunne ikke lese Excel-filen.');}return$content;}
 private function columnIndex(string $letters):int{$number=0;foreach(str_split($letters)as$letter)$number=$number*26+(ord($letter)-64);return $number-1;}
 private function normalize(array $rows):array{while($rows&&count(array_filter(end($rows),fn($v)=>$v!==''))===0)array_pop($rows);if(!$rows)throw new RuntimeException('Filen inneholder ingen data.');$headers=array_map(fn($v)=>trim((string)$v),array_shift($rows));if(count(array_filter($headers))<2)throw new RuntimeException('Første rad må inneholde minst to kolonneoverskrifter.');$data=[];foreach($rows as$row){$record=[];foreach($headers as$i=>$header)if($header!=='')$record[$header]=trim((string)($row[$i]??''));if(count(array_filter($record,fn($v)=>$v!=='')))$data[]=$record;}return ['headers'=>array_values(array_filter($headers,fn($v)=>$v!=='')),'rows'=>$data];}
}
