<?php
namespace App\Services;
use App\Models\Customer;use App\Models\StorageLocation;use App\Models\TireSet;use App\Models\Vehicle;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;use RuntimeException;
class TenantDataImporter{
 public const FIELDS=['customer_name'=>'Kundenavn','customer_email'=>'E-post','customer_phone'=>'Telefon','customer_type'=>'Kundetype','organization_number'=>'Organisasjonsnummer','address'=>'Adresse','postal_code'=>'Postnummer','registration_number'=>'Registreringsnummer','make'=>'Bilmerke','model'=>'Bilmodell','model_year'=>'Årsmodell','vin'=>'VIN / understellsnummer','tire_season'=>'Dekksesong','tire_size'=>'Dekkdimensjon','tire_brand'=>'Dekkmerke','tread_depth'=>'Mønsterdybde mm','dot_year'=>'DOT-år','storage_code'=>'Lagerplass'];
 private const ALIASES=['customer_name'=>['kundenavn','kunde','navn','customer name','name'],'customer_email'=>['e-post','epost','email','kunde epost'],'customer_phone'=>['telefon','mobil','phone'],'customer_type'=>['kundetype','type'],'organization_number'=>['organisasjonsnummer','orgnr','org nr'],'address'=>['adresse','gateadresse','address'],'postal_code'=>['postnummer','postnr','post nr','postal code','zip','zipcode'],'registration_number'=>['registreringsnummer','regnr','reg nr','kjennemerke','registration number'],'make'=>['bilmerke','merke','make'],'model'=>['bilmodell','modell','model'],'model_year'=>['årsmodell','arsmodell','modellår','model year'],'vin'=>['vin','understellsnummer'],'tire_season'=>['dekksesong','sesong','season'],'tire_size'=>['dekkdimensjon','dimensjon','dekk størrelse','tire size'],'tire_brand'=>['dekkmerke','dekkprodusent','tire brand'],'tread_depth'=>['mønsterdybde','monsterdybde','mm','tread depth'],'dot_year'=>['dot-år','dot år','dot','dot year'],'storage_code'=>['lagerplass','lokasjon','plassering','storage']];
 public function __construct(private readonly PostalCodeService $postalCodes){}
 public function detect(array$headers):array{$mapping=[];foreach(self::FIELDS as$field=>$label)foreach($headers as$header){if(in_array(mb_strtolower(trim($header)),self::ALIASES[$field]??[],true)){$mapping[$field]=$header;break;}}return$mapping;}
 public function run(array$rows,array$mapping,int$org,int$branch):array{$errors=[];$imported=0;foreach($rows as$index=>$row){try{DB::transaction(fn()=>$this->row($row,$mapping,$org,$branch));$imported++;}catch(\Throwable$e){$errors[]='Rad '.($index+2).': '.mb_substr($e->getMessage(),0,300);}}return['imported'=>$imported,'failed'=>count($errors),'errors'=>array_slice($errors,0,100)];}
 private function row(array$row,array$map,int$org,int$branch):void{$value=fn($field)=>trim((string)($row[$map[$field]??'']??''));$name=$value('customer_name');if($name==='')throw new RuntimeException('Kundenavn mangler.');$postal=$value('postal_code');$city=$this->postalCodes->city($postal);if(!$city)throw new RuntimeException('Gyldig norsk postnummer mangler.');$email=strtolower($value('customer_email'));$customer=$email!==''?Customer::withTrashed()->where('organization_id',$org)->where('email',$email)->first():null;$address=['address'=>$value('address')?:null,'postal_code'=>$postal,'city'=>$city];if(!$customer){$next=(int)Customer::withTrashed()->where('organization_id',$org)->max('id')+1;$customer=Customer::create(['public_id'=>(string)Str::uuid(),'organization_id'=>$org,'branch_id'=>$branch,'customer_number'=>'K'.str_pad((string)$next,6,'0',STR_PAD_LEFT),'type'=>$this->customerType($value('customer_type')),'name'=>$name,'email'=>$email?:null,'phone'=>$value('customer_phone')?:null,'organization_number'=>$value('organization_number')?:null,'notes'=>'[IMPORT]',...$address]);}else{if($customer->trashed())$customer->restore();$customer->update($address);}$reg=strtoupper(preg_replace('/[^A-Z0-9]/i','',$value('registration_number')));if($reg==='')return;$vehicle=Vehicle::withTrashed()->where('organization_id',$org)->where('registration_number',$reg)->first();$vehicleData=['customer_id'=>$customer->id,'make'=>$value('make')?:null,'model'=>$value('model')?:null,'model_year'=>$this->integer($value('model_year'),1900,(int)date('Y')+2),'vin'=>$value('vin')?:null,'recommended_tire_size'=>$value('tire_size')?:null];if($vehicle){if($vehicle->trashed())$vehicle->restore();$vehicle->update($vehicleData);}else{$vehicle=Vehicle::create(['public_id'=>(string)Str::uuid(),'organization_id'=>$org,'registration_number'=>$reg,...$vehicleData]);}if($value('tire_size')==='')return;$location=$value('storage_code')!==''?StorageLocation::where('organization_id',$org)->where('code',$value('storage_code'))->first():null;TireSet::firstOrCreate(['organization_id'=>$org,'vehicle_id'=>$vehicle->id,'season'=>$this->season($value('tire_season')),'size'=>$value('tire_size')],['public_id'=>(string)Str::uuid(),'storage_location_id'=>$location?->id,'code'=>'HJ-I'.strtoupper(Str::random(7)),'kind'=>'complete_wheels','manufacturer'=>$value('tire_brand')?:null,'quantity'=>4,'minimum_tread_depth'=>$this->decimal($value('tread_depth'),0,20),'dot_year'=>$this->integer($value('dot_year'),1990,(int)date('Y')),'status'=>$location?'stored':'received','condition_notes'=>'[IMPORT]','received_at'=>now()]);}
 private function customerType(string$v):string{return in_array(mb_strtolower($v),['business','bedrift','firma','company'],true)?'business':'private';}private function season(string$v):string{return match(mb_strtolower($v)){'vinter','winter'=>'winter','helår','helar','all season','all_season'=>'all_season',default=>'summer'};}private function integer(string$v,int$min,int$max):?int{if($v==='')return null;$n=(int)$v;return$n>=$min&&$n<=$max?$n:null;}private function decimal(string$v,float$min,float$max):?float{if($v==='')return null;$n=(float)str_replace(',','.',$v);return$n>=$min&&$n<=$max?$n:null;}
}
