<x-layouts.app title="Min arbeidsdag · DekkPilot" heading="Min arbeidsdag">
<link rel="stylesheet" href="{{ asset('workday-fixes.css') }}?v=20260813-2">
<link rel="stylesheet" href="{{ in_array(request()->getHost(),['localhost','127.0.0.1','::1'],true) ? route('system.asset',['filename'=>'workday-intake.css']) : asset('workday-intake.css') }}?v=20260812-1">
<style>.intake-measure{display:flex;align-items:end;gap:5px}.intake-measure label{display:grid;gap:2px}.intake-measure label span{color:var(--muted);font-size:8px;font-weight:850}.intake-measure input{width:58px;min-height:36px;padding:7px;font-size:12px}@media(max-width:600px){.intake-measure{display:grid;grid-template-columns:repeat(4,1fr)}.intake-measure input{width:100%}.intake-measure .button{grid-column:1/-1}}</style>
<section class="workday-hero panel"><div><p class="eyebrow">{{ auth()->user()->name }}</p><h2>{{ $myToday->count() }} timer satt av til deg i dag</h2><p>Skann én etikett for hele hjulsettet. DekkPilot holder oversikt over resten.</p></div><form method="get" action="{{ route('workday') }}" class="scan-bar"><label>Skann eller skriv hjulkode<input name="code" value="{{ $scanCode }}" placeholder="HJ-XXXXXXXX" autocomplete="off" autofocus data-scan-input></label><button class="button">Finn hjulsett</button><button class="button ghost" type="button" data-camera-open>▣ Bruk kamera</button></form></section>
<nav class="workday-sections" aria-label="Arbeidsområder"><a class="{{ $area==='schedule'?'active':'' }}" href="{{ route('workday',['area'=>'schedule','schedule'=>$scheduleMode]) }}"><span class="workday-section-icon">◷</span><span><small>I DAG</small><strong>Timebok</strong><b>{{ $allToday->count() }} timer · {{ $myToday->count() }} mine</b></span><i>→</i></a><a class="{{ $area==='preparation'?'active':'' }}" href="{{ route('workday',['area'=>'preparation','prep'=>$prepMode]) }}"><span class="workday-section-icon amber">⇣</span><span><small>FREMOVER</small><strong>Må klargjøres</strong><b>{{ $preparationBookings->count() }} timer i valgt periode</b></span><i>→</i></a><a class="{{ $area==='cleanup'?'active':'' }}" href="{{ route('workday',['area'=>'cleanup']) }}"><span class="workday-section-icon blue">✓</span><span><small>MOTTAK</small><strong>Må ryddes</strong><b>{{ $intakeSets->count() }} hjulsett</b></span><i>→</i></a></nav>
@if($scanCode && !$scanned)<div class="errors">Fant ikke hjulkoden «{{ $scanCode }}». Kontroller etiketten og prøv igjen.</div>@endif
@if($scanned)<section class="panel scanned-set"><div class="scan-success">✓ Hjulsett funnet</div><div class="scanned-grid"><div><small>REGISTRERINGSNUMMER</small><strong class="scan-registration">{{ $scanned->vehicle->registration_number }}</strong><span>{{ $scanned->vehicle->customer->name }}</span></div><div><small>PLASSERING</small><strong>{{ $scanned->storageLocation?->code ?? 'MOTTAK' }}{{ $scanned->storage_shelf_number?' · Hylle '.$scanned->storage_shelf_number:'' }}</strong><span>{{ $scanned->code }}</span><a href="{{ route('warehouse.map',['q'=>$scanned->code]) }}">Vis på kart →</a></div><div><small>HJULSETT</small><strong>{{ $scanned->manufacturer }} {{ $scanned->size }}</strong><span>{{ $scanned->season==='winter'?'Vinter':'Sommer' }} · {{ $scanned->quantity }} hjul</span></div><div><small>STATUS</small><strong>{{ ['received'=>'Mottatt','stored'=>'På lager','picked'=>'Lagt klart','workshop'=>'På verksted','delivered'=>'Utlevert'][$scanned->status] }}</strong><span>Én handling gjelder hele settet</span></div></div><div class="workflow-actions">@foreach(['picked'=>'1. Lagt klart','workshop'=>'2. Til verksted','stored'=>'3. Tilbake på lager','delivered'=>'4. Utlevert'] as $status=>$label)<form method="post" action="{{ route('workday.move',$scanned) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="{{ $status }}"><button>{{ $label }}</button></form>@endforeach</div></section>@endif
@if($area==='cleanup')<section class="panel intake-queue" id="cleanup"><div class="panel-head"><div><p class="eyebrow">MÅ RYDDES</p><h2>Hjul som skal inn på lager</h2><p>Viser mottatte hjul som ikke skal ut de neste fem dagene. Gjør bare neste steg.</p></div><span class="status">{{ $intakeSets->count() }}</span></div>
@forelse($intakeSets as $set)
 @php($step = !in_array($set->wash_status,['washed','not_needed'],true) ? 'wash' : ($set->minimum_tread_depth===null ? 'measure' : 'place'))
 <article class="intake-card"><div class="intake-main"><span class="intake-season">{{ $set->season==='winter'?'Vinter':'Sommer' }}</span><div><strong>{{ $set->vehicle->registration_number }}</strong><small>{{ $set->vehicle->customer->name }} · {{ $set->code }} · mottatt {{ $set->received_at->format('d.m') }}</small></div></div><ol class="intake-progress"><li class="{{ $step==='wash'?'active':'done' }}">1 Vask</li><li class="{{ $step==='measure'?'active':($step==='place'?'done':'') }}">2 Mål</li><li class="{{ $step==='place'?'active':'' }}">3 Plasser</li></ol><div class="intake-next">
 @if($step==='wash'&&$set->wash_status==='needed')<div><small>NESTE STEG</small><strong>Vask hjulsettet</strong></div><form method="post" action="{{ route('workday.intake-step',$set) }}">@csrf @method('PATCH')<input type="hidden" name="action" value="washed"><button class="button">✓ Ferdig vasket</button></form>
 @elseif($step==='wash')<div><small>NESTE STEG</small><strong>Trenger hjulene vask?</strong></div><div class="intake-buttons"><form method="post" action="{{ route('workday.intake-step',$set) }}">@csrf @method('PATCH')<input type="hidden" name="action" value="wash_needed"><button class="button">Ja, må vaskes</button></form><form method="post" action="{{ route('workday.intake-step',$set) }}">@csrf @method('PATCH')<input type="hidden" name="action" value="skip_wash"><button class="button ghost">Nei, fortsett</button></form></div>
 @elseif($step==='measure')<div><small>NESTE STEG</small><strong>Mål alle fire hjul</strong></div><details class="intake-car-control"><summary>Åpne visuell måling →</summary><form method="post" action="{{ route('workday.intake-step',$set) }}">@csrf @method('PATCH')<input type="hidden" name="action" value="measure"><div class="intake-car-map"><svg viewBox="0 0 180 360" aria-label="Bil sett ovenfra"><path class="car-shadow" d="M40 52Q45 18 90 12q45 6 50 40l14 58v180l-14 50H40l-14-50V110z"/><path class="car-body" d="M48 55Q52 28 90 22q38 6 42 33l12 60-8 165 8 45H36l8-45-8-165z"/><path class="car-glass" d="m57 72 12-30h42l12 30 7 48H50zM50 239h80l-9 66H59z"/><path class="car-line" d="M48 132h84M48 226h84M90 132v94"/></svg>@foreach(['Venstre foran','Høyre foran','Venstre bak','Høyre bak'] as $wheel)<label class="intake-wheel"><span>{{ $wheel }}</span><span><input name="depths[]" type="number" step="0.1" min="0" max="20" inputmode="decimal" placeholder="–" required><b>mm</b></span></label>@endforeach</div><button class="button full">Lagre alle fire mål</button></form></details>
 @else<div><small>NESTE STEG</small><strong>Velg lagerplass</strong></div><form class="intake-place" method="post" action="{{ route('workday.intake-step',$set) }}">@csrf @method('PATCH')<input type="hidden" name="action" value="place"><select name="storage_location_id" required><option value="">Velg reol</option>@foreach($locations as $location)<option value="{{ $location->id }}">{{ $location->code }} · {{ $location->tire_sets_count }}/{{ $location->capacity }}</option>@endforeach</select><button class="button">Plasser</button></form>
 @endif
 </div></article>
@empty<div class="empty-state"><strong>Mottaket er ryddig</strong><span>Ingen hjul uten kommende time trenger behandling nå.</span></div>@endforelse
</section>@endif
@if($area==='schedule')<section class="panel workday-schedule" id="schedule"><div class="panel-head"><div><p class="eyebrow">TIMEBOK I DAG</p><h2>{{ ['mine'=>'Mine timer','all'=>'Alle ansatte','bays'=>'Alle arbeidsbukker'][$scheduleMode] }}</h2><nav class="schedule-switch" aria-label="Velg timebokvisning"><a class="{{ $scheduleMode==='mine'?'active':'' }}" href="{{ route('workday',['area'=>'schedule','schedule'=>'mine']) }}">Mine</a><a class="{{ $scheduleMode==='all'?'active':'' }}" href="{{ route('workday',['area'=>'schedule','schedule'=>'all']) }}">Alle ansatte</a><a class="{{ $scheduleMode==='bays'?'active':'' }}" href="{{ route('workday',['area'=>'schedule','schedule'=>'bays']) }}">Arbeidsbukker</a></nav></div><span class="status">{{ $today->count() }}</span></div>
@if($scheduleMode==='bays')<div class="bay-schedule">@forelse($todayByBay as $bay=>$bookings)<section><h3>{{ $bay }}</h3>@foreach($bookings as $booking)<div class="work-card"><time>{{ $booking->is_drop_in?'Drop-in':$booking->starts_at->format('H:i') }}</time><div><strong>{{ $booking->vehicle?->registration_number ?? $booking->customer->name }}</strong><span>{{ $booking->customer->name }} · {{ $booking->service_name }}</span></div><span class="work-assignment">{{ $booking->assignedUser?->name??'Ikke tildelt' }}</span></div>@endforeach</section>@empty<div class="empty-state"><strong>Ingen timer i dag</strong></div>@endforelse</div>
@else @forelse($today as $booking)<div class="work-card"><time>{{ $booking->is_drop_in?'Drop-in':$booking->starts_at->format('H:i') }}</time><div><strong>{{ $booking->vehicle?->registration_number ?? $booking->customer->name }}</strong><span>{{ $booking->service_name }} · {{ $booking->customer->name }}</span></div>@if($scheduleMode==='all')<span class="work-assignment"><b>{{ $booking->assignedUser?->name??'Ikke tildelt' }}</b>{{ $booking->workBay?->code??'Uten bukk' }}</span>@else<span class="status {{ $booking->status }}">{{ $booking->status }}</span>@endif</div>@empty<div class="empty-state"><strong>Ingen timer i denne visningen</strong><span>Bytt til «Alle ansatte» for å se hele dagens plan.</span></div>@endforelse @endif
</section>@endif
@if($area==='preparation')<section class="panel prep-list" id="preparation"><div class="panel-head prep-head"><div><p class="eyebrow">MÅ KLARGJØRES</p><h2>{{ $prepMode==='week'?'Finn frem denne uken':'Finn frem til i morgen' }}</h2><nav class="prep-range" aria-label="Velg periode"><a class="{{ $prepMode==='tomorrow'?'active':'' }}" href="{{ route('workday',['area'=>'preparation','prep'=>'tomorrow']) }}">I morgen</a><a class="{{ $prepMode==='week'?'active':'' }}" href="{{ route('workday',['area'=>'preparation','prep'=>'week']) }}">Neste 7 dager</a></nav></div><span class="status prep-count">{{ $preparationBookings->count() }} timer</span></div>
@forelse($preparationBookings as $booking)<div class="prep-card"><time class="prep-time"><span>{{ $prepMode==='week'?$booking->starts_at->translatedFormat('D d.m'):'I morgen' }}</span><strong>{{ $booking->starts_at->format('H:i') }}</strong></time><div class="prep-vehicle"><strong>{{ $booking->vehicle?->registration_number ?? 'Uten bil' }}</strong><span>{{ $booking->customer->name }}</span><small>{{ $booking->service_name }}</small></div><div class="prep-locations">@php($wheelSets=$booking->vehicle?->tireSets ?? collect())@forelse($wheelSets as $set)<div class="prep-location {{ $set->status==='picked'?'is-ready':'' }}"><a href="{{ route('warehouse.map',['q'=>$set->code]) }}"><small>{{ $set->status==='picked'?'KLAR PÅ MOTTAK':'HENTES FRA' }}</small><strong>{{ $set->storageLocation?->code ?? 'Uten plass' }}{{ $set->storage_shelf_number?' · Hylle '.$set->storage_shelf_number:'' }}</strong><span>{{ $set->code }} <i>Vis på kart →</i></span></a>@if($set->status!=='picked')<form method="post" action="{{ route('workday.move',$set) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="picked"><input type="hidden" name="return_to" value="preparation"><input type="hidden" name="prep" value="{{ $prepMode }}"><button class="button prep-picked-button">✓ Legg klar på mottak</button></form>@else<span class="prep-ready-mark">✓ Ferdig</span>@endif</div>@empty<div class="prep-location missing"><small>MANGLER</small><strong>Ingen hjul registrert</strong></div>@endforelse</div></div>@empty<div class="empty-state"><strong>Ingen hjul må finnes frem i valgt periode</strong><span>Listen fylles automatisk fra kommende bookinger.</span></div>@endforelse
</section>@endif
<dialog class="camera-modal" data-camera-modal><div class="camera-head"><div><p class="eyebrow">SKANN ETIKETT</p><h2>Hold QR-koden foran kameraet</h2></div><button type="button" data-camera-close>×</button></div><video playsinline data-camera-video></video><p data-camera-status>Kameraet starter først når du trykker på knappen.</p><button class="button full" type="button" data-camera-start>Start kamera</button></dialog>
<script defer src="{{ asset('workday.js') }}"></script>
</x-layouts.app>
