<x-layouts.app title="Min arbeidsdag · DekkPilot" heading="Min arbeidsdag">
<link rel="stylesheet" href="{{ asset('workday-fixes.css') }}?v=20260810-1">
<link rel="stylesheet" href="{{ in_array(request()->getHost(),['localhost','127.0.0.1','::1'],true) ? route('system.asset',['filename'=>'workday-intake.css']) : asset('workday-intake.css') }}?v=20260812-1">
<style>.intake-measure{display:flex;align-items:end;gap:5px}.intake-measure label{display:grid;gap:2px}.intake-measure label span{color:var(--muted);font-size:8px;font-weight:850}.intake-measure input{width:58px;min-height:36px;padding:7px;font-size:12px}@media(max-width:600px){.intake-measure{display:grid;grid-template-columns:repeat(4,1fr)}.intake-measure input{width:100%}.intake-measure .button{grid-column:1/-1}}</style>
<section class="workday-hero panel"><div><p class="eyebrow">{{ auth()->user()->name }}</p><h2>{{ $today->count() }} timer satt av til deg i dag</h2><p>Skann én etikett for hele hjulsettet. DekkPilot holder oversikt over resten.</p></div><form method="get" action="{{ route('workday') }}" class="scan-bar"><label>Skann eller skriv hjulkode<input name="code" value="{{ $scanCode }}" placeholder="HJ-XXXXXXXX" autocomplete="off" autofocus data-scan-input></label><button class="button">Finn hjulsett</button><button class="button ghost" type="button" data-camera-open>▣ Bruk kamera</button></form></section>
@if($scanCode && !$scanned)<div class="errors">Fant ikke hjulkoden «{{ $scanCode }}». Kontroller etiketten og prøv igjen.</div>@endif
@if($scanned)<section class="panel scanned-set"><div class="scan-success">✓ Hjulsett funnet</div><div class="scanned-grid"><div><small>REGISTRERINGSNUMMER</small><strong class="scan-registration">{{ $scanned->vehicle->registration_number }}</strong><span>{{ $scanned->vehicle->customer->name }}</span></div><div><small>PLASSERING</small><strong>{{ $scanned->storageLocation?->code ?? 'MOTTAK' }}{{ $scanned->storage_shelf_number?' · Hylle '.$scanned->storage_shelf_number:'' }}</strong><span>{{ $scanned->code }}</span><a href="{{ route('warehouse.map',['q'=>$scanned->code]) }}">Vis på kart →</a></div><div><small>HJULSETT</small><strong>{{ $scanned->manufacturer }} {{ $scanned->size }}</strong><span>{{ $scanned->season==='winter'?'Vinter':'Sommer' }} · {{ $scanned->quantity }} hjul</span></div><div><small>STATUS</small><strong>{{ ['received'=>'Mottatt','stored'=>'På lager','picked'=>'Lagt klart','workshop'=>'På verksted','delivered'=>'Utlevert'][$scanned->status] }}</strong><span>Én handling gjelder hele settet</span></div></div><div class="workflow-actions">@foreach(['picked'=>'1. Lagt klart','workshop'=>'2. Til verksted','stored'=>'3. Tilbake på lager','delivered'=>'4. Utlevert'] as $status=>$label)<form method="post" action="{{ route('workday.move',$scanned) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="{{ $status }}"><button>{{ $label }}</button></form>@endforeach</div></section>@endif
<section class="panel intake-queue"><div class="panel-head"><div><p class="eyebrow">RYDD MOTTAK</p><h2>Hjul som skal inn på lager</h2><p>Viser mottatte hjul som ikke skal ut de neste fem dagene. Gjør bare neste steg.</p></div><span class="status">{{ $intakeSets->count() }}</span></div>
@forelse($intakeSets as $set)
 @php($step = !in_array($set->wash_status,['washed','not_needed'],true) ? 'wash' : ($set->minimum_tread_depth===null ? 'measure' : 'place'))
 <article class="intake-card"><div class="intake-main"><span class="intake-season">{{ $set->season==='winter'?'Vinter':'Sommer' }}</span><div><strong>{{ $set->vehicle->registration_number }}</strong><small>{{ $set->vehicle->customer->name }} · {{ $set->code }} · mottatt {{ $set->received_at->format('d.m') }}</small></div></div><ol class="intake-progress"><li class="{{ $step==='wash'?'active':'done' }}">1 Vask</li><li class="{{ $step==='measure'?'active':($step==='place'?'done':'') }}">2 Mål</li><li class="{{ $step==='place'?'active':'' }}">3 Plasser</li></ol><div class="intake-next">
 @if($step==='wash'&&$set->wash_status==='needed')<div><small>NESTE STEG</small><strong>Vask hjulsettet</strong></div><form method="post" action="{{ route('workday.intake-step',$set) }}">@csrf @method('PATCH')<input type="hidden" name="action" value="washed"><button class="button">✓ Ferdig vasket</button></form>
 @elseif($step==='wash')<div><small>NESTE STEG</small><strong>Trenger hjulene vask?</strong></div><div class="intake-buttons"><form method="post" action="{{ route('workday.intake-step',$set) }}">@csrf @method('PATCH')<input type="hidden" name="action" value="wash_needed"><button class="button">Ja, må vaskes</button></form><form method="post" action="{{ route('workday.intake-step',$set) }}">@csrf @method('PATCH')<input type="hidden" name="action" value="skip_wash"><button class="button ghost">Nei, fortsett</button></form></div>
 @elseif($step==='measure')<div><small>NESTE STEG</small><strong>Mål alle fire hjul</strong></div><form class="intake-measure" method="post" action="{{ route('workday.intake-step',$set) }}">@csrf @method('PATCH')<input type="hidden" name="action" value="measure">@foreach(['VF','HF','VB','HB'] as $wheel)<label><span>{{ $wheel }}</span><input name="depths[]" type="number" step="0.1" min="0" max="20" inputmode="decimal" placeholder="mm" required></label>@endforeach<button class="button">Lagre mål</button></form>
 @else<div><small>NESTE STEG</small><strong>Velg lagerplass</strong></div><form class="intake-place" method="post" action="{{ route('workday.intake-step',$set) }}">@csrf @method('PATCH')<input type="hidden" name="action" value="place"><select name="storage_location_id" required><option value="">Velg reol</option>@foreach($locations as $location)<option value="{{ $location->id }}">{{ $location->code }} · {{ $location->tire_sets_count }}/{{ $location->capacity }}</option>@endforeach</select><button class="button">Plasser</button></form>
 @endif
 </div></article>
@empty<div class="empty-state"><strong>Mottaket er ryddig</strong><span>Ingen hjul uten kommende time trenger behandling nå.</span></div>@endforelse
</section>
<section class="workday-grid"><article class="panel"><div class="panel-head"><div><p class="eyebrow">MIN PLAN I DAG</p><h2>Timene dine</h2></div><span class="status">{{ $today->count() }}</span></div>
@forelse($today as $booking)<div class="work-card"><time>{{ $booking->is_drop_in?'Drop-in':$booking->starts_at->format('H:i') }}</time><div><strong>{{ $booking->vehicle?->registration_number ?? $booking->customer->name }}</strong><span>{{ $booking->service_name }} · {{ $booking->customer->name }}</span></div><span class="status {{ $booking->status }}">{{ $booking->status }}</span></div>@empty<div class="empty-state"><strong>Ingen timer er tildelt deg i dag</strong><span>Avdelingsleder kan tildele ansatte når timen bookes.</span></div>@endforelse
</article><article class="panel prep-list"><div class="panel-head"><div><p class="eyebrow">KLARGJØRING</p><h2>Finn frem til i morgen</h2></div><span class="status prep-count">{{ $tomorrow->count() }} timer</span></div>
@forelse($tomorrow as $booking)<div class="prep-card"><time>{{ $booking->starts_at->format('H:i') }}</time><div class="prep-vehicle"><strong>{{ $booking->vehicle?->registration_number ?? 'Uten bil' }}</strong><span>{{ $booking->customer->name }} · {{ $booking->service_name }}</span></div><div class="prep-locations">@php($wheelSets=$booking->vehicle?->tireSets ?? collect())@forelse($wheelSets as $set)<a class="prep-location" href="{{ route('warehouse.map',['q'=>$set->code]) }}"><small>{{ $set->status==='picked'?'KLAR':'FINN FREM' }}</small><strong>{{ $set->storageLocation?->code ?? 'MOTTAK' }}{{ $set->storage_shelf_number?' · Hylle '.$set->storage_shelf_number:'' }}</strong><span>{{ $set->code }} · kart →</span></a>@empty<div class="prep-location missing"><small>MANGLER</small><strong>Ingen hjul registrert</strong></div>@endforelse</div></div>@empty<div class="empty-state"><strong>Ingen hjul må finnes frem til i morgen</strong><span>Listen fylles automatisk fra morgendagens bookinger.</span></div>@endforelse
</article></section>
<dialog class="camera-modal" data-camera-modal><div class="camera-head"><div><p class="eyebrow">SKANN ETIKETT</p><h2>Hold strekkoden foran kameraet</h2></div><button type="button" data-camera-close>×</button></div><video playsinline data-camera-video></video><p data-camera-status>Kameraet starter først når du trykker på knappen.</p><button class="button full" type="button" data-camera-start>Start kamera</button></dialog>
<script defer src="{{ asset('workday.js') }}"></script>
</x-layouts.app>
