<x-layouts.app title="Lagerkart · DekkPilot" heading="Finn hjul">
<link rel="stylesheet" href="{{ asset('warehouse-map.css') }}?v=20260810-2">
<link rel="stylesheet" href="{{ asset('warehouse-shelves.css') }}?v=20260810-1">
<link rel="stylesheet" href="{{ asset('warehouse-floorplan.css') }}?v=20260810-2">
<section class="panel map-search-panel"><div><p class="eyebrow">TEKNIKERKART</p><h2>Hvor ligger hjulene?</h2><p>Søk på registreringsnummer, kunde eller hjulkode. Riktig reol og hylle markeres.</p></div><form method="get" class="map-search"><input name="q" value="{{ $search }}" placeholder="Reg.nr., navn eller HJ-kode" autofocus><button class="button">Finn plass</button>@if($search)<a href="{{ route('warehouse.map') }}">Nullstill</a>@endif</form></section>
<section class="stats warehouse-stats"><article><span class="stat-icon green">▦</span><div><small>REOLER/PLASSER</small><strong>{{ $stats['locations'] }}</strong></div></article><article><span class="stat-icon blue">◎</span><div><small>KAPASITET</small><strong>{{ $stats['capacity'] }}</strong></div></article><article><span class="stat-icon violet">●</span><div><small>I BRUK</small><strong>{{ $stats['occupied'] }}</strong></div></article><article><span class="stat-icon orange">!</span><div><small>UTEN PLASS</small><strong>{{ $stats['unplaced'] }}</strong></div></article></section>
@if($search)<section class="panel map-results"><div class="panel-head"><div><p class="eyebrow">SØKERESULTAT</p><h2>{{ $matches->count() }} treff på «{{ $search }}»</h2></div></div>@forelse($matches as $set)<a href="#map-location-{{ $set->storage_location_id }}"><span class="plate-inline">{{ $set->vehicle->registration_number }}</span><div><strong>{{ $set->vehicle->customer->name }}</strong><small>{{ $set->code }} · {{ $set->manufacturer }} {{ $set->size }}</small></div><b>{{ $set->storage_label }} →</b></a>@empty<div class="empty-state"><strong>Ingen hjulsett funnet</strong><span>Kontroller registreringsnummeret eller skann etiketten på nytt.</span></div>@endforelse</section>@endif
<section class="panel"><div class="panel-head"><div><p class="eyebrow">DIN AVDELING SETT OVENFRA</p><h2>Hvor står reolen?</h2><p>Dra kartet med én finger. Trykk på en reol for å åpne innholdet.</p></div><div class="map-legend"><span><i class="free"></i>Ledig</span><span><i class="busy"></i>I bruk</span><span><i class="full"></i>Full</span><span><i class="highlight"></i>Treff</span></div></div><div class="warehouse-map-toolbar" aria-label="Kartvisning"><button type="button" class="map-tool" data-map-zoom-out aria-label="Zoom ut">−</button><output data-map-zoom-label aria-live="polite">100 %</output><button type="button" class="map-tool" data-map-zoom-in aria-label="Zoom inn">+</button><button type="button" class="map-fit-button" data-map-fit>Vis hele kartet</button></div><div class="warehouse-map-viewport" data-map-viewport tabindex="0" aria-label="Lagerkart. Dra for å flytte kartet."><div class="warehouse-map-stage" data-map-stage><div class="warehouse-canvas warehouse-floorplan technician-floorplan" data-map-surface>@forelse($locations as $location)@php
    $locationMatches = $matches->where('storage_location_id', $location->id);
    $available = max(0, $location->capacity - $location->tire_sets_count);
    $usage = $location->capacity > 0 ? $location->tire_sets_count / $location->capacity : 0;
@endphp<a id="map-location-{{ $location->id }}" class="floor-rack {{ $locationMatches->isNotEmpty()?'highlight':($usage>=1?'full':($usage>=.75?'busy':'free')) }}" href="{{ route('inventory',['location_id'=>$location->id]) }}" style="--x:{{ $location->map_x??3 }};--y:{{ $location->map_y??5 }}"><small>{{ $location->zone }}</small><strong>{{ $location->code }}</strong><b>{{ $location->tire_sets_count }}/{{ $location->capacity }} i bruk</b><span>{{ $available }} ledige</span>@if($locationMatches->isNotEmpty())<em>FINN HER · L{{ $locationMatches->first()->storage_position_number??'?' }} / H{{ $locationMatches->first()->storage_shelf_number??'?' }}</em>@endif</a>@empty<div class="map-empty"><strong>Lagerkartet er ikke bygget ennå</strong>@if(in_array(auth()->user()->role,['owner','admin'],true)||auth()->user()->is_super_admin)<a class="button" href="{{ route('admin.warehouse') }}">Bygg lageret</a>@endif</div>@endforelse</div></div></div><p class="warehouse-map-hint">Dra kartet sidelengs eller opp og ned. Bruk knappene for å zoome.</p></section>
<script defer src="{{ asset('warehouse-navigator.js') }}?v=20260811-3"></script>
</x-layouts.app>
