@php($legalCss = in_array(request()->getHost(), ['localhost','127.0.0.1','::1'], true) ? route('system.asset', ['filename' => 'legal.css']) : asset('legal.css'))
<!doctype html><html lang="nb"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="index,follow"><title>Databehandleravtale · DekkPilot</title><link rel="stylesheet" href="{{ $legalCss }}?v=20260812-1"></head><body class="legal-page">
<header class="legal-topbar"><div class="legal-topbar-inner"><a class="legal-brand" href="{{ url('/') }}"><span class="legal-brand-mark">D</span><span>DekkPilot</span></a><nav class="legal-nav" aria-label="Juridiske dokumenter"><a href="{{ route('legal.privacy') }}">Personvern</a><a href="{{ route('legal.terms') }}">Vilkår</a><a href="{{ route('legal.dpa') }}" aria-current="page">Databehandleravtale</a></nav></div></header>
<main class="legal-wrap"><section class="legal-hero"><p class="legal-kicker">Avtale om behandling av personopplysninger</p><h1>Databehandleravtale</h1><p>Avtalen regulerer DekkPilots behandling av personopplysninger på vegne av virksomheten som bruker tjenesten, i samsvar med personvernforordningen artikkel 28.</p></section><article class="legal-document"><div class="legal-meta"><span>Versjon 12. august 2026</span><span>Vedlegg til bruksvilkårene</span></div>
<h2>1. Partene og formålet</h2><p>Virksomheten som oppretter og bruker en DekkPilot-konto er behandlingsansvarlig («kunden»). Leverandøren av DekkPilot er databehandler. Avtalen gjelder når DekkPilot behandler personopplysninger som kunden registrerer eller gjør tilgjengelig i tjenesten.</p><p>Formålet er å levere et driftssystem for blant annet kunderegister, kjøretøy, hjulsett, booking, kommunikasjon, tilbud, betaling og regnskapsflyt.</p>
<h2>2. Behandlingens art og varighet</h2><p>Behandlingen omfatter innsamling, registrering, strukturering, lagring, søk, visning, endring, eksport, kommunikasjon og sletting som er nødvendig for å levere tjenesten. Behandlingen varer så lenge kundeavtalen består, og deretter i den perioden som følger av dokumenterte slette- og sikkerhetskopirutiner eller lovpålagte krav.</p>
<h2>3. Opplysninger og registrerte</h2><p>Opplysningene kan omfatte navn, adresse, telefonnummer, e-post, kjøretøy- og registreringsnummer, bookinghistorikk, tilbud, meldingshistorikk, betalingsstatus, medarbeideropplysninger, tekniske logger og annen informasjon kunden legger inn.</p><p>Registrerte kan være kundens privat- og bedriftskunder, kontaktpersoner, ansatte, innleide og andre personer kunden velger å registrere. Tjenesten er ikke ment for særlige kategorier personopplysninger etter artikkel 9.</p>
<h2>4. Instruks og ansvar</h2><p>DekkPilot skal bare behandle opplysningene etter dokumenterte instrukser fra kunden, med mindre norsk eller europeisk lov krever annet. Bruk av tjenestens funksjoner, valgte integrasjoner, bruksvilkårene og denne avtalen utgjør kundens dokumenterte instruks.</p><p>Kunden er ansvarlig for behandlingsgrunnlag, informasjon til de registrerte, riktige tilgangsroller, lovlig markedsføring og at opplysningene som registreres er relevante og nødvendige.</p>
<h2>5. Taushet og sikkerhet</h2><p>Personer med tilgang til opplysningene skal være underlagt taushetsplikt. Leverandøren skal opprettholde egnede tekniske og organisatoriske tiltak basert på risiko, herunder tilgangskontroll, virksomhetsisolasjon, kryptert transport, logging, sikkerhetskopiering, oppdateringer og rutiner for gjenoppretting.</p>
<h2>6. Underleverandører</h2><p>Kunden gir generell tillatelse til bruk av underdatabehandlere som er nødvendige for hosting, e-post, SMS, drift, overvåking og andre aktiverte integrasjoner. Leverandøren skal stille tilsvarende personvernforpliktelser til underdatabehandlerne og informere om vesentlige endringer slik at kunden kan fremsette en saklig innsigelse.</p><p>Oppdatert oversikt over underdatabehandlere kan forespørres på <a href="mailto:hei@dekkpilot.no">hei@dekkpilot.no</a>. Integrasjoner kunden selv aktiverer kan også innebære at mottakeren er selvstendig behandlingsansvarlig etter sine egne vilkår.</p>
<h2>7. Overføring utenfor EØS</h2><p>Personopplysninger skal ikke overføres utenfor EØS uten gyldig overføringsgrunnlag og nødvendige tilleggstiltak. Kunden skal informeres når valg av underleverandør eller integrasjon innebærer slik overføring.</p>
<h2>8. Bistand til kunden</h2><p>Leverandøren skal, så langt det er mulig og rimelig, bistå kunden med forespørsler om innsyn, retting, sletting, begrensning, dataportabilitet og protest. Leverandøren skal også bistå med informasjon som er nødvendig for risikovurderinger, avvikshåndtering og eventuell vurdering av personvernkonsekvenser. Arbeid utenfor ordinær tjenesteleveranse kan faktureres dersom dette er avtalt på forhånd.</p>
<h2>9. Brudd på personopplysningssikkerheten</h2><p>Leverandøren skal varsle kunden uten ugrunnet opphold etter å ha blitt kjent med et brudd som berører kundens opplysninger. Varselet skal, så langt informasjonen er tilgjengelig, beskrive hendelsen, sannsynlige konsekvenser, berørte data og registrerte samt gjennomførte eller foreslåtte tiltak.</p>
<h2>10. Innsyn og revisjon</h2><p>Leverandøren skal gjøre nødvendig informasjon tilgjengelig for å dokumentere etterlevelse av denne avtalen. Kunden kan be om en rimelig revisjon etter forhåndsvarsel. Revisjonen skal gjennomføres uten unødig belastning, fare for andre kunders sikkerhet eller tilgang til deres data.</p>
<h2>11. Avslutning, utlevering og sletting</h2><p>Ved avtalens opphør kan kunden be om eksport av egne data innen rimelig tid. Deretter slettes eller anonymiseres personopplysningene, med mindre lov krever videre lagring. Data i sikkerhetskopier slettes gjennom ordinær rotasjon og skal ikke brukes til andre formål.</p>
<h2>12. Prioritet og endringer</h2><p>Ved motstrid om behandling av personopplysninger går denne avtalen foran de alminnelige bruksvilkårene. Vesentlige endringer varsles før de trer i kraft. Norsk rett gjelder.</p>
<div class="legal-note"><strong>Før avtalen tas i kommersiell bruk</strong>Leverandørens juridiske navn, organisasjonsnummer, adresse, konkrete underdatabehandlere, lagringssteder og slettefrister må bekreftes og avtalen bør kvalitetssikres av juridisk rådgiver.</div>
<div class="legal-contact"><strong>Kontakt</strong><p>Spørsmål om avtalen eller behandling av personopplysninger: <a href="mailto:hei@dekkpilot.no">hei@dekkpilot.no</a></p></div></article><footer class="legal-footer"><span>© 2026 DekkPilot</span><a href="{{ url('/') }}">Tilbake til forsiden →</a></footer></main></body></html>
