<!doctype html><html lang="nb"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Personvern · DekkPilot</title><link rel="stylesheet" href="{{ asset('app.css') }}"><link rel="stylesheet" href="{{ asset('admin.css') }}"></head><body class="auth-page"><main class="auth-card" style="max-width:820px">
<div class="brand"><span class="brandmark">D</span><span>DekkPilot<small>Personvern</small></span></div><p class="eyebrow">VERSJON 9. AUGUST 2026</p><h1>Personvernerklæring</h1>
<p>DekkPilot behandler konto-, virksomhets-, bruks- og tekniske data for å levere og sikre tjenesten, administrere abonnementet, gi kundestøtte og oppfylle lovkrav.</p>
<h2>Hvilke opplysninger vi behandler</h2><p>Dette kan omfatte navn, kontaktinformasjon, virksomhetstilknytning, innloggings- og sikkerhetslogger, avtaleaksepter, fakturainformasjon og opplysninger kunden selv legger inn om sine kunder, kjøretøy, bookinger og hjulsett.</p>
<h2>Roller og behandlingsgrunnlag</h2><p>DekkPilot er behandlingsansvarlig for konto- og abonnementsdata. For opplysninger kunden legger inn om egne kunder og ansatte, er kunden behandlingsansvarlig og DekkPilot databehandler. Behandlingen bygger på avtale, rettslige plikter, samtykke der det kreves, og berettiget interesse i sikker drift.</p>
<h2>Deling og databehandlere</h2><p>Opplysninger deles bare når det er nødvendig med leverandører av hosting, e-post, SMS, fakturering, regnskap og integrasjoner, eller når loven krever det. Data skal ikke selges. Overføring utenfor EØS skal sikres med gyldig overføringsgrunnlag.</p>
<h2>Lagring og sikkerhet</h2><p>Opplysninger lagres så lenge kontoen er aktiv eller det er nødvendig etter avtalen og loven. DekkPilot bruker tilgangskontroll, virksomhetsisolasjon, kryptert kommunikasjon, logging og sikkerhetskopiering for å redusere risiko.</p>
<h2>Dine rettigheter</h2><p>Du kan be om innsyn, retting, sletting, begrensning, dataportabilitet eller protestere mot behandling der vilkårene er oppfylt. Du kan også klage til Datatilsynet.</p>
<p>Kontakt <a href="mailto:hei@dekkpilot.no">hei@dekkpilot.no</a> ved spørsmål eller rettighetskrav.</p><p class="fine">Erklæringen og databehandleravtalen bør kvalitetssikres juridisk før kommersiell lansering.</p></main></body></html>
