<!doctype html><html lang="nb"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bruksvilkår (EULA) · DekkPilot</title><link rel="stylesheet" href="{{ asset('app.css') }}"><link rel="stylesheet" href="{{ asset('admin.css') }}"></head><body class="auth-page"><main class="auth-card" style="max-width:820px">
<div class="brand"><span class="brandmark">D</span><span>DekkPilot<small>Bruksvilkår</small></span></div><p class="eyebrow">VERSJON 9. AUGUST 2026</p><h1>Bruksvilkår (EULA)</h1>
<p>Disse vilkårene gjelder mellom DekkPilot («leverandøren») og virksomheten som oppretter konto («kunden»). Personen som registrerer kontoen bekrefter at vedkommende har rett til å binde virksomheten.</p>
<h2>1. Tjenesten og bruksretten</h2><p>Kunden får en begrenset, ikke-eksklusiv og ikke-overførbar rett til å bruke DekkPilot som nettbasert driftssystem i egen virksomhet. Kunden er ansvarlig for brukere, tilgangsstyring, riktige opplysninger og forsvarlig bruk.</p>
<h2>2. Pris og fakturering</h2><p>Tjenesten koster 119 kroner per måned inkludert merverdiavgift, uten bindingstid. SMS faktureres separat etter faktisk bruk. Tilgang gis umiddelbart etter virksomhetskontroll og aksept. Inntil fakturaløsningen er aktivert kreves ingen betaling i registreringen. Leverandøren kan starte fakturering i samsvar med avtalt pris etter skriftlig varsel.</p>
<p>En gyldig kampanjekode kan gi 100 prosent rabatt ut den kalendermåneden koden gjelder for. Koden gir ikke rabatt etter utløpsdatoen.</p>
<h2>3. Kundedata og personopplysninger</h2><p>Kunden eier egne data og er behandlingsansvarlig for personopplysninger som legges inn. DekkPilot behandler disse på kundens vegne for å levere, sikre og forbedre tjenesten. Kunden må ha lovlig grunnlag for registrering og utsendelser. En databehandleravtale gjøres tilgjengelig før ordinær produksjonslansering.</p>
<h2>4. Integrasjoner</h2><p>Tjenesten kan bruke tredjepartstjenester, blant annet Brønnøysundregistrene, Statens vegvesen, e-post, SMS og regnskapssystemer. Tilgjengelighet og vilkår hos tredjepart kan endres. Kunden er ansvarlig for egne API-nøkler og avtaler der dette kreves.</p>
<h2>5. Tillatt bruk og sikkerhet</h2><p>Kunden skal ikke forsøke å omgå sikkerhet, få tilgang til andre virksomheters data, spre skadevare eller bruke tjenesten ulovlig. Passord og API-nøkler skal holdes hemmelige. Misbruk kan medføre midlertidig sperring.</p>
<h2>6. Tilgjengelighet og ansvar</h2><p>Leverandøren skal arbeide for stabil og sikker drift, men garanterer ikke uavbrutt tilgjengelighet. Ansvar for indirekte tap, driftstap og tapt fortjeneste er begrenset så langt loven tillater. Samlet direkte ansvar er begrenset til betalt abonnementsvederlag de siste tolv månedene, med unntak der ufravikelig lov bestemmer noe annet.</p>
<h2>7. Varighet, oppsigelse og eksport</h2><p>Avtalen løper månedlig og kan sies opp uten bindingstid. Ved avslutning kan kunden be om eksport av egne data innen rimelig tid. Data slettes eller anonymiseres etter gjeldende rutiner og lovkrav.</p>
<h2>8. Endringer og lovvalg</h2><p>Vesentlige endringer varsles før de trer i kraft. Norsk rett gjelder. Tvister søkes løst i minnelighet og behandles ellers av norske domstoler.</p>
<p class="fine">Spørsmål kan sendes til <a href="mailto:hei@dekkpilot.no">hei@dekkpilot.no</a>. Dette dokumentet bør kvalitetssikres juridisk før kommersiell lansering.</p></main></body></html>
